### ISSUE TITLE
how to get number of nodes after doc.child("node")

### ISSUE THREAD

**Issue by cowabunga1** [zeux/pugixml#101]
Hi, how can i get number of nodes after:

`pugi::xml_node nodes = doc.child("node");`

on xml:

```
<node name="1"></node>
<node name="2"></node>
<node name="3"></node>
```

mb `nodes.get_count()` ?

**Comment by zeux** [comment]
The easiest way is to do something like:

```
auto nodes = doc.children("node");
size_t count = std::distance(nodes.begin(), nodes.end());
```

(needs C++11 for auto and <iterator> include)

If you only have "node" children in the document, you can just do:

```
size_t count = std::distance(doc.begin(), doc.end());
```

**Comment by cowabunga1** [comment]
Thank you!
