### ISSUE TITLE
Make xml_document moveable

### ISSUE THREAD

**Issue by sezaru** [zeux/pugixml#104]
Hello there, can you implement move semantics for the pugi::xml_document?

The idea is to enable code like
auto document = pugi::xml_document{};

or

auto function()
{
  auto document = pugi::xml_document{};
  ...
  return std::move(document);
}

Thanks!

**Comment by adamfowleruk** [comment]
+1 I just got caught out by this too. I have a Document Wrapper (one for XML, another for JSON, and so on) and being able to pass on ownership of the document using move semantics would be very useful.

**Comment by zeux** [comment]
I'll look into this. For now note that you can work around the lack of move support by using unique_ptr.

**Comment by zeux** [comment]
Note: this did not make it into 1.8 because the implementation is surprisingly involved and I did not want to risk it. Will try to get it in for the next release though.

**Comment by dpservis** [comment]
+1

**Comment by ilya1725** [comment]
+1

**Comment by zeux** [comment]
FWIW move branch (https://github.com/zeux/pugixml/tree/move) has a preliminary version of move semantics support for documents; it seems reasonably stable but there are some edge cases with compact mode left that I'll need to resolve before merging to master as well as a few more tests to write.
