### ISSUE TITLE
Does pugixml support on Linux Environment?

### ISSUE THREAD

**Issue by Ajayiosdeveloper** [zeux/pugixml#105]
Hello Team,

Sorry for asking this in as an issue first.But no other way out to know this.

I am working on a Swift Project and need to use XML Parser that has xPath support too.Will pugixml work on Linux environment?

Thanks.

**Comment by kirbyfan64** [comment]
I've used it on my Linux PC before, so that should be a "yes".

**Comment by zeux** [comment]
Yes, pugixml fully supports Linux (as well as other major operating systems). This is mentioned in the manual (http://pugixml.org/docs/manual.html#install.portability) and sort of mentioned on pugixml.org.
