### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by steji113** [zeux/pugixml#107]
I was wondering if there was anyway you guys could make a few more options for your Nuget packages. I am currently in need of a VS2013 build with runtime library of MT and MTd. I am not sure what the effort involved in this would be. I can attempt to learn how to build these packages and contribute, too if needed.

Thanks!

**Comment by zeux** [comment]
I've uploaded a new version built from branch nuget-1.7 (which includes sources for 1.7 and all script changes required to build an up-to-date package). Can you verify it works as expected?

https://www.nuget.org/packages/pugixml/1.7.1

**Comment by steji113** [comment]
I will try first thing in the morning at work tomorrow. Thanks for all of your help!

**Comment by steji113** [comment]
@zeux It seems the static pivot inside of the .autopkg might be causing some issues. Once I took that out in the generated targets file it seemed to all work correctly. It selected the VS 2013 binaries for me. I can submit a new pull request with this moved if you would like.

**Comment by zeux** [comment]
Yes please.
