### ISSUE TITLE
cmake: shared library does not produce export library on Windows

### ISSUE THREAD

**Issue by snikulov** [zeux/pugixml#113]
When build with `-DBUILD_SHARED_LIBS=ON` build stage does not produce export symbols library.

Perhaps the better way is add following lines to [CMakeLists.txt](https://github.com/zeux/pugixml/blob/master/CMakeLists.txt#L38)

```
if(BUILD_SHARED_LIBS)
        add_library(pugixml SHARED ${SOURCES})
+       if(WIN32)
+           set_property(TARGET pugixml APPEND PROPERTY COMPILE_DEFINITIONS "PUGIXML_API=__declspec(dllexport)")
+       endif()
```

**Comment by snikulov** [comment]
@zeux any issues with this change?

**Comment by zeux** [comment]
@snikulov Is there anything special necessary to distinguish between dllexport & dllimport? I'm not very familiar with CMake, but it seems that if you were to use pugixml in a larger project driven by CMake, you'd want to set PUGIXML_API to dllimport in all dependent projects and to dllexport in pugixml project itself.

**Comment by snikulov** [comment]
@zeux perhaps somewhere in interface header you should add for windows

```
#ifdef WIN32
#ifndef PUGIXML_API // will be defined by cmake build when building library
#definet PUGIXML_API=__declspec(dllimport)
#endif            // PUGIXML_API
#endif            // WIN32

```
This will import shared library by default, and export will be only during shared library build.

**Comment by zeux** [comment]
That doesn't work because it assumes pugixml should be always built as a DLL.. I could add some define like PUGIXML_DLL and change pugixml.hpp to define PUGIXML_API based on that, but this still leaves a question as to how to make pugixml CMake target expose a define to other CMake projects that depend on it.

**Comment by zeux** [comment]
https://www.reddit.com/r/cpp/comments/6t4kse/c17_features_and_stl_fixes_in_vs_2017_153/dlhxni2/ implies that dllimport is not necessary for functions since VC2010, but still is necessary for classes :(

**Comment by zeux** [comment]
While this seems to contradict the information in the link above, it's actually sufficient to use dllexport even though pugixml exports classes. If we ever need dllimport it should be possible to specify it using `target_compile_definitions` with `INTERFACE` though.
