### ISSUE TITLE
invalid character cannot escape

### ISSUE THREAD

**Issue by c1rew** [zeux/pugixml#114]
< > is invalid character in xml file
Text: <>
ANSI:3C3E
UTF-8:3C3E
these characters can be escaped normally;

when i read a string from sqlite3 database, it contain 'C0BC'
UTF-8:C0BCC0BE
ANSI:3C3E
Text:<>

pugixml cannot escape these,
so, i get a xml file that attribute value contain '<>'

**Comment by zeux** [comment]
My understanding is that C0BC is an overlong encoding of U+003C which is an invalid UTF-8 sequence.:

> The standard specifies that the correct encoding of a code point use only the minimum number of bytes required to hold the significant bits of the code point. Longer encodings are called overlong and are not valid UTF-8 representations of the code point. This rule maintains a one-to-one correspondence between code points and their valid encodings, so that there is a unique valid encoding for each code point. This ensures that string comparisons and searches are well-defined.

pugixml does not filter these in any way. Do you know why your database has a string that contains C0BC instead of 3C?

**Comment by zeux** [comment]
Possibly related: https://www.sqlite.org/debug1/info/636da047cc599fa4 (not sure what specific stage is this validation code used at in SQLite)

**Comment by c1rew** [comment]
Oops,that is my fault, the version of sqlite3 for my project is before 2014, so, it is wrong.
thanks, the related answer is great.
