### ISSUE TITLE
Add flag do_not_serialize_element.

### ISSUE THREAD

**Issue by dahrens1701** [zeux/pugixml#118]
I am using a 3rd party application that does not always understand self-closing empty elements. (<foo />).  Would it be possible to add a flag to force empty elements to close the old fashion way? (<foo></foo>)

**Comment by zeux** [comment]
This is not the first time I'm getting this request/question - I'll look into adding this.

For now you can work around this by adding a pcdata child with empty content, e.g. node.text().set("") should do the trick (of course this is not very efficient and just plain weird! but if you *have* to do it right now this is how).
