### ISSUE TITLE
pugixml-1.8.tar.gz is borked.

### ISSUE THREAD

**Issue by LebedevRI** [zeux/pugixml#124]
@zeux Hi.

The `pugixml-1.8.tar.gz` has wrong timestamps for files - `Jan  1  1970`

According to https://github.com/Homebrew/homebrew-core/commit/556a412cad8d1e2b9ac3b5b449551da2a40d0d18#commitcomment-19974265, this is the reason why `homebrew` packages of `pugixml-1.8` are broken, in particular:
```
$ ls -lah /usr/local/Cellar/pugixml/1.8/lib/pugixml-1.8/libpugixml.a
-r--r--r--  1 travis  admin   206K Jan  1  1970 /usr/local/Cellar/pugixml/1.8/lib/pugixml-1.8/libpugixml.a
```

That completely breaks ninja build system, and cripples ld.
If i touch that file, it works.

**Comment by zeux** [comment]
Ugh. I thought I checked this but maybe I only did for zip archive. Will look into this ASAP.

**Comment by zeux** [comment]
Ah, I see - Far Manager tricked me by displaying correct timestamps for the tar file, whereas tar utility displays Jan 1970.

**Comment by LebedevRI** [comment]
@zeux 
Long story short: i'd just upload back the original pugixml-1.8.tar.gz (see https://github.com/Homebrew/homebrew-core/commit/556a412cad8d1e2b9ac3b5b449551da2a40d0d18#commitcomment-19974686)
And make a new release 1.8.1, with now-proper tarball.

**Comment by zeux** [comment]
@LebedevRI Yup, done - https://github.com/zeux/pugixml/releases/tag/v1.8.1. Thanks for the help! I'll try to keep the "never-reupload-uploaded-packages" rule in mind for the future :)
