### ISSUE TITLE
Overflow in src/pugixml.cpp:4524

### ISSUE THREAD

**Issue by jbakosi** [zeux/pugixml#125]
I'm trying to build using the Cray compiler, which refuses to build producing the following error:
```
CC-3059 crayc++: INTERNAL __C_FILE_SCOPE_DATA__, File = <pugixml>/src/pugixml.cpp, Line = 4524, Column = 4 
  Expected no overflow in routine.
```

The line in questions is in ```template <typename U> U string_to_integer(const char_t* value, U minneg, U maxpos)```:
```
return (overflow || result > minneg) ? 0 - minneg : 0 - result;
```
attempting to subtract a positive integer from zero. Not sure why gnu/clang/intel compilers do not complain, but the Cray compiler appears to do rightly so. Is there an easy fix?

**Comment by zeux** [comment]
Does replacing both zeroes with U(0) fix the issue?

**Comment by jbakosi** [comment]
No, it does not. I believe the problem the compiler does not like is that subtracting any positive number from zero (as is the case with both `minneg` and `result`, since they are unsigned) will always underflow.

**Comment by zeux** [comment]
I guess I don't really understand why the compiler considers it a problem - underflow is well defined for unsigned numbers. Is this a warning-promoted-to-an-error or an error?

The reason the function is doing this is that the only way to safely get INT_MIN by negating a number is to do it in unsigned space - anything else would either be undefined or would rely on two-complement semantics. I need to think on whether there's any other way to achieve this...

**Comment by zeux** [comment]
This is stupid, but does something like

    return (overflow || result > minneg) ? (1 - minneg) - 1 : (1 - result) - 1;

silence this? :)

**Comment by jbakosi** [comment]
No, that does not silence it either. Unfortunately, I'm not very familiar with the Cray compiler. I don't think this is a warning-promoted-to-an-error: I'm simply compiling with
```
CC -o pugixml.cpp.o -c pugixml.cpp
```
So this is the default behavior.

Also, I'm not finding anything relevant in the [reference manual](http://docs.cray.com/books/S-2179-84/S-2179-84.pdf) or the [manual page](http://docs.cray.com/cgi-bin/craydoc.cgi?mode=Show;q=id%3dcrayCC.1;f=man/xt_ccm/83/cat1/crayCC.1.html).

**Comment by zeux** [comment]
I guess one option is to switch to two-complement version for Cray to avoid this, something like:

    #ifdef _CRAYC
        return (overflow || result > minneg) ? ~minneg + 1 : ~result + 1;
    #else
        return (overflow || result > minneg) ? 0 - minneg : 0 - result;
    #endif

I'm somewhat surprised that the same error does not happen for things like this though:

    return string_to_integer<unsigned int>(value, 0 - static_cast<unsigned int>(INT_MIN), INT_MAX);

**Comment by jbakosi** [comment]
`0 - static_cast<unsigned int>(INT_MIN)` is fine because INT_MIN is negative so subtracting a negative from zero in an unsigned is fine.

`return (overflow || result > minneg) ? ~minneg + 1 : ~result + 1` compiles fine.

**Comment by zeux** [comment]
> 0 - static_cast<unsigned int>(INT_MIN) is fine because INT_MIN is negative so subtracting a negative from zero in an unsigned is fine.

That doesn't really make sense to me. INT_MIN is negative but after casting to unsigned it's very much positive. Anyway, for now it does not seem like there's any option other than to apply the aforementioned workaround. I'll look to see separately if there is a way to refactor this code to reduce the amount of signed/unsigned casting which could help as well.
