### ISSUE TITLE
node.next_sibling() is not traversing to the next node.

### ISSUE THREAD

**Issue by HemanthMChakravarthy** [zeux/pugixml#138]
Hello,

I am trying to read a big xml file using the library you provided.
node.next_sibling() is not traversing to the next node.

when I use a for loop to read sibling nodes, it is not working as intended.

pugi::xml_node variables = doc.child("plugin").child("interface").child("variables");

	for(pugi::xml_node variable = variables.first_child(); variable; variable.next_sibling())
	{
		std::cout 
			<< variable.attribute("name").value()
			<< std::endl;
	}
It is just printing the first child data in a continuous loop. 

Can you please help me in finding out what is the issue?

**Comment by zeux** [comment]
Additionally, if you have access to C++11 you can use ranged for to make the code shorter and more obviously correct:

```
for (pugi::xml_node variable: variables.children())
```

**Comment by HemanthMChakravarthy** [comment]
Thankyou, so much. It is working now.
