### ISSUE TITLE
Unicode interface issue with Shift-JIS

### ISSUE THREAD

**Issue by phibao37** [zeux/pugixml#139]
I'm opening an XML file (Japanese, Shift-JIS) like this:
```
<?xml version="1.0" encoding="Shift-JIS" ?>
<root>
  <FieldName>手書き英字１</FieldName>
  <FieldName>123456</FieldName>
</root>
```
This XML file contains two `FieldName` node, content of the first node is 6 characters (each with 2-byte), and the second node is still 6 characters (each with 1-byte)
(This is the [compressed file](https://github.com/phibao37/store/releases/download/v1.0/Sample.zip) if needed)

This is the code to open XML:
```
#include "pugixml.hpp"
#include <string.h>
#include <iostream>
using namespace std;

int main()
{
	cout << "Size of char = " << sizeof(char) << endl;
	cout << "Size of wchar_t = " << sizeof(wchar_t) << endl;

	pugi::xml_document doc;
	if (!doc.load_file("Sample.xml")) {
		cout << "Load failed" << endl;
		cin.get();
		return 1;
	}


#ifdef PUGIXML_WCHAR_MODE
	auto str1 = doc.select_node(L"/root/FieldName[1]").node().text().get();
	auto str2 = doc.select_node(L"/root/FieldName[2]").node().text().get();
	cout << "Length of field 1 in wchar_t: " << wcslen(str1) << endl;
	cout << "Length of field 2 in wchar_t: " << wcslen(str2) << endl;
#else
	auto str1 = doc.select_node("/root/FieldName[1]").node().text().get();
	auto str2 = doc.select_node("/root/FieldName[2]").node().text().get();
	cout << "Length of field 1 in byte: " << strlen(str1) << endl;
	cout << "Length of field 2 in byte: " << strlen(str2) << endl;
	cout << "Length of field 1 after convert to wchar_t: " << pugi::as_wide(str1).length() << endl;
#endif

	cin.get();
    return 0;
}
```
When run without `PUGIXML_WCHAR_MODE`, the output is:
```
Size of char = 1
Size of wchar_t = 2
Length of field 1 in byte: 12
Length of field 2 in byte: 6
Length of field 1 after convert to wchar_t: 3
```
and with `PUGIXML_WCHAR_MODE`:
```
Size of char = 1
Size of wchar_t = 2
Length of field 1 in wchar_t: 3
Length of field 2 in wchar_t: 6
```
Why the length of field 1 is `3` after convert to/or using WCHAR mode?
That is: `Size of wchar_t` = 2 * `Size of char`, so 12 byte should become to 6 character in WCHAR, right?
This is my expected value:
```
Length of field 1 after convert to wchar_t: 6
Length of field 1 in wchar_t: 6
```

So, what is the problem here?

**System information:**
- Windows 10 64bit, 
- Current language for non-Unicode program: Japanese
- PugiXML: 1.8.1 (master still the same)
- Compiler: Visual Studio 2017, build as x86

**Comment by zeux** [comment]
pugixml does not support Shift-JIS, it only supports Unicode variants. What seems to be going on is that in WCHAR mode, it assumes the input is UTF-8, and then converts from an (invalid) UTF-8 sequence thereby throwing away some characters.

For this to work you'll have to convert your document from Shift-JIS to UTF8 or UTF16 before passing it to pugixml; you can do this with MultiByteToWideChar, specifying the source codepage as 932.

**Comment by phibao37** [comment]
Thanks for your support, @zeux . I use `MultiByteToWideChar` and then can using pugixml with WCHAR mode.
