### ISSUE TITLE
crash on "xml_attribute::empty ()"

### ISSUE THREAD

**Issue by henrypp** [zeux/pugixml#143]
```xml
...
<item attr1="val" attr2="" />
...
```
```c++
...
if (!item.attribute (L"attr2").is_empty ()) // crash goes here
...
```
```c++
pugi::parse_default, pugi::encoding_auto
```
```c++
#define PUGIXML_COMPACT
#define PUGIXML_NO_STL
```

pugixml 1.6/1.8

**Comment by zeux** [comment]
pugixml does not have an `is_empty` function; is this something you have added?

Do you also define PUGIXML_WCHAR_MODE?

**Comment by henrypp** [comment]
sorry, just "::empty ()" method, wchar defined.

**Comment by zeux** [comment]
Does the crash happen without PUGIXML_COMPACT?
Can you include the full callstack of the crash?
If possible, can you attach the full XML file? The XML fragment alone doesn't seem to trigger any issues.

**Comment by henrypp** [comment]
with PUGIXML_COMPACT
```xml
<?xml version="1.0"?>
<root>
<item attr1="val" attr2="" />
</root>
```
pugi::xml_document doc;
pugi::xml_parse_result result = doc.load_file (L"example.xml", pugi::parse_default, pugi::encoding_auto);
pugi::xml_node root = doc.child (L"root");

if(root)
{
for (pugi::xml_node item = root.child (L"item"); item; item = item.next_sibling (L"item"))
{
if (!item.attribute (L"attr2").empty ()) // crash
{
//todo
}
}
}

**Comment by zeux** [comment]
This code does not result in a crash on the compilers I'm testing on (MSVC, gcc, clang on x86 / x64). What compiler are you using, what are the compilation flags, and what is the platform this code executes on?

Also it's my understanding that the crash is inside the `attribute` function, not `empty` function - is this correct?

**Comment by henrypp** [comment]
my misstake. crashing not on checking attribute, but get is value.

```C++
if (!item.attribute (L"attr2").empty ()) // not here crash
{
     // but condition is true, and as you see (above), attribute has empty value, no text.

     item.attribute (L"attr2").as_string (); // CRASH!!
     item.attribute (L"attr2").value (); // CRASH!!
}
```

**Comment by zeux** [comment]
This does not crash for me either. Here's the program I'm using:

```
#include "pugixml.hpp"

int main()
{
pugi::xml_document doc;
pugi::xml_parse_result result = doc.load_file (L"example.xml", pugi::parse_default, pugi::encoding_auto);
pugi::xml_node root = doc.child (L"root");

if(root)
{
for (pugi::xml_node item = root.child (L"item"); item; item = item.next_sibling (L"item"))
{
if (!item.attribute (L"attr2").empty ())
{
	item.attribute (L"attr2").as_string ();

}
}
}
}
```

When built with -DPUGIXML_COMPACT -DPUGIXML_WCHAR_MODE -DPUGIXML_NO_STL this does not crash on any systems I have access to. Can you specify the compilation flags, compiler and platform you're testing on so that I can try to understand the issue better?

**Comment by henrypp** [comment]
/GS- /GL /W4 /Gy /Zc:wchar_t /Ox /Zc:inline /fp:precise /D "_UNICODE" /D "UNICODE" /errorReport:prompt /GF /WX /Zc:forScope /Gr /Oy /MT /EHsc /nologo /Os

w7-64

**Comment by zeux** [comment]
Here's the code that I am using to test this:
[issue-143.zip](https://github.com/zeux/pugixml/files/921283/issue-143.zip)

When I build it and run it using Visual Studio 2012, I get this output:

pointer: 00976734, length: 0

Which is correct.

**Comment by henrypp** [comment]
Thank you for answer and help.
I found where it crashed, not pugixml.
