### ISSUE TITLE
VS 2015 NuGet Package Static Multithreaded

### ISSUE THREAD

**Issue by steji113** [zeux/pugixml#148]
The VS 2013 library was compiled with static /MT linkage whereas the newer VS 2015 library was compiled with dynamic /MD linkage in the NuGet package.

When upgrading our project to the VS 2015 C++ compiler, our projects that depend on the pugixml NuGet package were no longer able to link due to this change. Was this intended? And is there an option to change it or introduce support for static linking again?

MS doc about linkage: https://msdn.microsoft.com/en-us/library/2kzt1wy3.aspx

**Comment by zeux** [comment]
I believe that the 2015 libraries were just built with the defaults provided with VS2015 (which suggest a dynamically linked library). What really should happen I think is that NuGet package should include both dynamically linked and statically linked variants, but I'll need to check if this is supported.

**Comment by zeux** [comment]
Yeah, okay, it should be possible to include both using `dynamic` / `static` pivots. I'll take a look at doing this after merging VS 2017 NuGet PR.

**Comment by steji113** [comment]
Awesome, glad to hear! Would you happen to have a link to some documentation or reference on implementing this? There are a few other projects I would like to be able to contribute similar changes to. Also, I would be happy to take a stab at the VS 2015 version if you would like to get a PR ready.

Thanks!

**Comment by zeux** [comment]
Hmm the only issue is that there's this https://github.com/zeux/pugixml/pull/109... This might require more research.

**Comment by zeux** [comment]
(that is, I'm not sure if #109 would also be fixed if both static & dynamic options were available - I don't think we figured out in the end whether dynamic/static is about static/dynamic library or about static/dynamic linking for runtime)

**Comment by steji113** [comment]
Ah yes, I remember this now. Hmm. My interpretation of the coapp docs is that it means the application linkage rather than the runtime. I will try to do some more research as well, perhaps in some other libraries.

**Comment by zeux** [comment]
This might not be possible with CoApp, according to
https://github.com/coapp/coapp.powershell/issues/70
https://github.com/coapp/coapp.powershell/issues/94

It would be interesting to know how other native NuGet packages deal with this problem.

**Comment by steji113** [comment]
I think what I have seen is that native package authors typically just release multiple nuget packages and indicate to the user via the package name, tags and description. It is kind of ugly, but does the job.

So you could do something like pugixml-mt, pugixml-md, etc.

Examples of people creating their own form of "pivots": 
https://www.nuget.org/profiles/sergey.shandar?page=13
https://www.nuget.org/packages/boost_1.61.0_vc140_mt/

**Comment by igagis** [comment]
Personally, I don't see a reason in dynamic linkage on Windows, since those dll's are anyway meant to be distributed with every piece of software using them, so why not just link statically? I always use static linking on Windows. Linux is another story, of course.

**Comment by zeux** [comment]
I try to use static linking on Windows whenever I can myself, however there's two important caveats:

1) Code that passes STL objects between DLL boundaries might need a DLL runtime to use the same allocation functions.
2) The default in VS is DLL runtime, so it's somewhat more convenient to have NuGet images using /MD so that pugixml is usable out of the box with new projects.

Of course VS 2015 DLL runtime is much less convenient to distribute compared to earlier versions (it's like 40 DLLs) which doesn't make this choice easy...

**Comment by zeux** [comment]
I tried to get both packages built out of the same .autopkg file, and while I succeeded in that I have two packages, I can't get one of them to link files properly :-/ There's some intermediate progress in nuget branch, I'll wrestle with this a bit more... If this doesn't work out I'll just have to clone the .autopkg file I guess.

**Comment by steji113** [comment]
Thanks for the update! Let me know if you need any assistance testing anything out. I would be happy to try the static MT package.

**Comment by zeux** [comment]
Here's a test package for you:
https://ci.appveyor.com/api/buildjobs/n2jnbxr9u72ghbw9/artifacts/scripts/pugixml.1.8.0-appveyor.nupkg

This package contains both builds of the library (for dynamic & static CRT); you can select the right one in Project Settings -> Referenced Packages -> pugixml -> Linkage. The default is dynamic, but you can override it to be static (I will be changing the display names of these values to more clearly indicate this).

The package *should* have working builds for VS2013, VS2015 and VS2017, but I was only able to test VS2017.

**Comment by steji113** [comment]
That worked beautifully on VS 2015 following your directions to choose static linkage. Is this something that can be published to NuGet in the near future? Thanks!

**Comment by zeux** [comment]
I've uploaded the package built from 1.8 sources with these changes as pugixml 1.8.2 (and verified it works as expected on VS2017).

**Comment by steji113** [comment]
That did the trick. Thank you so much for your hard work on this.
