### ISSUE TITLE
Any way to select javascript code by XPath?

### ISSUE THREAD

**Issue by playgithub** [zeux/pugixml#152]
After tidied, the HTML is as below:
```
<div id="123">
    <script type="text/javascript">
    //<![CDATA[
    a = "Hello"
    //]]>
    </script>
</div>
```
Any way to extract the code `a = "Hello"` by XPath?

**Comment by zeux** [comment]
You should be able to extract all nodes using an expression like this one:

    //script[@type="text/javascript"]/text()

(this will select PCDATA or CDATA node)

**Comment by playgithub** [comment]
It works for this xml:
```
<div id="123">
    <script type="text/javascript">
    <![CDATA[
    a = "Hello"
    ]]>
    </script>
</div>
```
But not for
```
<div id="123">
    <script type="text/javascript">
    //<![CDATA[
    a = "Hello"
    //]]>
    </script>
</div>
```
The problem is that libHtmlTidy (http://www.html-tidy.org/) generated the latter one, any way to solve the problem?

**Comment by johanjohan** [comment]
quick intermezzo: @playgithub: testing on thousands of html files, i found libHtmlTidy to be insufficiently robust. After trying many many ways of converting html to xhtml/xml I am currently using xmllint with better results (xmllint -html -xmlout ...).

**Comment by playgithub** [comment]
Thanks in advance. I'll try it now.

**Comment by playgithub** [comment]
However, xmllint is part of libxml2, libxml2 depends on iconv, which is not friendly  with windows, and libiconv is under license LGPL, not so free.
I only need to tidy several kind of html, libTidyHtml is ok.
This is the only problem now, no way the problem?
BTW, with **HtmlAgilityPack** in C#, it just extract the whole block as:
```
//<![CDATA[
    a = "Hello"
//]]>
```
I think it simple and useful, for the small whole block, there are some ways to deal with it like:
1. string find
2. regex

**Comment by playgithub** [comment]
select `//script[@type='text/javascript']/text()` on
```
<div id="123">
    <script type="text/javascript">
    //<![CDATA[
    a = "Hello"
    //]]>
    </script>
</div>
```
The returned node type is `node_pcdata` not `node_cdata`

**Comment by zeux** [comment]
@playgithub Well, `//` is not a comment in XML, so your <script> node has two children: node_pcdata with contents `//` and node_cdata with contents `a = "Hello"\n//`. You can use `//script/[@type='text/javascript']` and just find the CDATA child, if any, of the result, or you can do something like this:

    //script[@type='text/javascript']/text()[last()]

(this will select the last child in each <script> node, skipping the first pcdata node)

Or you can do something like this:

	pugi::xpath_node_set ns = doc.select_nodes("//script[@type='text/javascript']");
	pugi::xpath_query concat(".");
	for (auto& n: ns) {
		std::string text = concat.evaluate_string(n);
	}

which will concatenate contents of all text nodes inside the <script> node with another XPath expression .

**Comment by zeux** [comment]
And I guess one other approach would be

	pugi::xpath_node_set ns = doc.select_nodes("//script[@type='text/javascript']");

	for (auto& n: ns)
	{
		std::stringstream ss;
		for (pugi::xml_node child: n.node().children())
			child.print(ss);

		std::string text = ss.str();
	}

Which will result in this string:

    //<![CDATA[
    a = "Hello"
    //]]>

**Comment by playgithub** [comment]
It works, thanks.
