### ISSUE TITLE
Maybe add a way to convert a xml_document out of a xpath_node_set

### ISSUE THREAD

**Issue by SFGrenade** [zeux/pugixml#153]
Could this be possible?
Or a way to directly attach xml_node s to to a xml_document.

**Comment by zeux** [comment]
Can you describe your usecase in more detail?

**Comment by SFGrenade** [comment]
nvm, just found a way, but it could be worthy adding it in the wiki.
i didn't find the xml_document::append_copy() at first.
I have to make a program for school, in which you can enter custom xpath and are able to save the result.

**Comment by mr-j0nes** [comment]
@SFGrenade Hi I think this would be useful to me. 
Would it be possible for you to add a an example of code on how you solved the issue ?
Thanks in advance...

**Comment by SFGrenade** [comment]
@mr-j0nes sure
```c++
pugi::xpath_node_set xpath_nodes = doc.select_nodes(xpath_str);
pugi::xml_document save_doc;
for (pugi::xpath_node child : xpath_nodes) {
    save_doc.append_copy(child.node());
}
save_doc.save_file(path);
```
where ```doc``` is a ```pugi::xml_document```, ```xpath_str``` and ```path``` is ```char[]```

**Comment by mr-j0nes** [comment]
Ok this really helped me. After some minutes you closed this issue I opened a new one asking a very similar question.
Thanks a lot.
