### ISSUE TITLE
element_by_path + index

### ISSUE THREAD

**Issue by mr-j0nes** [zeux/pugixml#155]
We have the excellent feature of first_element_by_path().
It would be good to have something like element_by_path() where we can specify indexes, E.g.: `../../foo[2]/./bar[0]`

**Comment by zeux** [comment]
first_element_by_path is a simplified XPath-like selector syntax; note that there's a full XPath engine available as well via select_node()/select_nodes(). I believe your specific query should work as is after adjusting for 1-based indexing, e.g.

```
pugi::xml_node bar = node.select_node("../../foo[3]/./bar[1]").node();
```

**Comment by mr-j0nes** [comment]
Ah excellent, long time I don't use the xpath syntax, I had the impression it was more heavy-weighted (complex)
Thanks for the answer I'll give it a try..
