### ISSUE TITLE
Enhance autodetection of the encoding

### ISSUE THREAD

**Issue by Lysander** [zeux/pugixml#158]
It would be great, if you would enhance your [encoding detection](https://pugixml.org/docs/manual.html#loading.encoding) in order to *evaluate* a given [``encoding``-Attribute](https://www.w3.org/TR/REC-xml/#NT-EncodingDecl) in the XML-declaration. This is also described [here](https://www.w3.org/TR/REC-xml/#sec-guessing).

So for example consider this document:

    <?xml version="1.0" encoding="iso-8859-1" ?>
    <root/>

Right now I have to configure your parser like this:

    xml_document doc;
    doc.load_file("foo.xml", parse_default, encoding_latin1);

This is imho cumbersome *and* less flexible, as you have to *know* the encoding within the code.
So it would be better, if *pugi* would evaluate the ``encoding`` attribute, in order to simplify the loading:

    doc.load_file("foo.xml");

On top this would be less error prone, as the XML-Document allready defines the encoding. If you configure your ``doc_load`` call with a *wrong* encoding, you get a corrupted content at best!

**Comment by zeux** [comment]
This is already how pugixml works since v1.8:

> Added auto-detection support for Latin-1 (ISO-8859-1) encoding during parsing

Are you using an earlier version?

**Comment by Lysander** [comment]
> Are you using an earlier version?

Quite sure that not!

I will check this tomorrow! But I think we got a falsy result, if we haven't set the encoding explcitly!


Btw: You should probably update the [documentation](https://pugixml.org/docs/manual.html#loading.encoding) - it doesn't say anything about the usage of the ``encoding`` attribute:

> Otherwise encoding is assumed to be UTF-8.

**Comment by zeux** [comment]
FWIW this code prints "No error 9" on your XML (9 = encoding_latin1):

```
	pugi::xml_parse_result res = doc.load_file("enc.xml");
	printf("%s %d\n", res.description(), res.encoding);
```

There is indeed an issue with documentation, I'll fix it to mention new behavior.

**Comment by Lysander** [comment]
Oops... I forgot about the fix of the codumentation - so reopened ;-)

**Comment by zeux** [comment]
Sorry, I'm not quite sure I understand your question. There is no version 8.1. If you are referring to 1.8.1 then this is just a re-packaging of 1.8 - there are no source changes. latin1 encoding autodetection is new as of 1.8 (1.7 doesn't have it, 1.8 does).
