### ISSUE TITLE
Possible problem with pugixml::xml_document::load_file + non+ASCII filenames + windows

### ISSUE THREAD

**Issue by LebedevRI** [zeux/pugixml#159]
Hi. This is pugixml 1.8 + mingw 64 bit
When we do
```
  xml_document doc;
  xml_parse_result result = doc.load_file(docname);
```
where `docname` is some filename that was not specially previously converted to windows wide characters (so i guess it's utf8?), the `load_file()` fails.
Are we supposed to manually convert to wide-character first?

**Comment by zeux** [comment]
Where do you get `docname` path from? That would determine whether it's UTF-8 or not.

If it is then this is sort of a duplicate of #45 - the current workaround is to use `doc.load_file(pugi::as_wide(docname).c_str())`. `load_file` uses `fopen` with the given path as is (which can be good or bad depending on how you look at it...)

**Comment by LebedevRI** [comment]
Ok, i'm being told that the workaround works.
