### ISSUE TITLE
[Question] Suppose i want to add more xpath 2.0 functions, how would i start?

### ISSUE THREAD

**Issue by tuananh** [zeux/pugixml#161]
Suppose i want to add more xpath 2.0 functions, how would i start?

Pointers are much appreciated.

Thank you.

**Comment by zeux** [comment]
To add a function to XPath engine, you have to:

1. Add ast_func_<functionname> to ast_type_t enum; if the function is overloaded, add multiple enums similar to other cases
2. Change `xpath_parser::parse_function` to emit the AST node with your newly added enum type if name is equal to your function name and argument count is what you'd expect. Make sure to specify the correct return type as well (`xpath_type_number`, etc.)
3. If some function arguments have to be node sets, you need to check that in `parse_function` similarly to "name" and some other cases - this is to avoid a runtime error during evaluation
4. Depending on the return type of your function, add the implementation to `eval_number`/`eval_string`/`eval_boolean`/`eval_node_set` methods of `xpath_ast_node` class.

**Comment by tuananh** [comment]
Thank you @zeux . Lemme digest these.
