### ISSUE TITLE
as_float() doesn't take the default value

### ISSUE THREAD

**Issue by ilya1725** [zeux/pugixml#163]
I've tried passing the default values (not 0) to as_float() method described [here](https://pugixml.org/docs/manual.html#access.attrdata). It doesn't seem to take it. The method still returns 0 when it can't convert the XML data.

**Comment by zeux** [comment]
Just to make sure, are you referring to the case where the attribute is present, but contains values that do not represent a valid floating point number?

**Comment by ilya1725** [comment]
Yes

**Comment by zeux** [comment]
So in general this is currently working as documented (documentation says that conversion issues result in unspecified values). In terms of implementation, this is currently tracked as #15 (for integer parsing there's now custom validation code, but the behavior hasn't been changed to use the default value; for floating point parsing currently pugixml relies on strtod, that has some issues wrt error reporting).

Thinking about this, I realized that in one specific case the current behavior can be more surprising than usual, which is when the contents is empty. I could change the code to check that case specifically, although I'm not sure if in your case the value is empty as opposed to a non-empty string that just happens to not be a number.

**Comment by ilya1725** [comment]
So I've tried two tests:
This is the data:
`<index3 x='10' y='W178.314'/>`
this is the code:
`y.as_float(-12345.6) << ":'" << y.value()`
the output:
`0:'W178.314`

With empty data:
`<index3 x='10' y=''/>`
output:
`0:'`

**Comment by zeux** [comment]
Yeah, my question is whether fixing this for *just* empty data is interesting to you. The default values were originally intended for use when attributes just don't exist, i.e. `<index3 x='10' />` in your example, which is why the current implementation only checks for that - but full validation is more complicated (#15 has some details)

**Comment by ilya1725** [comment]
It didn't work for the invalid float either. 
To be honest I don't really care, as long as the API does what the documentation says it should. It was my **mis**understanding of the API. The documentation says "_If attribute handle is null def argument is returned (which is 0 by default)._ " So the `def` technically only applicable to `null` handle and not the data itself.
It is up to you, this issue can be closed.

**Comment by zeux** [comment]
Ok, for now I will just treat this as part of #15 then.
