### ISSUE TITLE
Add Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [zeux/pugixml#165]
Hello,

Conan is modern package mamager for C++. There are a lot of libraries which have packages. Can you please add pugixml package to Conan?

Thank you.

**Comment by zeux** [comment]
Generally I try not to maintain pugixml packages - there are too many package repositories and too little time. (NuGet is the only exception atm).

I don't know anything about Conan but if you or anyone else can add a Conan package for pugixml that would be appreciated

**Comment by Croydon** [comment]
We have one out of self-need https://github.com/inexorgame/conan-pugixml 😄

**Comment by AlexandrePTJ** [comment]
Hi,

Maybe a bit redundant but I created a recipe that I will propose to @bincrafters.
Hope it will help.

**Comment by AlexandrePTJ** [comment]
Recipe have been adopted here: https://github.com/bincrafters/conan-pugixml

**Comment by zeux** [comment]
Thanks! It looks like there are several packages now, so I'll close this.
