### ISSUE TITLE
[question] xpath query with namespace xmlns

### ISSUE THREAD

**Issue by tuananh** [zeux/pugixml#168]
`
<nodes xmlns="http://mynamespace">
    <node>1</node>
</nodes>
`

using this xpath query `//nodes[@xmlns="http://mynamespace"]/node` with the above xml doesn't return any node.

any idea what im doing wrong here? many thanks.

**Comment by zeux** [comment]
Off the top of my head, XPath standard says that xmlns attributes never belong to attribute:: axis, so @xmlns will never find the node. I believe you should use something along the lines of

    //nodes[namespace-uri() = "http://mynamespace"]/node

instead.

**Comment by zeux** [comment]
Yeah specifically XPath 5.3 Attribute Nodes says

> There are no attribute nodes corresponding to attributes that declare namespaces (see [XML Names]).

In XPath 1.0 you may also be able to use `namespace::` axis to query namespace data; this is not supported by pugixml due to significant implementation challenges, and also is apparently deprecated in XPath 2.0.

**Comment by tuananh** [comment]
Thanks a lot.
