### ISSUE TITLE
Is any way to add text to node in CDATA format?

### ISSUE THREAD

**Issue by lexxmark** [zeux/pugixml#169]

**Comment by zeux** [comment]
I’m not sure I understand what you need exactly - do you mean appending more content to an existing CDATA node, or adding CDATA content as a child of an element/tag node?

**Comment by lexxmark** [comment]
For example I have an empty node and want to add a text block to it in CDATA format.
How to do that?

auto node = root.append_child("node");
node.text().set("Some text in CDATA format"); // ???

**Comment by zeux** [comment]
This should work:

```
node.append_child(node_cdata).set_value("Some text in CDATA format");
```

**Comment by lexxmark** [comment]
OK, thanks. I will make a shortcut for it.

**Comment by vineelkumar1990** [comment]
https://github.com/zeux/pugixml/issues/358
