### ISSUE TITLE
More move semantics

### ISSUE THREAD

**Issue by dpacbach** [zeux/pugixml#171]
Noticed that pugixml is generally move-aware, but wondering why there is not a move constructor/assignment operator for xml_document?  Can we add move semantics to any classes that don't have them?

**Comment by zeux** [comment]
pugixml supports document moves in master (as of a week ago: #170, 7c6d0010b30111dbfb8e523634e7b63328992106). I believe this covers all classes that might need move semantics, but feel free to reopen this if you find move support lacking.
