### ISSUE TITLE
remove xml node_declaration

### ISSUE THREAD

**Issue by uurynk** [zeux/pugixml#172]
when i genereted xml i got this.
```
<?xml version="1.0"?>
<SomeDto>
          <ID>1</ID>
          <Name>Ali Duru</Name>
</SomeDto>
```

But iwant my xml like this:

```
<SomeDto>
          <ID>1</ID>
          <Name>Ali Duru</Name>
</SomeDto>
```

Is there any way to remove declaration on the top?

**Comment by zeux** [comment]
When saving the document, you should pass format flags `format_default | format_no_declaration`: https://pugixml.org/docs/manual.html#format_no_declaration

**Comment by uurynk** [comment]
my code:
`_doc.save_file("test.xml", "\t", pugi::format_default | pugi::format_no_declaration);`

and xml file:

```
<?xml?>
<SomeDto>
	<ID>1</ID>
	<Name>anakara</Name>
	<Deleted>false</Deleted>
</SomeDto>
```

what am i missing?

**Comment by zeux** [comment]
Are you saying that with the code from the last comment you get the resulting XML from the last comment? `<?xml?>` looks like declaration that has either been parsed from the file (which may mean that you're loading the file with `pugi::parse_declaration`?), or - more likely? - like declaration that was explicitly added with the code, e.g. `doc.prepend_child(pugi::node_declaration)`. The flag `format_no_declaration` only suppresses output of default declaration in case the source document doesn't have it.

**Comment by uurynk** [comment]
Thank you for support!..
