### ISSUE TITLE
How to assemble a document from xpath(s)

### ISSUE THREAD

**Issue by bangusi** [zeux/pugixml#174]
Say I have these xpaths ( they are not in a valid xml document, they are jsut a listing of string lines presumably extracted from an xml document
that I have no access to.

```
/country/city/street_name
/country/city/street_name/house_number
/country/climate/rainfall
/country/climate/temperature
```

Is it possible to assemble an xml document from these strings and how.

The question #153  seems close to what I have in mind but if understand the answer
correctly, it asumes the source of the xpath is an existing xml document hence the call

```
auto nodes = source_doc.select_nodes(xpaths);
for (pugi::xpath_node child : xpath_nodes) 
{
  target_doc.append_copy(child.node());
}
```

**Comment by zeux** [comment]
I'm not sure I understand the question. `/country/city/street_name` by itself is not useful - you need an XML document to extract data from using this query, no?

**Comment by bangusi** [comment]
> you need an XML document to extract data from using this query, no?
Ideally, yes. But suppose the xpath is all you have and have no access to the original xml document. May be this is not possible, Perhaps construct a minimal xml on the fly? I am not sure.

**Comment by zeux** [comment]
I'm really unsure what the problem that you're trying to solve is. If we're talking about actual XPath queries, then they can be pretty complex and it's hard to establish a document that matches. Here's an example of a relatively full featured query:

    (//location[string(info/references/reference[1]/url)=string(current-url)]/info/references/reference[1])[1]

Now, maybe you're talking about slash-delimited paths and assuming this is XPath? If this is at all related to #173 then maybe what you want is given a collection of string-delimited paths to create a document that contains all of them? If so, pugixml doesn't provide any readily available functionality to do that but it should not be too hard to split each path using / as a delimiter and find/create the necessary nodes one by one.

**Comment by bangusi** [comment]
This is indeed related to #173 which you already provided a solution that works perfectly. The original document is actually xpaths which I converted to nodes in a std::map. I thought there might be a more direct way way to go from those xpaths to an xml document. The solution provided in #173 works fine so I will close this.
