### ISSUE TITLE
add xml node property  row and column  in document file

### ISSUE THREAD

**Issue by xfcanyue** [zeux/pugixml#178]
sometimes, i need to know a xml_node's location in the document. 

it's useful to edit xml from another program interface.  when edited, dynamically update the document, not reload the document.

thanks very much,  i like pugixml.

**Comment by zeux** [comment]
Currently the parser doesn't track row/column information, and there's also no space in the node to store this (making nodes larger would penalize workloads that don't need this info).

You do have `xml_node::offset_debug()`; it is essentially a byte position of the node in the file, which could be used to recover the row/column offset manually (of course that's a bit cumbersome).

I do have a plan to introduce a separate, optional table that could be used to store & query this data; this is tracked in #12.

**Comment by xfcanyue** [comment]
did you have finished this plan ?
