### ISSUE TITLE
how to get string value from a child

### ISSUE THREAD

**Issue by uurynk** [zeux/pugixml#180]
in xml child i'm using `child().text().get()` method but i get only the first word of the string.

For example my xml is:

`<root><Name>Ugur Yanik</Name></root>`

and i call this method:

```
stringstream nameValue;
nameValue << node.child("Name").text().get();
std::string name >> nameValue;
```
name would be "Ugur".

How can i get string value in a child?

I also tried:
```
nameValue << node.child_value("Name").text().get();
std::string name >> nameValue;
```

**Comment by zeux** [comment]
operator>> for stringstream by default only reads up to the first whitespace, you need to do `nameValue >> std::noskipws` to fix this. But also just don't use stringstream in the first place?

**Comment by uurynk** [comment]
I'm very beginneer to cpp and i ve found and sample on the some website. stringstream was using there. But is there a better way (the correct one) to get string value from child? Thanks.

**Comment by zeux** [comment]
Just assign the value directly:

    std::string name = node.child_value("Name");;

**Comment by uurynk** [comment]
`node.child_value` resolved my problem. Thank you sir.
