### ISSUE TITLE
Compiler warnings when PUGIXML_NO_EXCEPTIONS defined

### ISSUE THREAD

**Issue by DavidA2014** [zeux/pugixml#182]
These compiler warnings were reported by TI's C++ compiler when PUGIXML_NO_EXCEPTIONS is defined:

    "pugixml.cpp", line 253: warning #179-D: function "pugi::impl::<unnamed>::auto_deleter<T>::release [with T=pugi::impl::<unnamed>::xml_stream_chunk<wchar_t>]" was declared but never referenced
    "pugixml.cpp", line 253: warning #179-D: function "pugi::impl::<unnamed>::auto_deleter<T>::release [with T=pugi::impl::<unnamed>::xml_stream_chunk<char>]" was declared but never referenced
    "pugixml.cpp", line 253: warning #179-D: function "pugi::impl::<unnamed>::auto_deleter<T>::release [with T=std::FILE]" was declared but never referenced
    "pugixml.cpp", line 1529: warning #179-D: function "pugi::impl::<unnamed>::utf16_writer::any" was declared but never referenced
    "pugixml.cpp", line 1539: warning #179-D: function "pugi::impl::<unnamed>::utf32_counter::low" was declared but never referenced
    "pugixml.cpp", line 1544: warning #179-D: function "pugi::impl::<unnamed>::utf32_counter::high" was declared but never referenced
    "pugixml.cpp", line 1568: warning #179-D: function "pugi::impl::<unnamed>::utf32_writer::any" was declared but never referenced

**Comment by zeux** [comment]
Looking into this, I don't think it's feasible to fix these issues at the source level, short of disabling this warning in the file scope with a pragma. These warnings complain that certain instantiations of a templated class have certain members unused, which is true but fixing that requires restructuring code, *and* this is likely to crop up again in the future. This to me seems like a problem in the compiler - in fact, other C++ compilers won't even instantiate the unused methods, they may not compile.

The only way for me to fix these thus would be to disable it in file scope, similar to other warning pragmas you can see near the top of the file. Do you know if this is possible in this compiler and how to do this? (TI seems to provide their gcc-based compiler for free download, but this doesn't look like gcc to me).

**Comment by DavidA2014** [comment]
Thanks for your reply.  The TI DSP compiler that I am using is not gcc-based, but it does appear to have a means of suppressing warning messages on a per-file basis:

#pragma diag_suppress 179

[https://e2e.ti.com/support/development_tools/compiler/f/343/t/270420](url)

So I can make that change in my local copy.

**Comment by zeux** [comment]
Great - this helps. Does something like this prevent this warning from happening? If so, I can make this change.

```
diff --git a/src/pugixml.cpp b/src/pugixml.cpp
index b06eacb..a6930a1 100644
--- a/src/pugixml.cpp
+++ b/src/pugixml.cpp
@@ -76,6 +76,10 @@
 #      pragma diag_suppress=237 // controlling expression is constant
 #endif

+#ifdef __TI_COMPILER_VERSION__
+#      pragma diag_suppress 179 // function was declared but never referenced
+#endif
+
 // Inlining controls
 #if defined(_MSC_VER) && _MSC_VER >= 1300
 #      define PUGI__NO_INLINE __declspec(noinline)
```

**Comment by DavidA2014** [comment]
Yes, that change disables the warnings. Thank you.
