### ISSUE TITLE
How to append a node to a new document

### ISSUE THREAD

**Issue by boopr** [zeux/pugixml#186]
Hello,

I have methods which give me the entire XML tree of a class and I would like to save it in a new document. This is the method definition: 
```cpp
pugi::xml_node exportXML() const;
```
And this it the function I'm working on:
```cpp
template<class T> bool Saver::save(const T &object, const QString &path)
{
    pugi::xml_document doc;
    doc.append_move(object.exportXML());
    return doc.save_file(path.toStdString().c_str());
}
```
But I can't find anything to append a `xml_node` as a root element of a `xml_document`. Am I missing something?

Thanks for your answers. 😄

**Comment by zeux** [comment]
append_move is not suitable in these cases - it can only move nodes within a document, not between documents. This restriction is there because document is responsible for memory management of node's data, and nodes are allocated in bulk.

I must admit I'm not sure I understand the structure of this code precisely. I feel like in this case the better solution is to expose the document from exportXML function instead of just the node, something like

    pugi::xml_document exportXML() const;

(this would require C++11 and move constructor support from master)

or maybe

    std::unique_ptr<pugi::xml_document> exportXML() const;

(this would require C++11 but would work with any pugixml version)

or some equivalent of this. If this doesn't work, can you explain a bit more how exportXML function works?

**Comment by boopr** [comment]
Yes of course. This is the `Part::exportXML()` method:

```cpp
pugi::xml_node Part::exportXML() const
{
    pugi::xml_document doc;
    pugi::xml_node part = doc.append_child("part");

    // Attributes
    QMap<QString, QString>::const_iterator it = m_attributes.constBegin();

    while (it != m_attributes.constEnd()) {
        pugi::xml_node attribute = part.append_child("attribute");
        attribute.append_attribute("name") = it.key().toStdString().c_str();
        attribute.append_child(pugi::node_pcdata).set_value(it.value().toStdString().c_str());

        ++it;
    }

    // Position
    pugi::xml_node position = part.append_child("position");
    position.append_attribute("x") = m_position.x();
    position.append_attribute("y") = m_position.y();
    position.append_attribute("z") = m_position.z();

    if (m_parts.size() == 0) {
        // Mass
        pugi::xml_node mass = part.append_child("mass");
        mass.append_child("value").append_child(pugi::node_pcdata).set_value(QString::number(m_mass).toStdString().c_str());
        mass.append_child("margin").append_child(pugi::node_pcdata).set_value(QString::number(m_massMargin).toStdString().c_str());
    } else {
        // Parts
        pugi::xml_node parts = part.append_child("parts");

        for (int i = 0; i < m_parts.size(); ++i) {
            parts.append_copy(m_parts[i].exportXML());
        }
    }

    return part;
}
```
`Part` is a node of a tree which can have other parts as children. The `exportXML()` method is used to get the XML tree of any node, so I don't think I can return a `pugi::xml_document`.

This is an XML tree returned by the method:
```xml
<?xml version="1.0"?>
<part>
  <attribute name="name">A</attribute>
  <position x="2" y="0" z="-1" />
  <parts>
    <part>
      <attribute name="name">B</attribute>
      <position x="5" y="0" z="0" />
      <parts>
        <part>
          <attribute name="name">C</attribute>
          <position x="2" y="0" z="-1" />
          <mass>
            <value>0.33</value>
            <margin>0</margin>
          </mass>
        </part>
        <part>
          <attribute name="name">D</attribute>
          <position x="2" y="0" z="-1" />
          <mass>
            <value>0.33</value>
            <margin>0</margin>
          </mass>
        </part>
      </parts>
    </part>
    <part>
      <attribute name="name">E</attribute>
      <position x="2" y="0" z="-1" />
      <mass>
        <value>0.33</value>
        <margin>0</margin>
      </mass>
    </part>
  </parts>
</part>

```

I hope you'll understand better now. Thanks for your help!

**Comment by boopr** [comment]
But I'll not be able to do this then if I return a document :

```cpp
pugi::xml_node parts = part.append_child("parts");
for (int i = 0; i < m_parts.size(); ++i) {
    parts.append_copy(m_parts[i].exportXML());
}
```
Because to append to a node I need nodes. 😕

**Comment by brandl-muc** [comment]
1) Never use `std::move()` to move a temporary out of a function as it impedes NRVO. Simply use `return widget;` and the compiler will elide the move. (see [this SO answer](https://stackoverflow.com/a/4986802/1969455))
Things are different for class member variables, these need the `std::move`.

2) In your example, the returned document will "live" through the end of the call. So you can easily get the node and pass it on in this single line:
```
pugi::xml_node parts = part.append_child("parts");
for (int i = 0; i < m_parts.size(); ++i) {
    parts.append_copy(m_parts[i].exportXML().document_element());
}
```

Or store the document and then get the node:
```
pugi::xml_node parts = part.append_child("parts");
for (int i = 0; i < m_parts.size(); ++i) {
    auto const document = m_parts[i].exportXML();
    parts.append_copy(document.document_element());
}
```

**Comment by zeux** [comment]
@boopr Ah ok - I haven't paid attention to the recursive call. You should not in general create xml_document objects unless you have to - they are much more heavyweight compared to nodes.

In this case I'd recommend changing the signature to `void exportXML(xml_node target);` and using `m_parts[i].exportXML(parts);` as a recursive call.

**Comment by boopr** [comment]
So I tried to return a `pugi::xml_document` from `Part::exportXML()`. I got this error with the return instruction:
```
'pugi::xml_document::xml_document(const pugi::xml_document&)' is private within this context
     return doc;
            ^~~
```
Do you know what is this about ?

> In this case I'd recommend changing the signature to void exportXML(xml_node target); and using m_parts[i].exportXML(parts); as a recursive call.

But if I don't return a document, how can I save the nodes in an other function ? 😄 

Thank you both for your help!

**Comment by zeux** [comment]
@boopr Here's what I'm suggesting:

```
void Part::exportXML(pugi::xml_node target) const
{
    pugi::xml_node part = target.append_child("part");

    // Attributes
    QMap<QString, QString>::const_iterator it = m_attributes.constBegin();

    while (it != m_attributes.constEnd()) {
        pugi::xml_node attribute = part.append_child("attribute");
        attribute.append_attribute("name") = it.key().toStdString().c_str();
        attribute.append_child(pugi::node_pcdata).set_value(it.value().toStdString().c_str());

        ++it;
    }

    // Position
    pugi::xml_node position = part.append_child("position");
    position.append_attribute("x") = m_position.x();
    position.append_attribute("y") = m_position.y();
    position.append_attribute("z") = m_position.z();

    if (m_parts.size() == 0) {
        // Mass
        pugi::xml_node mass = part.append_child("mass");
        mass.append_child("value").append_child(pugi::node_pcdata).set_value(QString::number(m_mass).toStdString().c_str());
        mass.append_child("margin").append_child(pugi::node_pcdata).set_value(QString::number(m_massMargin).toStdString().c_str());
    } else {
        // Parts
        pugi::xml_node parts = part.append_child("parts");

        for (int i = 0; i < m_parts.size(); ++i) {
            m_parts[i].exportXML(parts);
        }
    }
}

template<class T> bool Saver::save(const T &object, const QString &path)
{
    pugi::xml_document doc;
    object.exportXML(doc);
    return doc.save_file(path.toStdString().c_str());
}
```

**Comment by zeux** [comment]
(note that this results in one xml_document shared throughout the entire recursive process of filling the tree - this is the most efficient option)

I think `return doc;` didn't compile for you because you are either not using pugixml/master or not using a C++11 compiler - `return doc` relies on C++11 and on recently added document move support. In any case, in this case it's excessive to use that since it would result in many documents being created/destroyed for large trees.

**Comment by boopr** [comment]
I tried your solution and it worked like a charm! Thanks a lot, it looks very clean!
