### ISSUE TITLE
Different result when using load_file inside and outside a function

### ISSUE THREAD

**Issue by boopr** [zeux/pugixml#187]
Hello again,

I have a weird issue. Imagine this simple XML:
```xml
<?xml version="1.0"?>
<part>
  <attribute name="name">A</attribute>
  <parts>
    <part>
      <attribute name="name">B</attribute>
    </part>
    <part>
      <attribute name="name">C</attribute>
    </part>
  </parts>
</part>
```
If I do this:
```cpp
pugi::xml_document doc;
doc.load_file("test_pos.xml");

Part p(doc.first_child());

for (const Part &part : p.getParts()) {
    std::cout << "Name: " << part.getAttribute("name").toStdString() << std::endl;
}
```
No problem, everything works great, I have the following result:
```
Name: B
Name: C
```
But if I do it like this:
```cpp
pugi::xml_node open(const QString &path)
{
    pugi::xml_document doc;
    doc.load_file(path.toStdString().c_str());

    return doc.first_child();
}
// [...]
Part p(open("test_pos.xml"));

for (const Part &part : p.getParts()) {
    std::cout << "Name: " << part.getAttribute("name").toStdString() << std::endl;
}
```
Which I think it's the same, I have the following result:
```
Name: B
```
The output `Name: C` isn't here.. Can someone explain me the difference between the two codes ?

Thanks and have a great day! 😄

**Comment by brandl-muc** [comment]
`xml_document` is owning all the memory / data, `xml_node` is merely a kind of pointer into the data.
This means that in your second example you return a "dangling" node which you then access.

I would construct the `xml_document` in the outer scope and pass it into `open()` as non-const reference. Then you can safely return the node.

**Comment by boopr** [comment]
Okay thanks for the explaination!
