### ISSUE TITLE
Reading environment variables

### ISSUE THREAD

**Issue by mr-j0nes** [zeux/pugixml#192]
Hello there,

currently I use XML for storing an application configuration. One of the features I would like to support is using environment variables as part of the values. E.g.:
```
<cfg>
    <work_dir>${WORK}/blahblah</work_dir>
    <no_retries>${RETRIES}</no_retries>
</cfg>
```
When reading with pugixml I would like that environment variable to be already expanded. E.g.:
```
std::string work_dir(document_->first_element_by_path("/cfg/work_dir").text().as_string()); 
int no_retries(document_->first_element_by_path("/cfg/no_retries").text().as_int()); 
// <- /work/blahblah
// <- 5
```
Do you support any kind of callback to inject my code to do this ? If not, where do you suggest to add such logic (which part of your code)?

Thanks in advance..

**Comment by zeux** [comment]
You can not expand variables like this during parsing. I suggest doing a separate recursive traversal of the tree after pugixml parsed it, and doing this replacement outside of pugixml source code.

**Comment by mr-j0nes** [comment]
Thank you, I've just implemented it via a recursive traversal as you suggested.
