### ISSUE TITLE
how to deal with so serious memory leaks?

### ISSUE THREAD

**Issue by owey0312** [zeux/pugixml#196]
see my attachment
[memory_leaks.zip](https://github.com/zeux/pugixml/files/1919367/memory_leaks.zip)

**Comment by zeux** [comment]
These memory leaks are mostly coming from what looks like CString, which suggests to me that the code that uses pugixml & CString isn't doing something correctly. If you share code used to load the document and extract data from it I might be able to spot the issue.

**Comment by owey0312** [comment]
hi,
  i have checkd the leak, when i remove all pugixml codes,as well as lib, the leak still exists, so i think it's not pugixml who lead to this leak happen.
 but, i want to show an another error:
     when i remove all children of an node, i find nodes haven't been removed when i call saveFile interface after of this, codes show below:
      xml_object_range<xml_node_iterator>* pRange = &node->children();
	auto iter = pRange->begin();
	for (; iter != pRange->end(); iter++) {
		node->remove_child(*iter);
	}

**Comment by zeux** [comment]
I'm not sure how this even compiles. You should not be taking a pointer here, use this instead:

```
xml_object_range<xml_node_iterator> pRange = node->children();
auto iter = pRange.begin();
for (; iter != pRange.end(); iter++) {
node->remove_child(*iter);
}
```
