### ISSUE TITLE
CMake add option to setup POSTFIX

### ISSUE THREAD

**Issue by irov** [zeux/pugixml#198]
option(USE_POSTFIX "Setup postfix" ON)

if(CMAKE_CONFIGURATION_TYPES AND USE_POSTFIX)
	set_target_properties(pugixml PROPERTIES DEBUG_POSTFIX "_d" MINSIZEREL_POSTFIX "_m" RELWITHDEBINFO_POSTFIX "_r")
endif()

**Comment by zeux** [comment]
The suffixes are new as of #191; my understanding has been that normal CMake builds don't trigger this - I'm totally up for putting this behind an option (maybe it should be off by default?), but I'd like to make sure I understand what is the problem with having these postfixes - what is the setup where they are appended in error?

**Comment by irov** [comment]
The engines use pugixml as a dependency, and my main CMake has its own compilation settings, and POSTFIX options. Your setting overrides my settings

**Comment by zeux** [comment]
Alright; since this change is super recent and I wasn't sure if it would break somebody's workflow and it did, I'll move it behind an off-by-default configuration switch. Thanks for the feedback!
