### ISSUE TITLE
'pugixml.cpp' file not found with PUGIXML_HEADER_ONLY on Ubuntu

### ISSUE THREAD

**Issue by vadi2** [zeux/pugixml#200]
I'm including pugixml in a Ubuntu build - so the package is from the repositories - and doing the following:

```cpp
#include <pugixml.hpp>

// qmake.pro 
DEFINES += PUGIXML_HEADER_ONLY
```

The build errors out with the following however:

```
In file included from ../src/XMLexport.h:33:
/usr/include/pugixml.hpp:1408:11: fatal error: 'pugixml.cpp' file not found
#       include PUGIXML_SOURCE
                ^
/usr/include/pugixml.hpp:1407:25: note: expanded from macro 'PUGIXML_SOURCE'
#       define PUGIXML_SOURCE "pugixml.cpp"
                              ^~~~~~~~~~~~~
```

What's going wrong?

**Comment by zeux** [comment]
I suspect Ubuntu package doesn't include pugixml.cpp - it's commonplace in package distributions to separate header files from source files and only include header files and precompiled libraries into the package. I suspect this is what's happening, I'll need to look into how the package is built for Ubuntu to confirm.

**Comment by zeux** [comment]
I looked into this and it does seem like Ubuntu package (understandably) doesn't package pugixml.cpp at all. In general using custom defines might not work well with pre-packaged versions; I'd suggest either using default defines, or using a local copy of pugixml instead of a package.

**Comment by zeux** [comment]
Since I don't maintain pugixml packages and the packaging for Ubuntu seems appropriate (even though it doesn't support header-only builds, if you need them you should bundle pugixml with your app), I'm closing this.
