### ISSUE TITLE
Are ASCII control characters supported?

### ISSUE THREAD

**Issue by vadi2** [zeux/pugixml#203]
We've had issues with ASCII control characters such as the [line tab](https://codepoints.net/U+000B?lang=en) not being encoded properly by other XML writers - the encoding would simply stop when fed that character. We've [worked around it](https://github.com/Mudlet/Mudlet/pull/995/files) by increasing the range of the characters and that works.

Would pugixml require such treatment as well or does it handle encoding/decoding characters like U+000B fine?

**Comment by zeux** [comment]
```c++
#include "pugixml.hpp"
#include <iostream>

int main()
{
	pugi::xml_document doc;
	doc.append_child("test").append_attribute("attr").set_value("\x0B");
	doc.save(std::cout);
}
```

outputs

```
<?xml version="1.0"?>
<test attr="&#11;" />
```

**Comment by vadi2** [comment]
Awesome! Thanks!!
