### ISSUE TITLE
"set_value_convert" please up precision for float 

### ISSUE THREAD

**Issue by irov** [zeux/pugixml#204]
float f = 1.f / 8192.f;

    printf( "%.9g\n", f );
    printf( "%.10g\n", f );

0.000122070313
0.0001220703125

I propose to add a command which will represent the float with full accuracy of its representation
like printf( "%.126g\n",  FLT_MIN);

**Comment by zeux** [comment]
0.000122070313 and 0.0001220703125 represent the same float; pugixml uses printing precision that is adequate to support round-tripping; see https://randomascii.wordpress.com/2013/02/07/float-precision-revisited-nine-digit-float-portability/ for details.

If you want to print more digits, you're welcome to use set_value with a double argument, or convert your floating point value manually and use set_value with a string argument.
