### ISSUE TITLE
How to add a doctype after node declaration?

### ISSUE THREAD

**Issue by vadi2** [zeux/pugixml#205]
If I do the following:

```cpp
    auto decl = mExportDoc.prepend_child(pugi::node_declaration);
    decl.append_attribute("version") = "1.0";
    decl.append_attribute("encoding") = "UTF-8";

    mExportDoc.append_child(pugi::node_doctype).set_value("MudletPackage");
```

Both values go into the output, however, the doctype is before the declaration - which is incorrect.

I've played around with a combination of `append_child` and `prepend_child` but I can't get the right one together.

**Comment by zeux** [comment]
The following program:

```c++
#include "pugixml.hpp"

int main()
{
    pugi::xml_document mExportDoc;

    auto decl = mExportDoc.prepend_child(pugi::node_declaration);
    decl.append_attribute("version") = "1.0";
    decl.append_attribute("encoding") = "UTF-8";

    mExportDoc.append_child(pugi::node_doctype).set_value("MudletPackage");

    mExportDoc.append_child("root");

    mExportDoc.save_file("test.xml");
}
```

Outputs the following file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE MudletPackage>
<root />
```

Is that not what you were expecting? I'm not sure how you get doctype to go before the declaration other than appending the declaration after the doctype, or prepending doctype after the declaration.

**Comment by vadi2** [comment]
Thanks - I was adding the root node first, then the declaration and the doctype!
