### ISSUE TITLE
How can I have the output be indented without a space on empty nodes?

### ISSUE THREAD

**Issue by vadi2** [zeux/pugixml#206]
Following on from https://github.com/zeux/pugixml/pull/95, how can I have both my `<element/>` and eat some formatting too?

**Comment by zeux** [comment]
Unfortunately, this option is not available; when format_raw is not set, pugixml assumes you want a pretty printed output and assumes space for empty nodes looks nicer.

**Comment by vadi2** [comment]
Ah ok - I prefer it the non-Microsoft way, so an `format_no_empty_element_space` flag would be great.
