### ISSUE TITLE
Serializing pugi::xml_document in a different thread

### ISSUE THREAD

**Issue by vadi2** [zeux/pugixml#208]
This might be a dumb question - I'm accessing and serializing `pugi::xml_document` with `save()` from another thread and I'm getting a segfault in [pugixml.cpp](https://github.com/zeux/pugixml/blob/master/src/pugixml.cpp#L7158). What am I doing wrong?

I'm guessing the issue is that `save()` creates it's own objects when serialising - and that's effectively done on the original thread.

**Comment by zeux** [comment]
save does *not* create objects during serialization - serializing should be safe, assuming that other threads aren't modifying the document. I'd say that the most likely case is that the document is destroyed by another thread?

**Comment by vadi2** [comment]
That was the case, thanks for helping with such a newbie question! The problem really wasn't that intuitive.
