### ISSUE TITLE
Is there xml external entity vulnerability and how to prevent it?

### ISSUE THREAD

**Issue by hylepo** [zeux/pugixml#216]
I am wondering is there xml external entity vulnerability and how to prevent it? I can not find any thing related in the manual document, thanks.

**Comment by zeux** [comment]
pugixml doesn’t expand XML entities other than predefined ones (`&amp;` etc), so it isn’t vulnerable. In general, pugixml parsing is guaranteed to run in linear amount of time wrt input, linear amount of heap memory and constant amount of stack memory.
