### ISSUE TITLE
build fails on MSVC due to missing permissions

### ISSUE THREAD

**Issue by emmenlau** [zeux/pugixml#217]
I have a very strange build error on MSVC with pugixml 1.9. After a bit of debugging it turns out that the Windows zip archive has quite specific permissions. This seems to break cmake for me. The error is not very helpful and returns no helpful google hits:
```
CMake Error in CMakeLists.txt:
  cmListFileCache: error can not open file.
```
When I change the permissions after extraction, everything works fine. Its possible that my `zip` utility from Cygwin is to blame and that other zip tools like WinZip or 7zip ignore the permissions. But I get the same permissions when I extract the archive on Linux (note the missing access permissions for CMakeLists.txt):
```
emmenlau(chili/ubuntu-16_04) /tmp/pugixml-1.9> ls -l
total 112
----------  1 emmenlau emmenlau  3076 Apr  4 07:53 CMakeLists.txt
drwxrwx---  2 emmenlau emmenlau  4096 Jul 21 23:54 contrib
drwxrwx---  4 emmenlau emmenlau  4096 Jul 21 23:55 docs
----------  1 emmenlau emmenlau  2190 Apr  4 07:53 readme.txt
drwxrwx---  4 emmenlau emmenlau  4096 Jul 21 23:54 scripts
drwxrwx---  2 emmenlau emmenlau  4096 Jul 21 23:54 src
```

Is this maybe a bug from the packaging? Could you try to bundle the Windows archive with file access permissions? I fixed the problem already on my end, but it may be cleaner to fix the archive...

Thanks a lot and keep up the good work!

**Comment by zeux** [comment]
Seems like a packaging issue to me. I've changed the script to assign explicit permissions to files; here's the resulting package file for current master:

[pugixml-1.9.zip](https://github.com/zeux/pugixml/files/2217681/pugixml-1.9.zip)

The fixed script will be used to package future releases; for now you can use .tar.gz archive as a workaround.

**Comment by emmenlau** [comment]
Thanks, that sounds good! I found another issue later that I did not report yet: the archives from your website do not contain the test directory, is that possible?
