### ISSUE TITLE
Test fails on MSVC with Intel Compiler 2018

### ISSUE THREAD

**Issue by emmenlau** [zeux/pugixml#218]
I can successfully build pugixml 1.9 on MSVC with the latest Intel Compiler 2018.3. However one test fails:
```
Test xpath_denorm_numbers failed: query.c_str() does not evaluate to "0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000009999987484955998" in context xml_node() at D:\tmp-ICC-Nehalem-7-x64-icl18.0.3.210\Release\Shared\pugixml-1.9\tests\test_xpath.cpp:254
FAILURE: 1 out of 932 tests failed.
```
The message does not mean much to me, does it mean something to you? Can I help to debug this issue?

**Comment by zeux** [comment]
The test verifies that printing of denormal numbers works as expected. My guess is that Intel compiler sets a flush-denorm-to-zero flag in their runtime which breaks the test.

You can look at the raw result by adding code along these lines to the test:

	std::string result = xpath_query(query.c_str()).evaluate_string(xml_node());

Does `result` evaluate to `0` on your compiler?
