### ISSUE TITLE
Test fails on MSVC

### ISSUE THREAD

**Issue by emmenlau** [zeux/pugixml#222]
I build latest pugixml from HEAD on Windows with Visual Studio 2015 and 2017 and with MinGW-w64. One of the tests fails:
```
Test document_contents_preserve failed: test_save_narrow(doc, format_raw | format_no_declaration | format_write_bom, files[dst].encoding, files[dst].data, files[dst].size) is false at D:\builds\pugixml\tests\test_document.cpp:1121
```

**Comment by zeux** [comment]
What file does the test fail for? I suspect this might be related to newline conversion, which could happen if core.autocrlf is used - looks like I need to add `.gitattributes` to prevent this from happening for tests/data folder...
