### ISSUE TITLE
How to test if xml_document is empty/not loaded/not created?

### ISSUE THREAD

**Issue by emptyVoid** [zeux/pugixml#223]
`xml_document::empty()` always returns `false`.

**Comment by zeux** [comment]
`xml_document::empty()` is a side-effect of the inheritance structure - it uses `xml_node::empty()` that checks if the node is an empty handle.

To check if the document is empty, you should check if the document has the document element - e.g. `if (doc.document_element())`

**Comment by emptyVoid** [comment]
Thanks!
