### ISSUE TITLE
Version macro and comment discrepancy

### ISSUE THREAD

**Issue by emptyVoid** [zeux/pugixml#224]
Here's the version macro definition:
```
#ifndef PUGIXML_VERSION
// Define version macro; evaluates to major * 100 + minor so that it's safe to use in less-than comparisons
#	define PUGIXML_VERSION 190
#endif
```
Contrary to the comment it looks like the version macro has `major * 100 + minor * 10 + patch` format. Could anyone clarify that one please? And what would it look like for version 1.10 (if it's planned)?

**Comment by zeux** [comment]
It's supposed to be major * 100 + minor * 10 + patch, the comment is incorrect. It's most likely that the next release will be 2.0; if we need minor releases I guess we'll need to settle for 1.9.1-1.9.9.
