### ISSUE TITLE
Missing Doc Information In Manual

### ISSUE THREAD

**Issue by deang** [zeux/pugixml#229]
pugixml.hpp contains important information about class methods which is not present in docs/manual.html.  For example docs/manual.html has the xml_node::value() method without the clarifying point found in pugixml.hpp:

// Get node value, or "" if node is empty or it has no value
// Note: For <node>text</node> node.value() does not return "text"! Use child_value() or text() methods to access text inside nodes.

**Comment by zeux** [comment]
Now that I looked at this closer, right after value() documentation there's a paragraph describing this gotcha:

> It is common to store data as text contents of some node - i.e. <node><description>This is a node</description></node>. In this case, <description> node does not have a value, but instead has a child of type node_pcdata with value "This is a node". pugixml provides several helper functions to parse such data:

This seems pretty clear to me so I'll close this.
