### ISSUE TITLE
Attributes without value

### ISSUE THREAD

**Issue by iUltimateLP** [zeux/pugixml#230]
Hello there, thanks for the library. I'm using it for my game, but I'm missing the functionality to have attributes without value, as I want to use it as a switch, e.g.
```xml
<cash random/>
```
or
```xml
<cash/>
```
should act like a simple switch to turn random mode on or off. You could add a parse flag for that so people can still disable it. Thank you :)

**Comment by brandl-muc** [comment]
That would not be valid XML, see for example [this SO thread](https://stackoverflow.com/q/6926442/1969455). 

Why can't you use a bool attribute?

**Comment by iUltimateLP** [comment]
Ah I didn't know that, I thought it is valid XML. I'm going to use a bool attribute then, thank you!
