### ISSUE TITLE
Possible xpath-engine bug

### ISSUE THREAD

**Issue by astramax** [zeux/pugixml#234]
Good day.  
I have a pugixml v.1.9 and a simple xml-file:
```
<?xml version="1.0"?>
<a>
<b>
<c>
<id_a v="1"/>
<id_b v="2"/>
<id_c v="3"/>
</c>
</b>
</a>
```

I am try to evaluate expressions with disjunction like this:
`/a/b/c/id_a/@v | /a/b/c/id_b/@v`
and this:
`/a/b/c/(id_a | id_b)/@v`

Result in first case is "empty" and application crash in second case.

my code is
```

#include "stdafx.h"
#include <iostream>

#include "pugixml.hpp"


int _tmain(int argc, _TCHAR* argv[])
{
	pugi::xml_document the_doc;
	pugi::xml_parse_result parse_result = the_doc.load_file("test_xpath.xml");
	if(!parse_result)
	{
		std::cout << "load_file error";
		return 1;	
	}

	pugi::xpath_node_set res = the_doc.select_nodes("/a/b/c/id_a/@v | /a/b/c/id_b/@v");
	if(res.empty())
        std::cout << "No nodes found";
    else
		std::cout << res.size() << " node(s) found";


	res = the_doc.select_nodes("/a/b/c/(id_a | id_b)/@v");
	if(res.empty())
        std::cout << "No nodes found";
    else
		std::cout << res.size() << " node(s) found";
	
	return 0;
}
```

Altova XMLSpy works well

![1](https://user-images.githubusercontent.com/35560206/46603335-6da60900-cafb-11e8-884f-b939e08e8e02.PNG)
![2](https://user-images.githubusercontent.com/35560206/46603337-6e3e9f80-cafb-11e8-8a4c-8ad51d05a0f9.PNG)

Best regards, Max.

**Comment by zeux** [comment]
Your second query isn't valid XPath 1.0 - I think it might be valid XPath 2.0 which is why XMLSpy works; pugixml only supports XPath 1.0. What happens is that select_node throws a pugi::xpath_exception object that contains the parsing error.

Your first query works for me with the .cpp file and the .xml file you've provided. I get "2 node(s) found". Do you get "No nodes found"?

**Comment by astramax** [comment]
You are right. Second expression is XPath 2.0 -compartible and exception was throws. And first expression is works well, I get "2 node(s) found".

Аre you planning to add support XPath 2.0 in pugixml?

**Comment by zeux** [comment]
> Аre you planning to add support XPath 2.0 in pugixml?

No - XPath 2.0 is way too large unfortunately; XPath 1.0 is a relatively simple query language but XPath 2.0 is a full blown programming language with variables, loops, etc. So it's outside of scope for pugixml.
