### ISSUE TITLE
*PLEASE* don't mess with already-released tarballs.

### ISSUE THREAD

**Issue by LebedevRI** [zeux/pugixml#237]
Hi.

This is the second time that i know of.
Please please please, once you have made a release, and uploaded release tarballs,
DO NOT TOUCH THEM. Ever. For any reason whatsoever. Make new release.

18 days ago https://github.com/zeux/pugixml/releases/download/v1.9/pugixml-1.9.tar.gz
had SHA512=f97941941d98a1a056087edc0dde6376bf2cc12ce4523b67a2f2ec5ae0895c2a2e55da32fcca6a997f1a0d918c5f39564167da0a07ce0d7da92880ad8631c31e
now, it is 853a9d985aae537391c6524d5413ef4de237d99d96cc58ea7fe7152f786df1e408cdacd2e4387697e23c3e67cdc1d42b29de554501309eae16d86edd0e24785f

This is really not cool. It is unclear whether there is a MITM, a typo in the checksum that was saved,
or something else :/

**Comment by zeux** [comment]
I'm not sure how to check the upload history but this release clearly wasn't re-released. I'm not sure what happened here.

**Comment by zeux** [comment]
This file was updated on August 20:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/pugixml.rb

It lists d156d35b83f680e40fd6412c4455fdd03544339779134617b9b28d19e11fdba6 as the SHA256. This matches what I can compute from a file I just downloaded:

```
zeux@SM-ARSENY3:/mnt/c/Users/arseny/Downloads$ openssl sha512 pugixml-1.9.tar.gz
SHA512(pugixml-1.9.tar.gz)= 853a9d985aae537391c6524d5413ef4de237d99d96cc58ea7fe7152f786df1e408cdacd2e4387697e23c3e67cdc1d42b29de554501309eae16d86edd0e24785f
zeux@SM-ARSENY3:/mnt/c/Users/arseny/Downloads$ openssl sha256 pugixml-1.9.tar.gz
SHA256(pugixml-1.9.tar.gz)= d156d35b83f680e40fd6412c4455fdd03544339779134617b9b28d19e11fdba6
```

Are you sure the SHA512 you have recorded was correct?

**Comment by zeux** [comment]
Same SHA256 is recorded here:
https://patchwork.ozlabs.org/patch/927119/

My conclusion is that you have incorrectly recorded the SHA512 previously. Just to reiterate, the *only* instance of reupload was the timestamp fix applied to .tar.gz of 1.8.0 (I think?) - no files have been reuploaded since and they won't be in the future.

**Comment by LebedevRI** [comment]
I don't remember repacking it at least..
```
/usr/src# sha512sum pugixml-1.9.tar.gz
f97941941d98a1a056087edc0dde6376bf2cc12ce4523b67a2f2ec5ae0895c2a2e55da32fcca6a997f1a0d918c5f39564167da0a07ce0d7da92880ad8631c31e  pugixml-1.9.tar.gz
/usr/src# ls -lah pugixml-1.9.tar.gz 
-rw-r--r-- 1 lebedevri lebedevri 543K Oct  6 21:42 pugixml-1.9.tar.gz
```
[pugixml-1.9.tar.gz](https://github.com/zeux/pugixml/files/2511838/pugixml-1.9.tar.gz)

**Comment by zeux** [comment]
Ok - I see what's going on. The SHA512 you had in mind was for this:

https://github.com/zeux/pugixml/archive/v1.9.tar.gz

Not for this:

https://github.com/zeux/pugixml/releases/download/v1.9/pugixml-1.9.tar.gz

The former is the source package that GitHub automatically makes, that just archives every single file in the repository.
The latter is the release package that I build - these contain only files that are relevant to the end users, with the correct newlines per platform (.zip is different from .tar.gz - not sure if GitHub archive behaves the same way).

**Comment by LebedevRI** [comment]
I have come to the same conclusion at the same time :/
```
$ wget https://github.com/zeux/pugixml/archive/v1.9.tar.gz
--2018-10-24 21:40:28--  https://github.com/zeux/pugixml/archive/v1.9.tar.gz
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/zeux/pugixml/tar.gz/v1.9 [following]
--2018-10-24 21:40:29--  https://codeload.github.com/zeux/pugixml/tar.gz/v1.9
Resolving codeload.github.com (codeload.github.com)... 192.30.253.121, 192.30.253.120
Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘v1.9.tar.gz’

v1.9.tar.gz                                                             [   <=>                                                                                                                                                             ] 542.46K   626KB/s    in 0.9s    

2018-10-24 21:40:31 (626 KB/s) - ‘v1.9.tar.gz’ saved [555480]

$ wget https://github.com/zeux/pugixml/archive/v1.9.zip
--2018-10-24 21:40:36--  https://github.com/zeux/pugixml/archive/v1.9.zip
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/zeux/pugixml/zip/v1.9 [following]
--2018-10-24 21:40:37--  https://codeload.github.com/zeux/pugixml/zip/v1.9
Resolving codeload.github.com (codeload.github.com)... 192.30.253.121, 192.30.253.120
Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘v1.9.zip’

v1.9.zip                                                                [    <=>                                                                                                                                                            ] 610.72K   662KB/s    in 0.9s    

2018-10-24 21:40:39 (662 KB/s) - ‘v1.9.zip’ saved [625376]

$ sha512sum v*
f97941941d98a1a056087edc0dde6376bf2cc12ce4523b67a2f2ec5ae0895c2a2e55da32fcca6a997f1a0d918c5f39564167da0a07ce0d7da92880ad8631c31e  v1.9.tar.gz
6fe52b7b086b32310d7a939352c4b1732d6a53425029d376c169c796721144a1db82b6b5476e99c483ab674097a47584dc83f31dd39ee381f13ea4271b50c843  v1.9.zip
```
Indeed, i messed up here, i'm sorry.

**Comment by zeux** [comment]
It's unfortunate that GitHub serves the v1.9.tar.gz file using the pugixml-1.9.tar.gz name - at least that's what happens if I open the link in Chrome. Sort of understandable - they probably want the repo-specific name so that it's more convenient for the users - but unfortunately as a result the downloaded names are exactly the same.
