### ISSUE TITLE
Escaping newlines only?

### ISSUE THREAD

**Issue by nlyan** [zeux/pugixml#253]
Hi,

I'm having some problems getting pugi to output the XML I want. In essence I'm serializing a parse tree  and require mixed content nodes. The problem is, I'd also like nicely indented output and some of my plain-text nodes will definitely contain new lines.

I see in https://github.com/zeux/pugixml/commit/5f996eba6deaa804bf4caced8acc65d8626720d6 that some changes were made to make mixed-content roundtrip properly. This is awesome, and as far as my understanding goes, it means pugi doesn't emit a newline and indentation prior to the next sibling, assuming it's an element.

Example:
```xml
    </someIndentedNode>my text
 with significant
    whitespace and new
 lines<nextSibling>foo</nextSibling>
    <someIndentedNode>
```

It occurs to me though that this problem can also be solved by emitting text nodes / PCDATA where \n and \r characters are escaped to &#10; and &#13; respectively. 

```xml
    </someIndentedNode>my text&#10; with significant&#10;    whitespace&#10; and new&#10; lines
        <nextSibling>foo</nextSibling>
    <someIndentedNode>
```

In this form, it's always safe to select a bunch of lines and tab or shift-tab in a text editor, because you know that the final new line and indentation on line 2 (prior to nextSibling) is not part of the data.

Is there anyway to accomplish this in pugi? I couldn't find an option to escape newlines in output, or a function that would accept text with escape sequences like `&#10;` without turning it in to `&amp;#10;`

**Comment by zeux** [comment]
Yeah, the change that you linked should make sure, that in mixed content there's no indentation or newlines around text nodes; however, if you have sibling nodes, they will still be separated with a newline.

Can you explain - maybe with an example - what kind of formatting you'd like to achieve?

Wrt disabling escaping or escaping newlines, I think the only currently available solution is to disable escaping altogether (by using `format_no_escapes`) and do escaping of everything manually as necessary . (obviously that's not very convenient, but that's the only option available atm)

**Comment by nlyan** [comment]
Thinking about it, I think you're right that the newline and indentation before <nextSibling> is undesirable, for no other reason than anyone parsing the document has to be aware that the trailing newline and indent can be stripped. This is very reminiscent of the classic HTTP `obs-fold` problem (The HTTP/1.1 spec dictates that leading and trailing whitespace on the rhs of header values should be stripped, yet allows for continuation lines over CRLFs via indentation)

This requires some thought.

**Comment by nlyan** [comment]
In the end I opted to emit ordinary plain text nodes between elements, except for cases where the content I wanted to emit consisted purely of white space (' ', '\t', '\r', '\n'), in which case I emit CDATA
