### ISSUE TITLE
XPath union results in node order that is not stable run to run

### ISSUE THREAD

**Issue by paul-seidel** [zeux/pugixml#254]
pugixml is really a nice software. Easy to use and incredibly fast.

I have a monster XML of 111 MB. It only takes two lines of code and half a second to load it. Great!

But unfortunately there seems to be a small error in load_file:

Among other things, the XML contains the two elements
    
    	_/BMECAT/T_NEW_CATALOG/ARTICLE/ARTICLE_DETAILS/DESCRIPTION_SHORT
        /BMECAT/T_NEW_CATALOG/ARTICLE/ARTICLE_DETAILS/EAN_
        
EAN is optional. 
    
If I select these elements, a NodeList like this should come out:
 
        SHORT EAN SHORT EAN SHORT SHORT SHORT EAN SHORT EAN ...
        
I'll get that, too. But unfortunately not always. Sometimes I get a list like this:
 
 	SHORT EAN SHORT EAN SHORT SHORT SHORT EAN **EAN** SHORT ...
        
 At first I thought it was because of the order of the elements in the document. But the result is (seemingly) random. The result seems to be rather due to the addresses in the memory. I don't know.

In the example I let the elements be selected 100 times. The wrong order occurs in about 30% of the cases - and always in a different place. Here is an exemplary program output:
    
        Loop 000 : 17113 nodes
        Loop 001 : 17113 nodes
        Loop 002 : 17113 nodes
        Loop 003 : 17113 nodes
        Loop 004 : 17113 nodes
        Loop 005 : 2426 nodes
        Loop 006 : 17113 nodes
        Loop 007 : 17113 nodes
        Loop 008 : 17113 nodes
        Loop 009 : 17113 nodes
        Loop 010 : 2372 nodes
        Loop 011 : 3526 nodes
        Loop 012 : 17113 nodes
        Loop 013 : 17113 nodes
        ...
        
I use an older **Xcode 3.2 on Mac OS X 10.13.6**. But the same things happens with newer versions of Xcode with 32 bit and 64 bit applications as well as with Windows and various Visual Studio versions.
    
I have found a workaround:
 
    #define PUGIXML_MEMORY_PAGE_SIZE  				32768*4
    
But I think it's just "coincidence" that it works then.

Thanks in advance for checking that.

Best regards,

    _Paul._
[xxxx.zip](https://github.com/zeux/pugixml/files/2743257/xxxx.zip)
[Bosch.xml.zip](https://github.com/zeux/pugixml/files/2743260/Bosch.xml.zip)

**Comment by zeux** [comment]
My recollection is that the behavior that you observe is compliant with XPath spec, but I'll take a closer look at the spec to figure out if the implementation should change - I agree the behavior is not intuitive. Here's what happens:

1. pugixml does not maintain the document order when merging node sets in a union operation
2. however, union operation has to deduplicate the resulting node set. To do that, the node set is sorted using the node handle (which is a pointer) as a sorting key, and duplicate consecutive elements are collapsed
3. as a result, your traversal order depends on the specifics of the memory allocation behavior - which depends on the memory page size...

You can easily force the order by calling

    nodeSets.sort();

after retrieving the data from an XPath operation; this sorts the nodes using the document order which is what your loop expects.

I'll double check what should happen as per XPath spec, and take another look at making the union deduplication more well-behaved - I did previously consider keeping the lists sorted after a union, but it's not always cheap to do that.

**Comment by zeux** [comment]
Nice :) Looking at the XPath spec, it doesn't really address this issue since it treats node sets as unordered abstract containers and doesn't define iteration order. I'm going to look into making the internal duplicate removal code preserve the original order, which would make the non-sorted output have all DESCRIPTION_SHORT nodes precede all EAN nodes which is much more intuitive, and hopefully can be reasonably performant as well.

**Comment by paul-seidel** [comment]
Hi Arseny!

O nice. Thanks for that - May be good idea for next releases. But no stress, for me the sort function is fast enough.

Paul

Gửi từ thành phố Hồ Chí Minh tại Việt Nam

Am 11.01.2019 um 12:49 schrieb Arseny Kapoulkine <notifications@github.com<mailto:notifications@github.com>>:


Nice :) Looking at the XPath spec, it doesn't really address this issue since it treats node sets as unordered abstract containers and doesn't define iteration order. I'm going to look into making the internal duplicate removal code preserve the original order, which would make the non-sorted output have all DESCRIPTION_SHORT nodes precede all EAN nodes which is much more intuitive, and hopefully can be reasonably performant as well.

**Comment by tuananh** [comment]
> My recollection is that the behavior that you observe is compliant with XPath spec, but I'll take a closer look at the spec to figure out if the implementation should change - I agree the behavior is not intuitive. Here's what happens:
> 
> 1. pugixml does not maintain the document order when merging node sets in a union operation
> 2. however, union operation has to deduplicate the resulting node set. To do that, the node set is sorted using the node handle (which is a pointer) as a sorting key, and duplicate consecutive elements are collapsed
> 3. as a result, your traversal order depends on the specifics of the memory allocation behavior - which depends on the memory page size...
> 
> You can easily force the order by calling
> 
> ```
> nodeSets.sort();
> ```
> after retrieving the data using the XPath query; this sorts the nodes using the document order which is what your loop expects.
> 
> I'll double check what should happen as per XPath spec, and take another look at making the union deduplication more well-behaved - I did previously consider keeping the lists sorted after a union, but it's not always cheap to do that.

if i do `nodeSets.sort()` , it won't respect the order in the query right?

eg: `//a|//b` won't be preserved?  check a first, if not then b?

**Comment by zeux** [comment]
@tuananh this is correct; however, note that right now the order in the query is *not* respected by pugixml in general (`//a|//b` results in, potentially, a mix of `a` and `b` nodes)

**Comment by tuananh** [comment]
@zeux if i would like to preserve the order in my fork, can you point me to where should i make the change?

Thank you.

**Comment by zeux** [comment]
You'll want to change remove_duplicates (https://github.com/zeux/pugixml/blob/master/src/pugixml.cpp#L8853-L8859) to avoid sorting the vector, and union code itself (https://github.com/zeux/pugixml/blob/master/src/pugixml.cpp#L10743-L10747) to append right to left instead of left to right; for that you'll need to compute ls on the `stack` and rs on the `swapped_stack`, they're currently computed in reverse.

**Comment by zeux** [comment]
The PR above fixes this issue by maintaining the order in a union; to be clear, if this was always the case, the code in the original post would *not* work (since it relies on document order), but it would be obvious that it doesn't since it wouldn't depend on the memory layout.

The PR is complete outside of some coverage tests that I still need to add for out-of-memory cases.
