### ISSUE TITLE
Can add a optional for compare ALL node name by ignore-case ? [enhancement]

### ISSUE THREAD

**Issue by hihihlo** [zeux/pugixml#26]
[this is a enhancement, not bug]
Sometimes I need NOT match case sensitive, ex: accept all below : NodeName/nodeName/Nodename/nodename,
It maybe use in xml_node::child(),  xml_node::next_sibling(),  ... ,
so need modify strequal() & strequalrange() function.
(Msxml.DOMDocument can ignore case in my test result)

Sorry I don't know how to assign label (enhancement),
Thank you !

**Comment by zeux** [comment]
XML is usually case sensitive, so case insensitive comparisons are rarely needed.
Additionally, implementing a correct Unicode-aware case-sensitive comparison is relatively involved.

Both of these combined mean that this feature does not really fit pugixml. It should be straightforward to implement custom functions that you may need as helpers, e.g. ```xml_node child_ignorecase_ascii(xml_node, const char*)``` in your header file.

**Comment by mr-phazer** [comment]
I have made a "version" og PUGI-XML has has [child_no_case ](url)and [atrribute_no_case](url) added methods, 

`PUGI_IMPL_FN xml_node xml_node::child_no_case(const char_t* name_) const
{
	if (!_root) return xml_node();

	for (xml_node_struct* i = _root->first_child; i; i = i->next_sibling)
	{
		const char_t* iname = i->name;			
		if (iname &&  toUpper(name_) == toUpper(iname))			
			return xml_node(i);
	}

	return xml_node();
}`

it is not like it is rocket-science,  I but could look at how portable my code is, and maybe push it?
There is also a simple way to make the whole library case-insentive, ofc you guys are coders, you you know already :)
