### ISSUE TITLE
xml_node::select_node(s) will act on the entire document

### ISSUE THREAD

**Issue by Sil3ntStorm** [zeux/pugixml#260]
`pugi::xml_node::select_nodes` (and related) will act on the entire document rather than the node it was called on.

The following code
```
	pugi::xml_document doc;
	if (auto result = doc.load_file("testcase"); !result) {
		std::cerr << "Failed to parse file: " << result.description() << " at " << result.offset << " near\n";
		return;
	}

	auto container = doc.select_node("//div[@class=\"container\"]").node();
	auto tags = container.select_nodes("//div[@class=\"alpha\"]");
	int i = 0;
	std::array<std::string, 3> want{ "foo", "bar", "foobar" };
	for (auto&& tag : tags) {
		auto node = tag.node();
		std::cout << "=== Processing node:\n";
		node.print(std::cout);
		std::cout << "\n\n";
		std::string info = node.select_node("//div[@class=\"info\"]").node().text().as_string();
		std::cout << "Have: " << info << " Want: " << want[i] << '\n';
		assert(info == want[i++]);
	}
```

with `testcase` having the following content:

```
<body>
    <div>
        <div class="info">unrelated stuff</div>
    </div>
    <div class="container">
        <div class="beta">
            <div class="info">cool shit</div>
        </div>
        <div class="alpha">
            <div class="info">foo</div>
        </div>
        <div class="alpha">
            <div class="info">bar</div>
        </div>
        <div class="alpha">
            <div class="info">foobar</div>
        </div>
    </div>
</body>
```

should not fail the assertion but does. In fact it will always get the `unrelated stuff` part.
Line 14 will in fact print out the correct node that the XPath should be applied to, but isn't.
This is a very much simplified example showing the issue.

**Comment by zeux** [comment]
This is correct as per XPath spec, see https://www.w3.org/TR/1999/REC-xpath-19991116/:

```
//para selects all the para descendants of the document root and thus selects all para elements in the same document as the context node
.//para selects the para element descendants of the context node
```

In other words, you probably want to use `.//div` instead.

**Comment by Sil3ntStorm** [comment]
Not very intuitive to have a node/object that a function is executed on, go to an entirely different object to run on...
Anyways I guess there is some obscure situation where someone somewhere would want the current one so

**Comment by zeux** [comment]
This is how XPath works - queries that start with `//` apply to the entire document that the context node belongs to. This isn't something that pugixml chooses as an API behavior, this is simply how every conformant XPath implementation must work.

**Comment by Sil3ntStorm** [comment]
Yeah, it was just not really intuitive. In any case it can be worked with. Thanks for the explanation.

**Comment by zeux** [comment]
That would preclude the use of correct (in this case) XPath expression “.//node”.

While use of // in a non-document context is certainly unintuitive, it can’t be treated as an error as that would violate XPath spec, and there’s no warning mechanism that can be used.
