### ISSUE TITLE
Allow specify encoding in xml header

### ISSUE THREAD

**Issue by Yanpas** [zeux/pugixml#266]
Currently with utf8 encoding calling save resultts in header like this: `<?xml version="1.0"?>`

This results in slower parsing with some popular xml libraries, like lxml.

The header `<?xml version="1.0" encoding="utf-8"?>` improves performance.

I will open a PR and add a flag `flag_declaration_encoding`. Should it be on by default?

**Comment by zeux** [comment]
You can customize the entire declaration including encoding by adding node_declaration to the document using doc.prepend_child and filling it with attributes.

**Comment by zeux** [comment]
Also - not sure if it will help because I’m not sure why lxml is slow, maybe it’s worthwhile to fix lxml instead? - you can use format_write_bom to get UTF8 BOM

**Comment by Yanpas** [comment]
Thanks! That resolves issue for me. Not sure what slows down lxml, but my xml contain a lot of russian alphabet characters which consist of two bytes.

Still not sure if encoding should be included by default.

**Comment by zeux** [comment]
IIRC right now pugixml only includes the encoding if it’s necessary to disambiguate - I think this is only necessary when output encoding is latin1; I need to double check the spec but I thought that in absence of BOM or encoding header the spec says that the default is utf8

**Comment by Yanpas** [comment]
Rewritten perf test with monotonic timer and iterating through string first, now encoding doesn't make a difference

**Comment by zeux** [comment]
Looked at the spec again and it looks like encoding isn’t necessary and parsers must assume utf-8 in absence of BOM and an explicit encoding declaration; given that and the fact that you can add a custom declaration node this doesn’t seem necessary.
