### ISSUE TITLE
parse_doctype didn't works if doctype is write in lowercase

### ISSUE THREAD

**Issue by sebastien247** [zeux/pugixml#267]
_pugi::xml_parse_result result = doc.load_string(source, pugi::parse_doctype );_ return _status_unrecognized_tag_ if doctype is write in lowercase **<!doctype html>**

**Comment by zeux** [comment]
XML specification mandates that DOCTYPE is upper-case:

https://www.w3.org/TR/xml/#NT-doctypedecl
