### ISSUE TITLE
How to preserve xml entity during save

### ISSUE THREAD

**Issue by senthilsam** [zeux/pugixml#268]
Input:
<given-names>Iv&#x00E1;n</given-names>

Output:
<given-names>Iván</given-names>

I want to preserve all the xml entity during save. How to do that?

**Comment by zeux** [comment]
I’m not sure what the request is but if I had to guess, you can disable parsing entities by removing parse_escapes flag from the default parsing flags (i.e. `parse_default & ~parse_escapes`) and disable quoting when saving the document by using format_no_escapes (i.e. `format_default | format_no_escapes`). You will have to take care of escaping data that is added to the document in C++ though.
