### ISSUE TITLE
Should append_attribute() prevent creation of duplicate attributes?

### ISSUE THREAD

**Issue by macsinus** [zeux/pugixml#269]
According to Wikipedia, "each attribute can appear at most once on each element".
https://en.wikipedia.org/wiki/XML#Key_terminology

I've done this accidentally once or twice - it would have helped me if append_attribute() had either treated this as an error or returned the existing attribute.

**Comment by zeux** [comment]
This is an intentional choice - for performance reasons parser and DOM don’t impose single attribute restriction. Without this adding 10 attributes would require 45 string comparisons which can be problematic for applications that construct  a lot of nodes at runtime.

**Comment by macsinus** [comment]
OK, this is understandable to keep pugixml fast and lean.
I'll write my own trivial wrapper because those factors aren't so important in my case.

**Comment by SlySven** [comment]
:book: I've accidentally just done this on a project I was coding for. We use the pugixml library for generation of the XML but use Qt's [QXmlStreamReader](https://doc.qt.io/qt-5/qxmlstreamreader.html) to read the XML produced - and it was unhelpfully obtuse! It merely reporting an element `QXmlStreamReader::tokenType()` of `QXmlStreamReader::Invalid` for the element with a duplicated attribute which it took me some hours to spot...! :cry:
