### ISSUE TITLE
Reorder siblings

### ISSUE THREAD

**Issue by luspi** [zeux/pugixml#271]
Hello,

I've been trying to reorder some siblings in an xml document, but it doesn't quite work as I expected/hoped. Here's what I try and the result I get:

Say I have an xml document like this
```
<vehicle>
    <car brand="buick">
        [some stuff]
    </car>
    <car brand="saab">
        [some stuff]
    </car>
    <car brand="vw">
        [some stuff]
    </car>
</vehicle>
```

Now I would like to reorder the above document, say I'd like to have the buick car node in between the saab node and the vw node. I get a `pugi::xml_node` handle to both those nodes and tell pugixml to move:
```
pugi::xml_node ret = saab.node().append_move(buick.node());
```

This, however, leads to the buick node to be *inside* the saab node, like this:
```
<vehicle>
    <car brand="saab">
        [some stuff]
        <car brand="buick">
            [some stuff]
        </car>
    </car>
    <car brand="vw">
        [some stuff]
    </car>
</vehicle>
```

This is not quite what I want, though, but I can't find the right way to achieve such reordering. Is this even possible in pugixml?

**Comment by zeux** [comment]
You should be able to do this with insert_move_after/insert_move_before into the parent.

Something like

```
xml_node vehicle = saab.node().parent();
vehicle.insert_move_after(buick.node(), saab.node());
```

**Comment by luspi** [comment]
Yes, that did it! I tried to use insert_move_after() before but did something wrong...

Thanks for your help!
