### ISSUE TITLE
Minimal escaping

### ISSUE THREAD

**Issue by JayXon** [zeux/pugixml#272]
Right now pugixml escapes all of `"<>&`, but sometimes this isn't necessary.

- all `>` except for `]]>`

- `"` in text

- `"` in attributes could also avoid escaping by using `'` to quote (if the attribute doesn't contain `'`).

**Comment by zeux** [comment]
> all `>` except for `]]>`

This should be valid per XML spec (I had to double check):

> The right angle bracket (>) may be represented using the string " &amp;gt; ", and must, for compatibility, be escaped using either " &amp;gt; " or a character reference when it appears in the string " ]]> " in content, when that string is not marking the end of a CDATA section.

There's a simpler version of this that I can implement, which is that > doesn't need to be escaped in attribute values.

> `"` in text

I believe pugixml already doesn't escape `"` outside of attributes?

> `"` in attributes could also avoid escaping by using `'` to quote (if the attribute doesn't contain `'`).

I'm somewhat reluctant to automatically switch attribute quotation based on the attribute content; it seems like it can result in slightly confusing diffs when attribute content changes.

**Comment by JayXon** [comment]
You are right `"` in text is already not escaped, I read the wrong code path.
I agree that automatically switching attribute quotation is a bit hacky, is it possible to hide it behind a flag?

**Comment by zeux** [comment]
`>` is no longer escaped in attribute values; for quotation marks, we now have `format_attribute_single_quote` that allows to switch to single quoted attributes with double quotes not requiring escaping. (this is a global switch)

This is not a complete solution - attributes aren't going to automatically pick the "least escaping" option, and `>` is still escaped in PCDATA - but this seems close enough to minimal that I'm going to close this issue.

**Comment by JayXon** [comment]
Thanks!
