### ISSUE TITLE
Support single quotes for enclosing attribute values

### ISSUE THREAD

**Issue by m-naumann** [zeux/pugixml#274]
Hey @zeux ,

Thanks for your great work! Would you be willing to merge a PR for allowing either also single quotes `'` instead of double quotes `"` [for enclosing attribute values](https://github.com/zeux/pugixml/blob/master/src/pugixml.cpp#L4082) or a custom enquoting char?

That would be very handy for our [lanelet2](https://github.com/fzi-forschungszentrum-informatik/Lanelet2)-map-framework which allows to use [JOSM](https://josm.openstreetmap.de/) for map creating and editing, because JOSM uses single quotes in the map files, and this makes git-diffs always huge and untransparent.

Thanks

**Comment by zeux** [comment]
Yup, for sure! This has been on the todo list for a while but absent a request it just didn’t become prioritized. If you want to make a PR, go ahead - please use a format flag for this to minimize API changes, e.g. format_attribute_single_quote
