### ISSUE TITLE
Prevent attributes formatting

### ISSUE THREAD

**Issue by ribtoks** [zeux/pugixml#277]
Thanks for the most awesome XML library for C++!

This issue is a small feature request. Currently if you print document/node with `format_raw`, element attributes get formatted anyways. Would be great to create mode like `format_no_attributes` to keep attributes intact (like they were parsed).

Thanks

**Comment by zeux** [comment]
Can you give an example XML input, along with how pugixml formats it right now and how you’d like it to be formatted?

**Comment by ribtoks** [comment]
Left: before
Right: after pugixml (diff has wordwrap ON)

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/505555/59617021-65668a80-90da-11e9-83c2-e0735eafb571.png">

This is what I'm talking about. You have any XML tag with attributes that originally were on different lines 
```
<anyTag attribute1="value1"
               attribute2="value2"
...
>
</anyTag>
```

After formatting with *pugixml* with any flags (I tried almost all combinations) all attributes will be placed in 1 line. Do you want me to provide XML or this explanation is suffice?

What was expected is that there's a flag (for output, but probably will require mirror flag for input) like "pugi::dont_touch_attributes" i.e. leaves attributes formatted the original way.

**Comment by zeux** [comment]
Ok - I see. Unfortunately, this isn't really possible to implement - the whitespace around attributes is not considered as significant and is dropped during parsing. This is how, I believe, almost all other XML parsers work as well, at least I don't know a parser that preserves this data.

As a consequence, pugixml can only make formatting decisions that automatically apply to node/attribute data - currently attributes are either indented with an attribute on each line (`format_indent_attributes`) or not (`format_default` or `format_raw`).

If your goal is to have XML files that are easily mergeable/diffable, I'd recommend using `format_indent_attributes`. If your goal is to preserve indentation from the original document then unfortunately pugixml can't do that.
