### ISSUE TITLE
Performance about parsing large xml(50M+)

### ISSUE THREAD

**Issue by DebbieDebbieli** [zeux/pugixml#278]
Msxml-dom parses a 50M+ xml cosing about 30s. To make it fast according to https://pugixml.org/benchmark.html,  I try pugixml. However, pugixml uses 3min+. Is anything wrong?

**Comment by zeux** [comment]
pugixml should parse 50MB in under a second. Are you building pugixml in Release mode? Are you measuring the time it takes to call xml_document::load_file or does that include the time to process the resulting document?

**Comment by DebbieDebbieli** [comment]
Directly use the .hpp and .cpp in my project and the test is under release mode. 3min is wasted by load_buffer and traversal the xml node. Following the the main loader. 
       //xml_document m_doc,     std::wstring wsXmlText
	pugi::xml_parse_result result = m_doc.load_buffer(wsXmlText.c_str()wsXmlText.size()*sizeof(wchar_t));
	//std::cout << result.description() << std::endl;
	return (result);
}

**Comment by zeux** [comment]
Can you measure the time for load_buffer *separately* from the traversal code? My best guess is that your traversal code is somehow inefficient, possibly quadratic somewhere. Not sure if you can share the code.

**Comment by DebbieDebbieli** [comment]
load_buffer costs about 0.29s. Most time is wasted by traveral the node, Following is test code:
https://github.com/DebbieDebbieli/TestXML
Thanks.

**Comment by zeux** [comment]
Thanks for the test code! Yeah I reproduced this issue with OpenStreetMap data and wow, wstring_convert is catastrophically inefficient here.

You can use `PUGIXML_WCHAR_MODE` as you noted, or alternatively you can use `pugi::as_wide` to perform the UTF8 -> UTF16 conversion and `pugi::as_utf8` to perform UTF16 -> UTF8 conversion; this change alone speeds traversal up from 21s to 0.14s on a 19 MB file for me.

If you intend to work with `wchar_t` everywhere in the application then probably using wchar mode is a better option.

**Comment by zeux** [comment]
It looks like most of the time is spent in the `wstring_convert` constructor; you can also move it into the global namespace to the top of the file:

```
static std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t> convert;
```

and that cuts down the traversal time almost as much as using pugixml functions.

**Comment by DebbieDebbieli** [comment]
Thanks a lot and it's solved. I'll use pugi to replace the msxml in the project.

**Comment by zeux** [comment]
Glad this worked for you. I'd also note that I would recommend letting pugixml load the file directly, either by using `xml_document::load_file` or by loading raw bytes from the file and calling `load_buffer` on that - in your existing code `std::wfstream` has quite a bit of overhead as well.

pugixml will automatically handle all encoding conversions, e.g. in wchar mode it will convert the document from UTF8 to wchar_t as necessary.
