### ISSUE TITLE
Make save easier

### ISSUE THREAD

**Issue by kristone** [zeux/pugixml#28]
What do you all think of have a version of xml_document::save with a functor-parameter (when it is quite cumbersome to implement the xml_writer-interface for every target) ?

   std::vector\<char\> xml;
   const auto functor = \[&xml\]( const void* const data, const std::size_t size)
   {xml.insert( xml.end(), data, data + size);} // perhaps some casting needed
   my_document.save( functor); // perhaps some other function-name is needed

**Comment by zeux** [comment]
Why do you need to have many different implementations of xml_writer?

**Comment by kristone** [comment]
I do not want many different implementations, I just want one; the functor-style ;-)

The implementations existing today is save to a (named) file and to a ostream and if I want to save it to another target I need to wither intermediate-save it to an ostringstream or implement the xml_writer-interface which is kind of cumbersome and not that modern (compared to a non-virtual-dispatch by using a functor/policy-interface that can be implemented by a lambda or such)

Ok, this is no biggie and I do not expect it to be high prioritized

**Comment by zeux** [comment]
So there are two parts here.

The first is an actual implementation. The writing implementation was specifically designed to minimize the number of virtual calls - it is heavily buffered internally. While using templated functors is possible, it would require moving a lot of code into the header, with no real performance gains (it's possible to restructure the implementation to gain performance in cases when conversion is not required by essentially bypassing buffering, but the number of cases when it would help is not that big; pugixml already does this for big pieces of data, see xml_buffered_writer::write_direct)

The second is the interface. It *is* possible to introduce a functor-based interface (by introducing a templated implementation of xml_writer interface). However, in the cases I've seen the actual number of implementations - e.g. the number of different functors you may want to pass in - is extremely limited, so the convenience benefit of a functor interface is not very significant.
