### ISSUE TITLE
unable to read attributes properly with different encoding character set (German, Russian, Chinese, Japanese)

### ISSUE THREAD

**Issue by chaipu88** [zeux/pugixml#281]
We am having an issue while reading the below attributes using pugi:

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<root>
	<child value="テスティング 化粧品"/>
	<child value="systèmes"/>
	<child value="gewähren"/>
	<child value="системы"/>
	<child value="你好"/>
</root>`

the following pugi code:
`{
		OutputDebugString(L"pugi\n");
		pugi::xml_document pPugiDocument;
		pugi::xml_parse_result result = pPugiDocument.load_file("test.xml", pugi::parse_full, pugi::encoding_auto);
		pugi::xml_node docElement = pPugiDocument.document_element();
		for (pugi::xml_node child = docElement.first_child(); child; child = child.next_sibling())
		{
			pugi::xml_attribute pugiChildAttr = child.attribute("value");
			std::string attrVal = pugiChildAttr.value();

			OutputDebugString(ConvertStringToCString(attrVal));
			OutputDebugString(L"\n");
		}
	}`

outputs:
ãƒ†ã‚¹ãƒ†ã‚£ãƒ³ã‚° åŒ–ç²§å“
systÃ¨mes
gewÃ¤hren
ÑÐ¸ÑÑ‚ÐµÐ¼Ñ‹
ä½ å¥½

where else msxml code:
`		MSXML2::IXMLDOMDocumentPtr pXMLDoc = NULL;
		pXMLDoc.CreateInstance(__uuidof(MSXML2::DOMDocument60));;

		pXMLDoc->async = false;

		CComVariant strFile = _T("test.xml");
		VARIANT_BOOL vbool = pXMLDoc->load(strFile);

		MSXML2::IXMLDOMElementPtr pRootElem;
		pXMLDoc->get_documentElement(&pRootElem);

		MSXML2::IXMLDOMNodeListPtr childList = NULL;
		pRootElem->get_childNodes(&childList);
		long lg = 0;
		childList->get_length(&lg);

		OutputDebugString(L"msxml\n");
		for (int i = 0; i<lg; i++)
		{
			MSXML2::IXMLDOMNodePtr pNode = childList->nextNode();
			if (pNode == NULL)
				continue;

			CString attrStr = GetAttributeValue(pNode, _T("value"));
			OutputDebugString(attrStr);
			OutputDebugString(L"\n");
		}`

outputs:
msxml
テスティング 化粧品
systèmes
gewähren
системы
你好

We are planning to migrate our code, from msxml to pugi.
Any solution to this problem, would be highly appreciable!
-Thanks

**Comment by zeux** [comment]
ConvertStringToCString is probably the issue, can you show the code for this function? pugixml by default uses UTF8 to store the data; if that function assumes the input string is ASCII or ANSI you will get something similar.

Note that you can also build pugixml with PUGIXML_WCHAR_MODE define in which case it will do all conversions for you and .value() will return const wchar_t* which is probably closer to MSXML.

**Comment by chaipu88** [comment]
> ConvertStringToCString is probably the issue, can you show the code for this function?

It just returns return CString(str.c_str())
`CString ConvertStringToCString(const std::string &str) 
{
	return CString(str.c_str());
}`

> Note that you can also build pugixml with PUGIXML_WCHAR_MODE define in which case it will do all conversions for you and .value() will return const wchar_t* which is probably closer to MSXML.

let me try this

-thanks

**Comment by zeux** [comment]
Right, so the issue was that ConvertStringToCString uses `CString(const char*)` constructor; this constructor assumes that input data is ANSI-encoded, not UTF-8 encoded. `PUGIXML_WCHAR_MODE` is one option, if it ever doesn't work for you you can use `pugi::as_wide` instead to convert `const char*` UTF8 strings to `std::wstring`.
