### ISSUE TITLE
Removing all children of node with one function

### ISSUE THREAD

**Issue by NeoProgramming** [zeux/pugixml#282]
pugi::xml_node has not member function like "clear" or "remove_all" for removing all children subnodes. It is possible to remove only single child node (xml_node::remove_child()), but this method perform additional actions, such as relink sibling nodes. This actions are necessary for removing single child node, but they are not necessary for removing all children of node.
Is it possible to add 'clear' method to pugi::xml_node?

**Comment by zeux** [comment]
Something like `xml_node::remove_children` and `xml_node::remove_attributes` would make sense to me.

**Comment by tuananh** [comment]
@zeux 

should it be sth like this?

```cpp
PUGI__FN bool xml_node::remove_children()
	{
		for (pugi::xml_node child: this->children())
		{
			remove_child(child);
		}

		return true;
	}
```

**Comment by zeux** [comment]
The implementation should work with internal APIs - probably will need to duplicate parts of `remove_child` - for efficiency; should have a loop through children using `xml_node_struct*`, and be careful to read the next sibling before the node gets destroyed - see `destroy_node` for an example. The implementation of remove_attributes would be similar.

**Comment by zeux** [comment]
In fact the optimal implementation should only call `impl::destroy_node`, and then manually clear out `first_child` pointer - this avoids the redundant node relinking mentioned in the original post.

**Comment by tuananh** [comment]
this is my attempt but it still fails. the child is still there.

```cpp
	PUGI__FN bool xml_node::remove_children()
	{
		for (pugi::xml_node child: this->children())
		{
			if (!_root || !child._root || child._root->parent != _root) return false;

			impl::xml_allocator& alloc = impl::get_allocator(_root);
			if (!alloc.reserve()) return false;

			impl::destroy_node(child._root, alloc);
			child._root->first_child = nullptr;
		}

		return true;
	}
```

test

```TEST_XML(dom_node_remove_children, "<node><n1/><n2/><n3/><child><n4/></child></node>")
{
	xml_node node = doc.child(STR("node"));
	xml_node child = node.child(STR("child"));

	child.print(std::cout);
	CHECK(child.remove_children());
	CHECK_NODE(child, STR("<child/></child>"));
}
```

**Comment by tuananh** [comment]
ah it seems to be working now. i will continue to work on `remove_attributes`
