### ISSUE TITLE
customize double precision

### ISSUE THREAD

**Issue by mikejiang** [zeux/pugixml#285]
see https://github.com/zeux/pugixml/issues/18#issuecomment-522169447
It can be set either globally or overridden locally (i.e. `xml_attribute::set_value` )

**Comment by zeux** [comment]
`set_value` overloads for this definitely make sense; global overrides could be separate, or could be part of the same change I suppose.

**Comment by tuananh** [comment]
when i tried this

```cpp
template <typename String, typename Header>
PUGI__FN bool set_value_convert(String& dest, Header& header, uintptr_t header_mask, float value, int precision=9)
{
    char buf[128];
    char fmt[16];
    PUGI__SNPRINTF(fmt, "%%.%dg", precision);
    PUGI__SNPRINTF(buf, fmt, double(value));

    return set_value_ascii(dest, header, header_mask, buf);
}

template <typename String, typename Header>
PUGI__FN bool set_value_convert(String& dest, Header& header, uintptr_t header_mask, double value, int precision=17)
{
    char buf[128];
    char fmt[16];
    PUGI__SNPRINTF(fmt, "%%.%dg", precision);
    PUGI__SNPRINTF(buf, fmt, value);

    return set_value_ascii(dest, header, header_mask, buf);
}
```

I got 3 old tests fails which are

* dom_fp_roundtrip_min_max_double
* dom_attr_assign_large_number_double
* dom_attr_assign_large_number_float

@zeux Can you see what I did wrong there?

**Comment by tuananh** [comment]
@zeux i have another question

i manage for tests to pass now but i have another question.

when i keep the default precision = 9 for float and 17 for double. if i set the precision to be lower than the default, the test will fail.

how can i fix that?

**Comment by zeux** [comment]
I'm not quire sure what you mean. Can you elaborate?
Also jfyi you can use "%.*g" to pass the precision as a separate argument to snprintf, you don't need a temporary format string.

**Comment by tuananh** [comment]
with this code https://github.com/tuananh/pugixml/blob/custom-precision/src/pugixml.cpp#L4667
and this test https://github.com/tuananh/pugixml/blob/custom-precision/tests/test_dom_modify.cpp#L1766

when i sent the custom precision for double, lower than the default old value of pugixml (17), this test will fail. if higher, it'll pass.

**Comment by tuananh** [comment]
> Also jfyi you can use "%.*g" to pass the precision as a separate argument to snprintf, you don't need a temporary format string.

can you give an example?

**Comment by zeux** [comment]
Isn't it expected? Maybe I'm missing something. 15 decimal digits isn't enough to represent DBL_MIN exactly.

**Comment by tuananh** [comment]
Ah I didnt know that. Thank you
