### ISSUE TITLE
XML namespace, etc? 

### ISSUE THREAD

**Issue by ylluminate** [zeux/pugixml#287]
I saw pugixml recommended [here](https://stackoverflow.com/a/3380618), but then some dissuasion [here](https://stackoverflow.com/questions/40796231/how-does-xpath-deal-with-xml-namespaces#comment68843112_40796315) and [here](https://stackoverflow.com/questions/40796231/how-does-xpath-deal-with-xml-namespaces#comment68844846_40796315).

Has there been any effort to resolve or implement these points yet in `pugixml`?

**Comment by tuananh** [comment]
i thought this work ? `'//mynode[namespace-uri() = "http://example.com"]'`

**Comment by zeux** [comment]
Please update the issue description to be more precise/clear about what you’re asking about without referring to unclear Stackoverflow discussions

**Comment by zeux** [comment]
If this is re: XPath, then the list of deviations from the standard in https://pugixml.org/docs/manual.html#xpath.w3c is still accurate and is not likely to change any time soon.
