### ISSUE TITLE
There is no nuget package for VS2019

### ISSUE THREAD

**Issue by Joelgranados** [zeux/pugixml#289]
When I update my solution to V142 I get the following message:
cannot open input file 'C:\...\packages\pugixml.1.9.0\build\native\lib\x64\v142\dynamic\Release\pugixml.lib'
And its because it only has the v141 directory.
Any plans to update to VS2019?

**Comment by Joelgranados** [comment]
Here is what I did to make it compile on my machine.
I tested the newly created nuget package and it works like a charm.
Note that I did not change the makefile nor the cmake. I just added yet another VS project file.

[0001-Update-nuget-creation-to-VS2019.txt](https://github.com/zeux/pugixml/files/3565633/0001-Update-nuget-creation-to-VS2019.txt)

**Comment by zeux** [comment]
I'd be happy to merge a pull request for this

**Comment by Joelgranados** [comment]
Pull request :)
https://github.com/zeux/pugixml/pull/291

**Comment by Joelgranados** [comment]
Now that the PR is in, how long will it take to get the nuget into nuget.org?

**Comment by zeux** [comment]
It’s about time to release the next version so I will bundle the nuget update with that; should happen in a few days.
