### ISSUE TITLE
[question] xpath function to print xml raw

### ISSUE THREAD

**Issue by tuananh** [zeux/pugixml#292]
i need to add a xpath function to get raw xml as string

```cpp
case ast_func_raw_0:
{
    printf("ast_func_raw_0");
    struct xml_string_writer: pugi::xml_writer
    {
        std::string result;
        virtual void write(const void* data, size_t size)
        {
            result.append(static_cast<const char*>(data), size);
        }
    };

    xpath_node na = c.n;
    xml_node n = na.node();
    switch (n.type())
    {
        case node_pcdata:
        case node_cdata:
        case node_comment:
        case node_pi:
            return xpath_string::from_const(n.value());

        case node_document:
        case node_element:
        {
            xml_string_writer writer;
            n.print(writer);
            printf("writer.result.c_str() %s", writer.result.c_str());
            return xpath_string::from_const(writer.result.c_str());
        }

        default:
            return xpath_string();
    }
}
```

the `printf` does print the xml string but i can't get it from the xpath function

my xpath query is this `root/mynode/raw()` (i name the function raw()) but it doesn't work

i also tried `raw(root/mynode)` but same thing

can you help point out what i did wrong here.

**Comment by zeux** [comment]
`xpath_string::from_const` has a specific semantics: it says "I'm going to create an xpath_string object from memory that will outlive the duration of XPath query execution". It doesn't copy the string, so it's very fast. This is used for strings stored inside the document.

When you create a string dynamically, you should use `xpath_string::from_heap(writer.result.c_str(), writer.result.c_str() + writer.result.size(), alloc. stack.result)`.

**Comment by tuananh** [comment]
> `xpath_string::from_const` has a specific semantics: it says "I'm going to create an xpath_string object from memory that will outlive the duration of XPath query execution". It doesn't copy the string, so it's very fast. This is used for strings stored inside the document.
> 
> When you create a string dynamically, you should use `xpath_string::from_heap(writer.result.c_str(), writer.result.c_str() + writer.result.size(), alloc. stack.result)`.

i assume you mean that last arg is `stack.result`?

also, i saw this `xpath_allocator_capture cr(stack.result);` quite often but don't really get what it does. can you explain this bit to me.


```cpp
struct xpath_allocator_capture
	{
		xpath_allocator_capture(xpath_allocator* alloc): _target(alloc), _state(*alloc)
		{
		}

		~xpath_allocator_capture()
		{
			_target->revert(_state);
		}

		xpath_allocator* _target;
		xpath_allocator _state;
	};
```

**Comment by zeux** [comment]
Yeah, sorry, last argument is `stack.result` - started to type `alloc` and then realized the variable isn't called that. `xpath_allocator_capture` is used when there are some allocations being made for temporary objects; the internal allocator used by XPath engine doesn't free memory, but you can setup checkpoints using allocator_capture to reclaim all memory allocated up until that point. For your function you don't really need this because the expectation is that if a function returns a string, the string has been allocated on the current stack (which is why you should pass `stack.result` to `from_heap` function).

**Comment by tuananh** [comment]
Thank you. it works now
