### ISSUE TITLE
Full release for 1.10?

### ISSUE THREAD

**Issue by hobbes1069** [zeux/pugixml#293]
Is release 1.10 going to get the full treatment? Currently on the release page it's still showing 1.9 as the "Latest release" and there's no download archives.

I tried the auto-tar.gz but it was missing contribs...

**Comment by zeux** [comment]
v1.10 is now fully released; note that contrib/ was removed from pugixml (see https://github.com/zeux/pugixml/commit/434c4a4d41bfc4cd3803a0af8525fc25a46a3668)

**Comment by hobbes1069** [comment]
Thanks for the quick response! Did you mean to remove both README.md and LICENSE.md?

**Comment by zeux** [comment]
Neither README.md nor LICENSE.md have been present in any release archives - readme.txt contains the license information and brief summary.
