### ISSUE TITLE
pugixml giving the same address of xml_node for all children at the same level. 

### ISSUE THREAD

**Issue by RavikumarTulugu** [zeux/pugixml#297]
we are seeing, that the address of all the children at the same level are the same, this is hurting our logic as we want to store the addresses of xml nodes for later processing. here is the sample xml we are using and the output.

xml:
<?xml version="1.0"?>
<network>
    <animation clip="idle" flags="loop" />
    <animation clip="run" flags="loop" />
    <animation clip="attack" />
    <?include transitions.xml?>
</network>

code:
#include <vector>
#include <iostream>
#include <string>
#include <map>
#include "pugixml.hpp"
#include "tinyformat.h"
#include <boost/filesystem.hpp>
#include <boost/algorithm/string.hpp>
#include <fstream>
#include <streambuf>
#include <tuple>
#include <algorithm>
#include <cctype>
#include <string>

int main( int ac, char **av )
{
    try {
        std::ifstream t("/home/rk/character.xml");
        std::string str((std::istreambuf_iterator<char>(t)), std::istreambuf_iterator<char>());
        std::string xml = str;
        pugi::xml_document *doc = new pugi::xml_document();
        auto result = doc->load_buffer_inplace ( const_cast <char*> ( xml.c_str() ), xml.size() );
        if ( result.status != pugi::xml_parse_status::status_ok ) {
            throw std::runtime_error ( std::string ( std::string( "Error parsing the xml: " )
                        +
                        std::string ( result.description() ) ));
        }
        std::cerr<<" children: " << std::endl;
        std::cerr<<" --------: " << std::endl;
        for ( pugi::xml_node_iterator it = doc->first_child().begin(); it != doc->first_child().end(); ++it ) {
            pugi::xml_node *element = &(*it);
            std::cerr << " type : " << element->name() 
                << " name : " << element->attribute("clip").as_string() 
                << " address : " << element 
                << std::endl;
        }
        std::cerr<<" --------: " << std::endl;
        return 0;
    } catch ( std::exception &ex ) {
        std::cerr<< " main exited with exception : " << ex.what() << std::endl;
        return -1;
    }
}

output: 
children: 
 --------: 
 type : animation name : idle address : 0x7ffde2386cc0
 type : animation name : run address : 0x7ffde2386cc0
 type : animation name : attack address : 0x7ffde2386cc0 <------ i was expecting different

**Comment by zeux** [comment]
```
pugi::xml_node *element = &(*it);
```

This code gives you an address of the node handle that's stored on the stack - so you'll get the same address that doesn't really relate to node's position in a tree or node's identity. It's effectively the same as `&it` (conceptually).

xml_node objects are handles that wrap the internal pointers to node data. Ideally you should just work with them directly - copying them is basically free, so if you want to store them for later processing just store the objects themselves, e.g. in a `std::vector<pugi::xml_node>`.

For rare occasions where you *have* to have a pointer (for example you have a C ABI boundary that only works with pointers), you can use `xml_node::internal_object()` to get an internal pointer to node representation, and then create an xml_node wrapper from it - please note that I'm only mentioning for completeness, the use cases for this are very rare and it's very likely that in your case working with xml_node directly is the right answer.

**Comment by RavikumarTulugu** [comment]
hi , thanks for a wonderful explanation,  there is no way to store references, so we store pointers, after going through the  code more exhaustively, i found out that the xml_node is a wrapper over the actual pointer, we will use xml_node::internal_object as pointers. Thanks
