### ISSUE TITLE
Possibility to use a configurable number of spaces instead of tabs

### ISSUE THREAD

**Issue by griffin-j** [zeux/pugixml#304]
It would be nice if there was the option to and indents using an optional number of spaces instead of the current hard-coded tabs.

**Comment by zeux** [comment]
You can already do this by passing a different parameter `indent` to node output functions - e.g. passing a string with 4 spaces will use that instead of tabs.

**Comment by griffin-j** [comment]
Great!  Thank you.  Sorry, I missed that it was already possible.
