### ISSUE TITLE
pugixml.cpp facing issue in Checkmarx Scan 

### ISSUE THREAD

**Issue by HimNG** [zeux/pugixml#308]
in Checkmarx Scan, It is showing "Improper Null Termination" high issue in pugixml.cpp Line No 7689. 

`

			void* result = allocate(new_size);
			if (!result) return 0;

			// we have a new block
			if (ptr)
			{
				// copy old data (we only support growing)
				assert(new_size >= old_size);
				memcpy(result, ptr, old_size);`

in Checkmarx description, " The buffer result does not have a null terminator.  Any subsequent operations on this buffer that treat it as a null-terminated string will result in unexpected or dangerous behavior."

in "memcpy(result, ptr, old_size);`" result has new_size allocation but we are taking old_size length to copy. and old_size is always greater than the new_size.

**Comment by zeux** [comment]
> The buffer result does not have a null terminator. Any subsequent operations on this buffer that treat it as a null-terminated string will result in unexpected or dangerous behavior

I believe Checkmarx is getting confused. There's only one callsite where the data here is a string data, and it looks like this:

```
char_t* result = static_cast<char_t*>(alloc->reallocate(_uses_heap ? const_cast<char_t*>(_buffer) : 0, (target_length + 1) * sizeof(char_t), (result_length + 1) * sizeof(char_t)));
```

Here we reallocate the string specifying the size *including* the null terminator, and memcpy copies that over to the new buffer.

> result has new_size allocation but we are taking old_size length to copy. and old_size is always greater than the new_size.

Did you mean "less or equal"? It's intentional that we copy the old data to the new block after reallocation - as noted in the assert & comment, reallocate only support buffer growing.

So I believe this is a false positive, but I'm not sure what the best way is to silence this.

**Comment by HimNG** [comment]
`Did you mean "less or equal"?`

correct. less only.

`So I believe this is a false positive`

this is where I am getting confused. I guess Checkmarx not talking assert into consideration and giving error on basis of memcpy only.

**Comment by HimNG** [comment]
@zeux   :
one small query , 
do impl::xml_memory::allocate/alloc->reallocate initialize memory with some default value(0) or not?

**Comment by zeux** [comment]
No - none of them initialize memory with default value. It's expected that the caller does this. For example, in the string reallocation call site, you can see the following code:

```
				// allocate new buffer
				char_t* result = static_cast<char_t*>(alloc->reallocate(_uses_heap ? const_cast<char_t*>(_buffer) : 0, (target_length + 1) * sizeof(char_t), (result_length + 1) * sizeof(char_t)));
				if (!result) return;

				// append first string to the new buffer in case there was no reallocation
				if (!_uses_heap) memcpy(result, _buffer, target_length * sizeof(char_t));

				// append second string to the new buffer
				memcpy(result + target_length, o._buffer, source_length * sizeof(char_t));
				result[result_length] = 0;
```

Which relies on reallocate to copy existing contents, and then proceeds to memcpy + null-terminate the rest of the buffer, effectively filling all of it with valid data.

**Comment by HimNG** [comment]
@zeux. 
Please check below instance  in pugixml.cpp( version 1.10) . 
**1st instance at line number 12390.** 
```
char_t* copy = static_cast<char_t*>(impl::xml_memory::allocate(size));
memcpy(copy, value, size);
```
Here 'copy' variable is of 'size' size and we are copying 'size' length. Here how we are ensuring 'copy' to be null terminated. Is  source memory 'value' is already null terminated?

**2nd instance at line number 12186.**
```
xpath_node* storage = (size_ <= 1) ? _storage : static_cast<xpath_node*>(impl::xml_memory::allocate(size_ * sizeof(xpath_node)));

memcpy(storage, begin_, size_ * sizeof(xpath_node));
```

Here 'storage' variable is of 'size_ * sizeof(xpath_node)' size and we are copying 'size_ * sizeof(xpath_node)' length. Here how we are ensuring 'storage' to be null terminated properly.
Is  source memory 'begin_' is already null terminated?

**Comment by zeux** [comment]
1st instance:
> Is source memory 'value' is already null terminated?

Yes. You can see how `size` is computed to make sure of that:

```
		size_t size = (impl::strlength(value) + 1) * sizeof(char_t);
```

2nd instance:
> Here how we are ensuring 'storage' to be null terminated properly.

In this case memory isn't null terminated and doesn't need to be - null termination only applies to string data (1st case). In this case we're allocating arrays of xpath_node objects and don't need any special sentinel value.
