### ISSUE TITLE
Setting text of node

### ISSUE THREAD

**Issue by secondVISION** [zeux/pugixml#31]
Hey, I'm trying to set the value of a node but I can't get it to work.

I have a file:
    \<config> 
          \<info/>
            \<test>\</test>
    \</config>

When I try to set either of these to a value it won't work.
I've tried the following:
pugi::xml_node tagNode = mDoc.child("config").child(info);
	tagNode.append_child(pugi::node_pcdata);
	tagNode.first_child().set_value("value");

or:
	tagNode.text().set("value");

**Comment by zeux** [comment]
This code works:

```c++
#include "pugixml.hpp"
#include <iostream>

int main()
{
	pugi::xml_document doc;
	doc.load_string("<config><info/><test></test></config>");

	pugi::xml_node tagNode = doc.child("config").child("info");
	tagNode.text().set("value");
	
	doc.save(std::cout);
}
```

Can you provide a complete code snippet that does not work?

Note: info is not quoted in your example; it's possible you're accidentally using an info variable declared elsewhere in the scope.

**Comment by secondVISION** [comment]
Hey, info should have been quoted indeed (typo).
I tried it using your 2 llines and I guess I did something wrong because it's working now.
Thanks!
