### ISSUE TITLE
[question] what xpath_value_type for tokenize xpath function?

### ISSUE THREAD

**Issue by tuananh** [zeux/pugixml#312]
I would like to implement this `tokenize` function but its return an array and `xpath_value_type` doesn't have one that seem fit for this purpose.

for this, i would have to create a new enum entry for it right?

https://www.w3.org/TR/xpath-functions/#func-tokenize

**Comment by zeux** [comment]
There's no existing value type for an array of strings - this is probably non-trivial because it requires adding this type everywhere, including allocation, and probably extending various operations for that type (comparison, etc).
