### ISSUE TITLE
Attribute value without quote

### ISSUE THREAD

**Issue by yanming-zou** [zeux/pugixml#323]
Hi,

First thanks for your great work.
I met a problem that pugixml does not support data format like below
<Data x=0.172109 y=0.392026 z=9.504243/>
It seems like some single quote or double quotes must be added.
I have some xml created by TinyXML and wrote in the format as above without quotes and I want to change to pugi as my tool to process XML files.
What is you suggestion to deal with these cases?

Best
Yanming

**Comment by zeux** [comment]
Can you attach the document that you're having trouble with? I don't see anything in the issue.

**Comment by yanming-zou** [comment]
One line of the file is as below
<Data x=0.095616 y=0.296410 z=9.580735 timestamp='1573020286534111005'/>

**Comment by yanming-zou** [comment]
It seems like the github filters out xml format lines and files. I uploaded it as a txt file.
[sample.txt](https://github.com/zeux/pugixml/files/4100940/sample.txt)

**Comment by zeux** [comment]
Ah - I see. Unquoted attribute values aren't standard; they occasionally come up in context of HTML, e.g. https://github.com/zeux/pugixml/issues/106.

While supporting these isn't too hard in principle, in practice doing this without compromising performance requires specializing attribute conversion function which as it stands is the most complex part of the parser. So I don't think pugixml should support this natively.

I would suggest using a tool like tidy (https://linux.die.net/man/1/tidy) to convert the files into standard XML that can be parsed.
