### ISSUE TITLE
Add Conversion of Child values not just for attributes.

### ISSUE THREAD

**Issue by haseeb-heaven** [zeux/pugixml#327]
There is option to convert data type for XML **atttributes** but there is no option to convert child values to _int,float_ etc.
```
		cout << node.child_value().as_int(); //Error as_int() only for attributes.
		int id = node.attribute("ID").as_int(); //Success.
```
How to convert child nodes values to int,float etc from String?

**Comment by zeux** [comment]
xml_node::text() supports this.

**Comment by haseeb-heaven** [comment]
> xml_node::text() supports this.

Can you show any example ?

**Comment by zeux** [comment]
https://pugixml.org/docs/manual.html#access.text

**Comment by haseeb-heaven** [comment]
> https://pugixml.org/docs/manual.html#access.text

thanks for reply
