### ISSUE TITLE
xpath with variables - crashes when variables need type conversion

### ISSUE THREAD

**Issue by tadamovsky** [zeux/pugixml#328]
xpath with variables - crashes when variables need type conversion.
For example xpath like this:
number($var1) = number($var2)
will crash if either var1 or var2 is not number.
This happens because the code in the following functions:
eval_number, eval_string, eval_boolean
only return value if var does not need conversion, causing the crash after it.
For example,		double eval_number(const xpath_context& c, const xpath_stack& stack)
```
			case ast_variable:
			{
				assert(_rettype == _data.variable->type());
				if (_rettype == xpath_type_number)
					return _data.variable->get_number();
			}
```
I changed it like below:
```
			case ast_variable:
			{
				assert(_rettype == _data.variable->type());

				switch (_rettype)
				{
				case xpath_type_boolean:
					return _data.variable->get_boolean() ? 1 : 0;
				case xpath_type_number:
					return _data.variable->get_number();
				case xpath_type_string:
					return convert_string_to_number(_data.variable->get_string());
				case xpath_type_node_set:
				{
					const xpath_node_set & ns = _data.variable->get_node_set();
					xpath_allocator_capture cr(stack.result);
					return ns.empty() ? gen_nan() : convert_string_to_number(string_value(ns.first(), stack.result).c_str());
				}
				default:
					assert(false && "Wrong expression for return type number"); // unreachable
					return 0;
				}
			}
```

And similarly other 2 functions. 
Verified it is working after the change.
Thank you.

**Comment by zeux** [comment]
So I've just added a test for the conversion (https://github.com/zeux/pugixml/commit/85a39b955d353b4db3bafc044b01fbdac43e5183) and it passes. I don't quite understand the problem.

Note that `ast_variable` is the last statement before the `default`. When the type mismatches, it intentionally falls through to `default` label which handles the type conversion. Can you share the source for `pugixml.cpp` that you are using?

**Comment by tadamovsky** [comment]
OK sorry it was my bug, I added my own xpath function as the last case in the switch (after ast_variable), it caused the bug as ast_variable MUST be the last before default, otherwise it will fall to the case after it (the function I added).
I think some comment is needed there that ast_variable must be last, as it is somewhat confusing...
Thank you.

**Comment by zeux** [comment]
> I think some comment is needed there that ast_variable must be last, as it is somewhat 

Yeah, I added the comment in master to highlight the fall through a bit more.
