### ISSUE TITLE
bug in escaped text

### ISSUE THREAD

**Issue by fobrs** [zeux/pugixml#332]
I have the following value in an attribute:
`<text id="t00X00Y-N">`
This will be escaped as:
` &lt;text id=&quot;t00X00Y-N&quot;>`

Watch the last `'>'` which is not escaped as `&gt;`

**Comment by fobrs** [comment]
Ok, sorry, it is not a bug. `'>'` is allowed unescaped in attribute values. But I'm busy replacing msxml6 with pugixml, and msxml6 escapes `'>'` in attribute values. 
I need to have both api's generate exactly the same textual output...

**Comment by zeux** [comment]
Yeah, pugixml intentionally doesn't escape `>`, see #272. Because of the existing profileration of escape flags I'd like to keep this as is, however if you really need to escape it you could patch pugixml.cpp by changing 1 to 3 on line 1875 in declaration of `chartypeex_table`:

```
		24, 24, 24, 24, 24, 24, 24, 24,    24, 24, 0,  0,  3,  0,  1,  0,     // 48-63
```
