### ISSUE TITLE
How could I get files and nodes' length? 

### ISSUE THREAD

**Issue by JackStig** [zeux/pugixml#336]
Thanks for this amazing xml parser and thanks for all the contributers!I'm new to cpp and I'm working on a firmware update system.I use "char* node_to_buffer(pugi::xml_node node, char* buffer, size_t size)"(samples/save_custom_writer.cpp) to convert node to string.The question is:How could I get files' or nodes' length?
It would be great, if this function would be part of the public API in order to make it easier to do those stuff! (They must be existent, but I haven't understood / found the location in the source where this function happen).

**Comment by zeux** [comment]
Please check `node_to_buffer_heap` in that example - the way it works is that it does two passes over the tree, one to compute the total size needed, and one to print the data.

Alternatively you could use `xml_string_writer` from the same sample - it's easier to use, but it requires STL support and can reallocate heap more aggressively - unsure what the constraints are for your software, so don't know if you can use that instead.

**Comment by JackStig** [comment]
Thank you for your reply! I will try both methods tomorrow.Hope it will work on my system.
