### ISSUE TITLE
Null pointer

### ISSUE THREAD

**Issue by besabasr** [zeux/pugixml#339]
Hi,

Could ._root end up being NULL, making context._root->first_child unreliable?

https://github.com/zeux/pugixml/blob/5e64076af9691ce8100aedf7a61cb338f2596151/src/pugixml.cpp#L6268

if so can it please be NULL-checked to prevent it?

**Comment by zeux** [comment]
No:
https://github.com/zeux/pugixml/blob/5e64076af9691ce8100aedf7a61cb338f2596151/src/pugixml.cpp#L6246

**Comment by besabasr** [comment]
Somehow the static-analysis placed the execution of root() here:

https://github.com/zeux/pugixml/blob/5e64076af9691ce8100aedf7a61cb338f2596151/src/pugixml.cpp#L6244

After the null-check here:

https://github.com/zeux/pugixml/blob/5e64076af9691ce8100aedf7a61cb338f2596151/src/pugixml.cpp#L6246

This made probable xml_node()._root get a null value, but I didn't go back to the original code, my bad!

Thank you for checking!

**Comment by besabasr** [comment]
Hey,

Other potential issues with null-checks please, 

1.- Could doc->_root be null at this point?
https://github.com/zeux/pugixml/blob/5e64076af9691ce8100aedf7a61cb338f2596151/src/pugixml.cpp#L7079

The analyser is complaining there is no null-check before this dereference, only until,
https://github.com/zeux/pugixml/blob/5e64076af9691ce8100aedf7a61cb338f2596151/src/pugixml.cpp#L7098

2.- Same thing with other->first_child here,
https://github.com/zeux/pugixml/blob/5e64076af9691ce8100aedf7a61cb338f2596151/src/pugixml.cpp#L7052

Null-check only,
https://github.com/zeux/pugixml/blob/5e64076af9691ce8100aedf7a61cb338f2596151/src/pugixml.cpp#L7101


3.- Could !contents in this line evaluate to true and size to false?
https://github.com/zeux/pugixml/blob/5e64076af9691ce8100aedf7a61cb338f2596151/src/pugixml.cpp#L4702

If so, tracing-back from convert_buffer(), data, until process(), there data would be explicitly dereferenced 
https://github.com/zeux/pugixml/blob/5e64076af9691ce8100aedf7a61cb338f2596151/src/pugixml.cpp#L1694

Is it possible to use a form of conditional check before dereferencing for the above?

**Comment by zeux** [comment]
1. xml_document::_root is never null, so none of these pointers can be NULL

2. Same as 1

3. Yes, it's possible for contents to be NULL and size to be 0. However, in this case the while loop in process (one line above the one you quoted) will not execute, because the size is 0.
