### ISSUE TITLE
Local Array Index possibly out of bounds

### ISSUE THREAD

**Issue by besabasr** [zeux/pugixml#340]
Hi,

If 'writer' is passed as argument '$0->bufsize' [4,2048] to function 'write_buffer' here,

https://github.com/zeux/pugixml/blob/5e64076af9691ce8100aedf7a61cb338f2596151/src/pugixml.cpp#L3981

Could 4..2048 be the only possible index values to access array 'array.buffer' (size=2048) while calling 'write_buffer?'

this->buffer (size=2048) is used here,

https://github.com/zeux/pugixml/blob/5e64076af9691ce8100aedf7a61cb338f2596151/src/pugixml.cpp#L3773

**Comment by zeux** [comment]
Sorry, I'm not sure I follow this - there's a range check inside write_buffer function that should prevent out of bounds index access.
