### ISSUE TITLE
Possible division by zero

### ISSUE THREAD

**Issue by besabasr** [zeux/pugixml#341]
Hi,

Could this be a division by zero?

https://github.com/zeux/pugixml/blob/5e64076af9691ce8100aedf7a61cb338f2596151/src/pugixml.cpp#L10473

When not entering the loop below because it != ns.end() is false

https://github.com/zeux/pugixml/blob/5e64076af9691ce8100aedf7a61cb338f2596151/src/pugixml.cpp#L10529

**Comment by zeux** [comment]
Sure, there are many conditions where the right hand side here can evaluate to zero. The XPath specification explicitly declares that the arithmetic follows IEEE754 rules - division by zero is valid and produces Infinity (or NaN).
