### ISSUE TITLE
umlaute in pcdata

### ISSUE THREAD

**Issue by pamapa** [zeux/pugixml#342]
Is there a way to special encode umlaute (öäü, ...) in pcdata when printing?
```
ö -> &#246;
```

Something like python is doing:
```
import xml.etree.cElementTree as ET
root = ET.Element("root")
doc = ET.SubElement(root, "doc")
ET.SubElement(doc, "node").text = "Hello Wö"
tree = ET.ElementTree(root)
tree.write("test_pcdata_python.xml")
```
gives:
```
<root><doc><node>Hello W&#246;</node></doc></root>
```

With pugixml gives (flags=0, encoding=auto):
```
...
x.append_child(pugi::node_pcdata).set_value(tmp.c_str());
doc.print(buf, "", 0);
```

```
<root><doc><node>Hello Wö</node></doc></root>
```

**Comment by pamapa** [comment]
Would be cool to have a special flag to do something like this:

```
std::string xmlEncodePcData(const std::string& pcdata)
{
    std::ostringstream buf;
    for (size_t i = 0; i < pcdata.length();) {
        auto ch = pcdata[i];
        int cplen = 1;
        if ((ch & 0xf8) == 0xf0) cplen = 4;
        else if ((ch & 0xf0) == 0xe0) cplen = 3;
        else if ((ch & 0xe0) == 0xc0) cplen = 2;
        if ((i + cplen) > pcdata.length()) cplen = 1;

        if (cplen == 1) {
            switch (ch) {
                case '&' : buf << "&amp;"; break;
                case '<' : buf << "&lt;"; break;
                case '>' : buf << "&gt;"; break;
                default:
                    // handle control codes
                    if (((ch >= 0x00) && (ch <= 0x1f) && 
                         (ch != 0x09) && (ch != 0x0d) && 
                         (ch != 0x0a)) || (ch == 0x7f)) {
                            buf << '.';
                    } else
                        buf << ch;
                    break;
            }
        } else {
            unsigned int res = static_cast<unsigned char>(ch & (0xff >> (cplen + 1))) << ((cplen - 1) * 6);

            size_t j;
            int len;
            for (j = 1, len = cplen -1; len; --len) {
                res |= (static_cast<unsigned char>(pcdata[i+j]) - 0x80) << ((len - 1) * 6);
            }
            buf << "&#";
            buf << res;
            buf << ";";
        }

        i += cplen;
    }

    std::string encoded = buf.str();
    return encoded;
}
```

**Comment by pamapa** [comment]
The function `text_output_escaped` needs to be extend, i am not 100% sure what would be the best approach.

**Comment by pamapa** [comment]
In the meantime i have found a working solution for gerbera. I did simply miss to add:
```
<?xml version="1.0" encoding="UTF-8"?>
```

So the correct execution path depends on the encoding. I still think it my merge request will make sense for other people and maybe as fallback even for gerbera (quirky devices).

**Comment by pamapa** [comment]
Python with `encoding="utf8"`:
```
import xml.etree.cElementTree as ET

root = ET.Element("root")
doc = ET.SubElement(root, "doc")
ET.SubElement(doc, "node2").text = "Hello W2 öüä"

tree = ET.ElementTree(root)
tree.write("test_pcdata_python.xml", encoding="utf8")
```

produces
```
<?xml version='1.0' encoding='utf8'?>
<root><doc><node2>Hello W2 öüä</node2></doc></root>
```

**Comment by pamapa** [comment]
Was to optimistic, i already have found a quirky device: BubbleUPnP. We need that patch...

**Comment by brandl-muc** [comment]
Since you only gave incomplete examples it's hard to tell if you already do this.
So, does it work if you write proper UTF-8 to your document? (eg ö = `0xc3 0xb6`) Not ISO-8859-15 or Windows-1252...

**Comment by pamapa** [comment]
Thanks for helping. I give you more context. Gerbera i an open source DLNA server. You can find it here https://github.com/gerbera/gerbera. It is using pugixml as internal xml handling libs for reading and writing. However its a little bit more complicated, it is also using upnp (https://github.com/pupnp/pupnp) for the DLNA stuff. upnp has its own xml lib called ixml.

My current problem is when using pugixml to write/print xml data. Everything is ok when using normal ascii chars. However when using DLNA metadata non ascii, e.g. öäü, e.g. BubbleUPnP does no accept it anymore.

You can see the source code here:
`DIDL-Lite` is created here:
https://github.com/gerbera/gerbera/blob/master/src/upnp_cds.cc#L108
The response is converted into string + into ixml here:
https://github.com/gerbera/gerbera/blob/master/src/action_request.cc#L93

**Comment by pamapa** [comment]
When i look with Wireshark on the wire i can see e.g. a response like the attached file.
[response.txt](https://github.com/zeux/pugixml/files/4499915/response.txt)

When you look here:
```
0c30   64 61 74 65 26 67 74 3b 0a 26 6c 74 3b 75 70 6e   date&gt;.&lt;upn
0c40   70 3a 61 6c 62 75 6d 26 67 74 3b 4d 6f 6e 73 74   p:album&gt;Monst
0c50   65 72 70 69 6c 7a 65 20 c3 bc 26 6c 74 3b 2f 75   erpilze ..&lt;/u
0c60   70 6e 70 3a 61 6c 62 75 6d 26 67 74 3b 0a 26 6c   pnp:album&gt;.&l
0c70   74 3b 75 70 6e 70 3a 61 72 74 69 73 74 26 67 74   t;upnp:artist&gt
0c80   3b 44 69 65 20 64 72 65 69 20 46 72 61 67 65 7a   ;Die drei Fragez
```
You can see `Monsterpilze ä`, where ä is encoded as `c3 bc`. Should be ok for utf8 stream? Also i made sure to add encoding declaration.

My guess is that BubbleUPnP and other clients do not like that. They like non ascii encoded with #&123;

NOTICE: `DIDL-Lite` is it self an xml and added via pcdata into the response xml.

**Comment by brandl-muc** [comment]
Maybe that was too much context, I'm not going to look at all the code, sorry. ^^
But the gist of it is that you are not using pugi directly, gerbera is. And gerbera is creating files just fine. Lastly BubbleUPnP does not accept the files, so maybe it is also an idea to file a bug there?
(what has ixml to do with the problem?)

By the way, even if you are not German, you can look up octet (byte) sequences  for UTF-8 here: https://www.utf8-zeichentabelle.de/
Doing so for ä yields `0xc3 0xa4`, but `0xc3 0xbc` is ü so you probably sent "Monsterpilze ü"mixed up the input string, and yes it is valid UTF-8 anyhow.

**Comment by pamapa** [comment]
I now did a re-run with gerbera 1.4.0, which is not using pugixml. There its utf8 as well. So the problem must be somewhere else.

[response_1.4.0.txt](https://github.com/zeux/pugixml/files/4499980/response_1.4.0.txt)

**Comment by pamapa** [comment]
argh the problem is somewhere else, i track it down

**Comment by zeux** [comment]
I guess my preference would be to not add format flags to coerce pugixml into escaping all non-ASCII symbols because there are already too many format flags, and it should be entirely correct to use Unicode (and it results in smaller files...). I still don't fully understand why/whether this is necessary.

**Comment by pamapa** [comment]
I agree, it makes no sense to make it the default. On the other hand i do no longer need this. I was tricked **again** and found my issue somewhere else.
I left the pull request and issue, as the code might be for others useful. As other xml libs are offering this kind of encoding. If you do not want to pull it its ok for me.

**Comment by zeux** [comment]
Alright - glad you've got your issue resolved. I will close this for now since I'd rather only add critically important format flags; the PR will stay in the repository history so if this is needed again we can reopen it. Thanks for looking into this!
