### ISSUE TITLE
It seems having a bug in functions: as_uint() and as_ullong().

### ISSUE THREAD

**Issue by haquocviet** [zeux/pugixml#345]
When I intentionally read a negative integer from a XML file via as_uint() and as_ullong(), regardless any negative integer, those functions always return 0. 
I think they have a bug internally.

**Comment by brandl-muc** [comment]
Hey, have a look at the [documentation](https://pugixml.org/docs/manual.html#access.attrdata):
_In case the input string contains a non-numeric character sequence or a number that is out of the target numeric range, the result is undefined._
Hard to call that a bug. ;)
I don't know what you expected to get, but 0 instead of some big positive number seems the better choice to me.

**Comment by zeux** [comment]
The current implementation of the as_ functions clamps the input to the valid range intentionally; so e.g. an integer too large to fit into an unsigned int will be clamped to UINT_MAX as a result of as_uint(), and similarly for negative integers they are clamped to 0. Documentation doesn't reflect this but it probably could.

The clamping behavior - in my mind - is better than wrapping around. If you want a wraparound behavior you can use as_llong() or as_int(), followed by a cast.

**Comment by haquocviet** [comment]
In the C/C++ world, an integer can be legally represented in a negative or positive number. 
Many places mention about this, e.g. book "C++ Primer Plus" notes that:

> "In C++ it is perfectly legal to assign a negative number to an object with unsigned type. The result is the negative value modulo the size of the type".

I think your library should leave clamping to the callers, if they really need clamp they should do themselves, otherwise, as_uint() and as_sllong() just return numbers with casting to unsigned only.
Example: With input: "<int_>-1</int_>", child("int_").as_uint() returning "4,294,967,295‬" make more sense than returning "0", right?.

**Comment by zeux** [comment]
> I think your library should leave clamping to the callers,

You can *NOT* clamp as a caller. There's no type that `as_ullong` can return that would simultaneously preserve large positive values and large negative values, allowing the caller to clamp.

> Example: With input: "<int_>-1</int_>", child("int_").as_uint() returning "4,294,967,295‬" make more sense than returning "0", right?.

I don't see why this is true.

**Comment by zeux** [comment]
(again, I will note that if you really want a signed value returned as an unsigned value mod 2^K you can use as_llong/as_int instead)
