### ISSUE TITLE
Cannot get Chinese from ”PUGI__FN const char_t* xml_node::value() const”

### ISSUE THREAD

**Issue by GitHubXiaofei** [zeux/pugixml#346]
When I enable "#define PUGIXML WCHAR MODE", I still cannot get Chinese by "pugis s const char_t* xml_node::value() const"。
like this
    const char_t* value = node.value(); // node is "TAG" but value = “” 
but if i
    const char_t* value = node.parent().child_value(L"TAG");
it works, Value is what it should be.

**Comment by zeux** [comment]
`node.value()` will be always empty if the node is an element node. Please refer to https://pugixml.org/docs/manual.html#dom.tree for the DOM structure.

To get the PCDATA child value from the node, you can use `node.child_value()` (without argument), or `node.text().get()`.

**Comment by GitHubXiaofei** [comment]
ok, thanks
