### ISSUE TITLE
 error C2440: 'return': cannot convert from 'bool' to 'pug::xml_attribute

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [zeux/pugixml#347]
When compiling with Visual Studio 2019 Prof. 16.5.4 with C/C++/Language/Conformance mode set to Yes (/permissive-) I get the error C2440: 'return': cannot convert from 'bool' to 'pug::xml_attribute in line 3471, 3485 and 3499. 
It should be nullptr or xml_attribute() instead of false?

**Comment by zeux** [comment]
What version of pugixml is this? The latest file from master compiles fine for me in VS 2019 16.6.0 preview 3 with /permissive-, and the line numbers noted above don't seem to match.

**Comment by zeux** [comment]
I'm going to assume this is either fixed in the latest VS or fixed in the latest pugixml. Feel free to provide extra information and reopen this otherwise.
