### ISSUE TITLE
can i delete xml file right after loading it with load_file() ?

### ISSUE THREAD

**Issue by easydsp** [zeux/pugixml#356]
First I would like to thank the developer so much for this super helpful library.
Second I don't know whether I can put the question here. If not, please understand I'm a newbie for this site.

I have a question. 
Somehow I need to delete xml file right after loading.
Can I delete xml file right after loading it by load_file() function ?
I tried. Sometimes xml file is deleted right away. Sometime it is deleted after ~20 seconds. 
Is there a way to delete xml immediately all the time ?

Thanks very much in advance.

**Comment by zeux** [comment]
> Somehow I need to delete xml file right after loading.
> Can I delete xml file right after loading it by load_file() function ?

Yes. After `load_file` returns, the file handle to the file is closed, and you should be able to delete the file without issues.
If you see any delays in the file being deleted, I suspect this doesn't have much to do with pugixml (e.g. maybe this is on a networked filesystem that is caching the directory structure or something else along the same lines).

**Comment by easydsp** [comment]
Thanks zeux so much for the prompt reply. 
It helps a lot.
