### ISSUE TITLE
to avoid escaping special character for password node in xml ,how to declare CDATA tag for password node in c++ by using pugixml libraries,how to read userinput for cdata nodes in c++

### ISSUE THREAD

**Issue by vineelkumar1990** [zeux/pugixml#358]
Requirement is on login web page , to avoid escaping special character for password node in xml ,how to declare CDATA tag for password node in c++ by using pugixml libraries.

ex:
pugi::xml_node Password =  inputMsg.child("Password"); 
			           Password.append_child(pugi::node_cdata).set_value("%s");

**Comment by vineelkumar1990** [comment]
@zeux 

could you please help me on my query

thanks in advance

**Comment by zeux** [comment]
```
Password.append_child(pugi::node_cdata).set_value("password");
```

Is the correct answer.
