### ISSUE TITLE
Wrong DLLExport declaration for static builds

### ISSUE THREAD

**Issue by julianxhokaxhiu** [zeux/pugixml#359]
Hi,

I'm building your library as a static one, but I noticed all of your APIs are declared as `dllexport` which actually is not required ( see https://github.com/zeux/pugixml/blob/master/CMakeLists.txt#L105 ).

I think you need to patch that line to something like `$<$<CXX_COMPILER_ID:MSVC>:PUGIXML_API=__fastcall>)`.

Any better suggestion is welcome, as long as the library does not export when built statically :)

Thank you in advance!

//EDIT: I did try a personal patch by removing entirely that block and it works just fine as well. Using MSVC latest with `CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded`

**Comment by zeux** [comment]
Yes, you're correct. I think the right solution here is to remove the line you quoted (and 2 lines above it obviously) altogether. Feel free to submit a PR, otherwise I'll fix it in the next couple of days.

**Comment by julianxhokaxhiu** [comment]
Done :) Thank you!
