### ISSUE TITLE
Issue with translate() when trying to convert character to empty character

### ISSUE THREAD

**Issue by Willux** [zeux/pugixml#36]
So I have a string "0000007555" and I try doing
```
std::string xpath = "translate('0000007555', '0', '')";
pugi::xpath_query query(xpath.c_str());
std::cout << query.evaluate_string(doc) std::endl; // Assume doc is declared and the XML is loaded.
```

. The output I get is something really funky: "755507555". However, when I change the 'to' variable to a non-empty string, translate() works fine.

**Comment by zeux** [comment]
Wow, this is a really unfortunate bug. Thank you for reporting!

This is a regression introduced in 1.5. The string was always zero-terminated internally by translate()/normalize-space() but evaluate_string() disregarded content after the first null terminator.

With some internal restructuring and optimization the length was cached inside the string and never recomputed in translate/normalize-space. What's worse, the unit tests only compared the result using C string comparison so they passed even though implementation returned extra data.

**Comment by Willux** [comment]
Thank you for the fix, @zeux :) It works fine now
