### ISSUE TITLE
How to parse double locale independent?

### ISSUE THREAD

**Issue by fabianbuettner** [zeux/pugixml#362]
Hi,

I am trying to parse the text of a node(\<Offset\>3.5\</Offset\>) as double like this:

```
pugi::xpath_node offset_xpath_node = xml_node.select_node("Offset");
double offset = offset_xpath_node.node().text().as_double();
```

but after that the content of offset is 3. The "locale" command on my machine yields the following output:
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=

How am I able to parse doubles with "," and "." as decimal seperator?

regards,
Fabian

**Comment by zeux** [comment]
pugixml uses `strtod` from standard library to implement as_double currently, so it's indeed locale-dependent. If you need a locale-independent parse and need the locale set to non-C for your application, you'd need to use `as_string()` and parse this yourself, perhaps using `stringstream` and `imbue` from C++.

A simpler solution is probably to call `setlocale (LC_ALL, "C");` first thing in `main()`. Although this should be the default so maybe you're calling setlocale yourself at some point?

**Comment by fabianbuettner** [comment]
Thanks for the replies!
I haven't had the time to check your suggestions, yet.

@zeux maybe one of the libraries I am using is calling setlocale internally.
@brandl-muc yes I do have acess to C++17. I am going to checkout std::from_chars()

**Comment by fabianbuettner** [comment]
@brandl-muc Sorry for the late feedback. I found out that std::from_chars() in gcc 9.3.0 which I am using has no floating point support.

**Comment by brandl-muc** [comment]
@fabianbuettner Sorry to hear that, I wasn't aware that this is still missing in most stdlib implementations.
