### ISSUE TITLE
empty text  filter by select_nodes api ？

### ISSUE THREAD

**Issue by DieYoungWsn** [zeux/pugixml#366]
For example:
`
...
std::string xpath("/aaa/bbb/ccc/ddd/text()");

pugi::xpath_node_set nodes = doc.select_nodes(xpath.c_str());
...
`
If there is empty text in the ddd, the API will filter it out.
Is there any way to ensure that it is not filtered out？

**Comment by zeux** [comment]
By "empty" do you refer to something like this?

`<foo></foo>`

If there's no whitespace between the tags then there's no text node at all here and there's no way to get it to appear. If there's whitespace-only content then by default parser discards it, so XPath query doesn't see it, but you could use `pugi::parse_ws_pcdata` parsing flag and then it should work as expected.
