### ISSUE TITLE
Add a find module for CMake

### ISSUE THREAD

**Issue by seifertm** [zeux/pugixml#37]
Currently, all software packages depending on pugixml and use CMake as a build system like [OpenImageIO](https://github.com/OpenImageIO/oiio) or [OpenShadingLanguage](https://github.com/imageworks/OpenShadingLanguage) have to supply its own `FindPugiXML.cmake` find module. If the find module for pugixml is not installed together with OIIO or OSL, even indirect dependencies need to provide an appropriate cmake module for pugixml.

Working examples of such a module are the ones provided by [OIIO](https://github.com/OpenImageIO/oiio/blob/master/src/cmake/modules/FindPugiXML.cmake) and by [OSL](https://github.com/imageworks/OpenShadingLanguage/blob/master/src/cmake/modules/FindPugiXML.cmake), though both are licensed under BSD.

Is it possible to add a similar find module for CMake based builds to future releases?

**Comment by zeux** [comment]
PRs are welcome.

**Comment by seifertm** [comment]
I missed the fact that pugixml also supports a CMake based build.
Version 1.5 also installs the required package configuration files, so there is no need for a `FindPugiXML.cmake` module.
