### ISSUE TITLE
node like  < node />

### ISSUE THREAD

**Issue by xfcanyue** [zeux/pugixml#371]
begin a node,  right after '<' with a space.   just like <     node /> , it is  error.

**Comment by zeux** [comment]
Space after `<` is always an error; `< node />` isn't valid XML.

**Comment by xfcanyue** [comment]
yes, i know. thank you so much.
i use pugixml to analyzing xml for  a directui designer.  with a scintilla editor.
can you tell me some suggestions, how to reflect modified xml to pugixml immediately in my editor. 
now, i always load_string to rebuild windowui, it's so stupid.

**Comment by zeux** [comment]
If the text changes, you need to reparse it by doing `load_string` or equivalent. If you want to, you could write a function that creates a new document, and then walks through both documents at the same time and only applies changes to the UI based on the difference in nodes,
