### ISSUE TITLE
build pugixml with -DBUILD_SHARED_LIBS=ON doesn't work with mingw

### ISSUE THREAD

**Issue by GChivot** [zeux/pugixml#372]
I try to compile pugixml (https://github.com/zeux/pugixml) with mingw in powershell. The static library works well, but when I try to compile the dll with the commands

cmake -G "MinGW Makefiles" -DBUILD_SHARED_LIBS=ON ..
mingw32-make.exe

, I have the following message :

C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin\windres.exe: C:\\Users\\kafka\\Desktop\\project\\pugixml\\scripts\\pugixml_dll.rc:11: syntax error
C:\Users\kafka\Desktop\project\pugixml\scripts\pugixml_dll.rc:2: fatal error: when writing output to : Broken pipe

cmake version : 3.18 mingw32-make :

GNU Make 4.2.1
Built for x86_64-w64-mingw32
Copyright (C) 1988-2016 Free Software Foundation, Inc.

**Comment by zeux** [comment]
This looks like a problem in .rc file with the define:

```
#ifdef GCC_WINDRES
VS_VERSION_INFO		VERSIONINFO
#else
VS_VERSION_INFO		VERSIONINFO	MOVEABLE IMPURE LOADONCALL DISCARDABLE
#endif
```

I'm not sure which define needs to be used here to detect the mingw version of the resource packer, but I'm happy to merge a PR that fixes this.

**Comment by GChivot** [comment]
You're right. I don't know how to use .rc file but if I replace 

#ifdef GCC_WINDRES
VS_VERSION_INFO		VERSIONINFO
#366 
VS_VERSION_INFO		VERSIONINFO	MOVEABLE IMPURE LOADONCALL DISCARDABLE
#endif 

by 

```VS_VERSION_INFO		VERSIONINFO```

It compiles on my computer. It seems GCC_WINDRES is not defined.

I don't know what is the right way to handle that correctly, but adding 

#ifdef __MINGW32__
#define GCC_WINDRES
#endif


#ifdef GCC_WINDRES
VS_VERSION_INFO		VERSIONINFO
#else
VS_VERSION_INFO		VERSIONINFO	MOVEABLE IMPURE LOADONCALL DISCARDABLE
#endif

correct the issue in my computer.

**Comment by zeux** [comment]
Changing #ifdef GCC_WINDRES to #if defined(GCC_WINDRES) || defined(__MINGW32__) should be a bit safer; if that also works feel free to submit a pull request with the change.

**Comment by jjmccollum** [comment]
I'd like to see this issue fixed myself, so I'd be happy to submit a pull request with this change, if no one else has agreed to do so yet. I will admit, though, that I've never submitted a pull request, so I'm not entirely sure how to go about it. Do I have to get write permission to work on a separate branch for the repo?

**Comment by c72578** [comment]
@jjmccollum Please have a look at e.g. [GitHub Standard Fork & Pull Request Workflow](https://gist.github.com/Chaser324/ce0505fbed06b947d962)

**Comment by jjmccollum** [comment]
@c72578 Thanks for the reference! I've saved this for future reference.

I've forked the repo, made the changes outlined in this issue on a dedicated branch, and submitted a pull request. It looks like the code on my branch passes most of the build and coverage tests, although it slightly fails the codecov/project test (I can't see why).

**Comment by jjmccollum** [comment]
Nevermind that last comment; it looks like all tests are passing now.
