### ISSUE TITLE
Streaming API?

### ISSUE THREAD

**Issue by EmmanuelOga** [zeux/pugixml#375]
More of a question than an issue:

I was reading [this article about parsing a 38GB  XML file](https://news.ycombinator.com/item?id=24863352) and pugixml came to mind, I was wondering if it supported some sort of streaming API?

Thank you!

**Comment by zeux** [comment]
pugixml doesn't provide streaming API; at its core it's a DOM library/parser and as such expects to fit the entire input in memory.

A set of optimizations makes pugixml viable to load very large documents, especially https://pugixml.org/docs/manual.html#dom.memory.compact - but it still requires more RAM than the input document's size.

There are possible workarounds when the input structure is regular/known - some users use pugixml for parsing an XML message stream, using a lightweight scanner (e.g. looking for `</message>` string when that's the outer node that's expected to repeat often), and then passing the short input segment to pugixml parser. That's a reasonable model for some embedded processors.

Beyond that though, there are no plans to support streaming as a first-class feature, as it doesn't fit the scope of the library or the design of the document storage / parser.

**Comment by EmmanuelOga** [comment]
Makes sense, thanks zeux!
