### ISSUE TITLE
in a node, exist same attribute name

### ISSUE THREAD

**Issue by xfcanyue** [zeux/pugixml#379]
is it bug ？

**Comment by tuananh** [comment]
Thats not xml compliant right?

**Comment by xfcanyue** [comment]
eg.  <Button text="1" text="2" />,  it has two attribute text,   maybe pugixml should throw an exception .

**Comment by zeux** [comment]
Please refer to https://pugixml.org/docs/manual.html#loading.w3c; for performance reasons, pugixml doesn't reject documents with attributes that have the same name.
