### ISSUE TITLE
Function to convert doc into string

### ISSUE THREAD

**Issue by hsdk123** [zeux/pugixml#385]
Hi, I was hoping to request a function to convert `pugi::xml_document` into a std::string. This would make it much simpler an interface for saving or sending data through custom paths.

Api example: `std::optional<std::string> pugi::xml_document::save_as_string()`

**Comment by zeux** [comment]
This can be done in two-three lines with iostreams:

```
std::stringstream ss;
doc.save(ss);
std::string str = ss.str();
```

**Comment by hsdk123** [comment]
absolutely great
