### ISSUE TITLE
how to add CR and LF after the declaration node?

### ISSUE THREAD

**Issue by kinbei** [zeux/pugixml#400]
how to add CR and LF after the declaration node? can I add a new option to the format_option?

eg.
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"> ...
```

**Comment by zeux** [comment]
pugixml uses LF for newlines in the output. If you want to use CRLF you can use automatic conversion that `fopen`/`std::ofstream` provide, e.g.

```
std::ofstream out("result.xml");
doc.save(out);
```

will use CRLF on Windows, since the default output mode for ofstream is text.

**Comment by kinbei** [comment]
In this case, I use `pugixml` to parse the *.xml contained in a Excel file    
It turns out that the source string contains "\r\n", but after being modified by pugixml, "\r\n" disappears    
Or, can make the pugi::format_raw option preserve the "original format"?    
eg.

```c++
#include <pugixml.hpp>
#include <iostream>

const unsigned int parse_options = (pugi::parse_default & ~pugi::parse_eol) | pugi::parse_ws_pcdata | pugi::parse_declaration;

int main() {
	pugi::xml_document doc;
	doc.load_string("<?xml version=\"1.0\" encoding=\"UTF - 8\" standalone=\"yes\"?>\r\n<foo bar='baz'><call>hey</call></foo>", parse_options);

	// Output is "<?xml version="1.0" encoding="UTF - 8" standalone="yes"?><foo bar="baz"><call>hey</call></foo>"
	doc.save(std::cout, "", pugi::format_raw);

	// Expected output
	// "<?xml version="1.0" encoding="UTF - 8" standalone="yes"?>\r\n<foo bar="baz"><call>hey</call></foo>"

	std::cout << std::endl;
	return 0;
}
```

**Comment by zeux** [comment]
If you want to preserve the top-level formatting you need to add `parse_fragment` option during parsing to store it in pcdata nodes that will be reproduced during printing.

**Comment by kinbei** [comment]
Now it works. thanks.
