### ISSUE TITLE
WinCE compatiblity: wfopen_s, sprintf_s and _countof, are not available for all plaforms

### ISSUE THREAD

**Issue by LowLevelMahn** [zeux/pugixml#401]
PugiXML: 1.11.0
Compiler: VS2008, WinCE 
Platforms:
  Pocket PC2003
  Windows Mobile 5

i've fixed that adding following lines to the pugixml.cpp

```
// In some environments MSVC is a compiler but the CRT lacks certain MSVC-specific features
#if defined(_MSC_VER) && !defined(__S3E__)

// quick fix - make the compiler older :)
#   if defined( WINCE )
#   if (_MSC_VER == 1500) //MSVS 2008
#       undef _MSC_VER
#       define _MSC_VER 1399 // small 1400
#   endif
#   endif

#	define PUGI__MSVC_CRT_VERSION _MSC_VER
#endif
```

1.8 compiles out of the box

**Comment by zeux** [comment]
Redefining _MSC_VER itself seems wrong but it would make sense to me to set PUGI__MSVC_CRT_VERSION to 1399 for WINCE. Would you mind submitting a pull request to that effect?

**Comment by LowLevelMahn** [comment]
> Would you mind submitting a pull request to that effect?

i'll check your suggestion

still open problem: i can cut of these 3 function for all WINCE builds - checking for the define, but only some WinCE Platforms missing these functions - are there very relevant for speed, quality or something or is the loss just small?

**Comment by zeux** [comment]
I think it’s fine to not use these on any WinCE platforms, the loss is insignificant
