### ISSUE TITLE
Provide some additional xml_node functionalities: null_nodes, this_node

### ISSUE THREAD

**Issue by DeanGrid** [zeux/pugixml#408]
For member variables initialization and return values from functions it might be usefull to be able to have a functionality that gives access to an empty node. 
For instance, sometimes I need if-else if-else  that deals with conditions if a variable containing nodes exist or not or have been correctly initialized. To have an empty xml_node element would be really helpful.

For some specific coding reasons it would also be helpful to have a functionality that allows an xml_node to explicitely return itself and not only childs, e.g. xml_node.this_node().

**Comment by zeux** [comment]
> To have an empty xml_node element would be really helpful.

Does xml_node() not work?

> functionality that allows an xml_node to explicitely return itself and not only childs

If you mean you want to get a copy of the node that has an empty child list then this is impossible due to the lifetime/ownership restrictions as all nodes with data must be attached somewhere in a document.
