### ISSUE TITLE
Node hash values change when using xml_document::reset() to copy the document

### ISSUE THREAD

**Issue by nickdademo** [zeux/pugixml#43]
Is this expected behaviour?
If so, is there a way to do a 1:1 copy which also copies the node hash values?

**Comment by zeux** [comment]
This is expected. It's not spelled out that well in documentation - it says

"If you want to use xml_node or xml_attribute objects as keys in hash-based associative containers, you can use the hash_value member functions. They return the hash values that are guaranteed to be the same for all handles to the same underlying object. The hash value for null handles is 0."

But does not clarify what the behavior is for copies of the node.

Hash value is not stored in the node - and it's not unique, of course. If you want a stable hash value you'd have to compute it in an expensive fashion by printing the contents of the node to a string and hashing that. Or you can write a custom hasher that traverses the children and combines the hash values (which is more efficient but more code to write).

Or maybe you don't really need a hash here :) it depends on what you're trying to do.

**Comment by nickdademo** [comment]
Thanks for the clarification Arseny.

I see that the hash value is derived from the root pointer of the document so it makes perfect sense that it isn't retained during a reset().

I basically want each node to have a unique identifier which I can use to find a specific node after a copy via reset():
```
        typedef struct hash_predicate
        {
            int ref_hash_value;
            bool operator()(pugi::xml_node node) const
            {
                return (node.hash_value() == ref_hash_value);
            }
        };
```
Then:
```
    hash_predicate p;
    p.ref_hash_value = hashValue;
    pugi::xml_node n = referenceDoc->find_node(p);
    if (n)
    {
    }
```

**Comment by zeux** [comment]
Ok, I see. I think there are two good options:

1. Generate a map between nodes in two documents with a simultaneous traversal. E.g.

```
void traverse(std::unordered_map<pugi::xml_node, pugi::xml_node>& map, pugi::xml_node ln, pugi::xml_node rn)
{
    map[ln] = rn;
    for (pugi::xml_node lc = ln.first_child(), rc = rn.first_child(); lc && rc; lc = lc.next_sibling(), rc = rc.next_sibling())
        traverse(map, lc, rc);
}

pugi::xml_document copy;
std::unordered_map<pugi::xml_node, pugi::xml_node> copymap;
copy.reset(*referenceDoc);
traverse(copymap, *referenceDoc, copy);
```

2. If you frequently remove nodes in the copied document, maintaining the map can become cumbersome since you'd have to remove entries from it whenever you remove nodes from the copy; in which case the easiest thing is to generate a unique ID in the original document and store it using an attribute. E.g.

```
unsigned int generateId(pugi::xml_node node, unsigned int id)
{
    node.append_attribute("__uid") = ++id;
    
    for (auto child: node.children())
        id = generateId(child, id);

    return id;
}
```
