### ISSUE TITLE
Some Cmake and INstallation Issues

### ISSUE THREAD

**Issue by gabyx** [zeux/pugixml#44]
Wouldn't it be better if pugixml installes its header

in /usr/local/include/pugixml

instead of just in /usr/local/include
which is not good practice anyway, i think,

(at least under linux)

that means we would change the default installation options in CMAKE
to
CMAKE_INSTALL_INCLUDEDIR  = include/pugixml

I have alsoa  FIndSCript which I could add for CMAKE

**Comment by zeux** [comment]
I'm not sure what is and what is not a good practice. zlib, libintl, ncurses and libiconv all install into /usr/include/ directly.

Regardless, changing that will force people who use the CMakeLists.txt to change it back - it's used by several Linux distributions as the building script (occasionally with minor patches), so changing this will either break the compatibility of those packages or force the package maintainers to patch.

Regarding the find script, I understand how it would work on Linux - there are some projects that use something like this https://github.com/imageworks/OpenShadingLanguage/blob/master/src/cmake/modules/FindPugiXML.cmake - how would it work on Windows? I'm not very familiar with CMake.
