### ISSUE TITLE
Veracode scan complains the malloc is not checked for return value.

### ISSUE THREAD

**Issue by KrishnaRLolage** [zeux/pugixml#440]
https://github.com/zeux/pugixml/blob/9e382f98076e57581fcc61323728443374889646/src/pugixml.cpp#L186

We use [Veracode](https://analysiscenter.veracode.com/) for scanning our mobile application. It complains the following when pugixml lib is used.

**The result of this call to malloc() is not checked for success before being used. This can result in application instability or crashing if memory is not available.**

Can this be fixed?

**Comment by zeux** [comment]
There's nothing to fix here - feel free to submit a bug report for Veracode. This code is perfectly valid; the check for null pointer is located in the callers of the allocate callback. There's nothing sensible that the `default_allocate` function can do.

**Comment by brandl-muc** [comment]
We are starting to use Veracode, the thing is that they are not doing
static code analysis but are doing a data flow analysis using the binaries.
So it is IMHO (not at all an expert with their tools) likely that one of
the callers of default_allocate() is not checking the result  for nullptr.
Easiest way to check this is manual code inspection I guess. Maybe
something OP could do?
(apart from that I second your nothing sensible statement)


Arseny Kapoulkine ***@***.***> schrieb am Do., 23. Sept.
2021, 11:59:

**Comment by zeux** [comment]
You can grep for `xml_memory::allocate` - the result is always getting checked for 0. I suspect their dataflow analysis gets confused because of a function pointer, the allocation callback is replaceable and `default_allocate` is just, well, the default.
