### ISSUE TITLE
Need help rejecting invalid entity expansions

### ISSUE THREAD

**Issue by ThirtyNineWinks** [zeux/pugixml#444]
The classic billion laughs attack relies on entity declarations repeatedly expanding entities. I'm glad you can't do that, but I would like to have you give an error on the entity that didn't get expanded. That is, with this snippet:
```
   :
 <!ENTITY lol7 "&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;">
 <!ENTITY lol8 "&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;">
 <!ENTITY lol9 "&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;">]>
<lolz>&lol9;</lolz>
```
I would like you to report an error on `&lol9;`. Your manual says "... so you can do additional processing later." I cannot detect this error case from someone deliberately writing `&amp;lol9;`. That would expand to look like the error case, but it never intended to expand lol9.

Reporting this error won't even slow down the parser in the normal case. In strconv_escape all the good cases return. All the error cases break, and end up at the bottom of the function, with `return stre;`. All you need to do is give an error there, and you've got it.

**Comment by ThirtyNineWinks** [comment]
(You can't give an error in `strconv_escape`, or in the function that calls it, because you don't actually throw exceptions, but set variables in the class and return the pointer to where the error was. I made the `strconv_escape` return the pointer to the '&', and I made the caller and caller's caller check if `*s=='&'` and give an error. That's lame, and someone else could probably do better.)

**Comment by zeux** [comment]
> I cannot detect this error case from someone deliberately writing &amp;lol9;

If you want to perform custom entity expansion yourself, you need to disable `parse_escapes` during parsing. After this you're free to perform your own unescaping with arbitrary logic, including error handling etc.

**Comment by ThirtyNineWinks** [comment]
I'm perfectly happy with this not being expanded, it's just that Pugi should give an error that it didn't do it.

If course I could turn the option off, and I can write my own xml parser. I'm just saying that it is really easy for you to detect the problem in the source. If I traverse the tree afterwards and find an invalid escape, could I point to the source?
