### ISSUE TITLE
Please support MSVC v143 for NuGet release

### ISSUE THREAD

**Issue by Silver-Fang** [zeux/pugixml#455]
I installed the NuGet release from Visual Studio and selected Dynamic CRT linkage. However, linkage failed for not founding packages\pugixml.1.11.0\build\native\lib\x64\v143\dynamic\Debug\pugixml.lib. Under directory packages\pugixml.1.11.0\build\native\lib\x64, I found it support only to v142 but not v143.
Please update the NuGet release to support MSVC v143, thanks.

**Comment by zeux** [comment]
pugixml 1.12 was published to NuGet just now with support for VS2022 following #468.
