### ISSUE TITLE
Human readable version string

### ISSUE THREAD

**Issue by kelson42** [zeux/pugixml#458]
Currently there is only `PUGIXML_VERSION` in the header. This is maybe good for computers, but does not reflect the real version of libpugixml.

**Comment by zeux** [comment]
I'm not sure what's being asked for here - a human-readable version string is in the top-level comment for all files (https://github.com/zeux/pugixml/blob/master/src/pugixml.hpp#L2); PUGIXML_VERSION can be used to produce any type of version string at runtime.

**Comment by kelson42** [comment]
@zeux I might be wrong, but this is the kind of code I have to write to get `std::string 1.11.4`

```
const unsigned pugixml_major = (PUGIXML_VERSION - PUGIXML_VERSION % 1000) / 1000;
const unsigned pugixml_minor = (PUGIXML_VERSION - pugixml_major * 1000 - PUGIXML_VERSION % 10) / 10;
const unsigned pugixml_patch = PUGIXML_VERSION - pugixml_major * 1000 - pugixml_minor * 10;
std::ostringstream libpugixml_version;
libpugixml_version << pugixml_major << "." << pugixml_minor << "." << pugixml_patch;
libpugixml_version.str();
```

this is not really dev friendly. This is why I have open this ticket.

**Comment by zeux** [comment]
Ok. It sounds like what you are asking for is a way to programmatically display a human-readable version.

It can be done in ~1 line of code:

```
printf("pugixml version: %d.%d.%d\n", PUGIXML_VERSION / 1000, (PUGIXML_VERSION % 1000) / 10, PUGIXML_VERSION % 10);
```

Since it's rare that you need something like this I don't think it needs a special API.
