### ISSUE TITLE
How to query a node with node name contain colon ":" ？

### ISSUE THREAD

**Issue by TRUEJASONFANS** [zeux/pugixml#462]
like a xml:
```
<parameter>
        <:xposi:wei>1.5</:xposi:wei>
        <:yposi:wei>1.5</:yposi:wei>
</parameter
```
and the :xposi or :yposi is not the namespace and just a node name.

**Comment by TRUEJASONFANS** [comment]
I use the pugi::xml_node::selec_nodes("/parameter/:xposi:wei") will return error.

**Comment by brandl-muc** [comment]
Element names must start with a letter or an underscore, see e.g. [here](https://www.w3schools.com/xml/xml_elements.asp).
Hence that's not valid XML.

**Comment by zeux** [comment]
Note that if you *really* need to select this node, you can do it like this:

```
node.select_nodes("/parameter/*[name() = ':xposi:wei']")
```

That said, as noted above this XML is non-standard and as such a better way would be to not use element names that start with a colon.

**Comment by TRUEJASONFANS** [comment]
@zeux  thanks for great support!
