### ISSUE TITLE
Suggestion for performance improvement for Compact mode

### ISSUE THREAD

**Issue by ThirtyNineWinks** [zeux/pugixml#463]
When in compact mode I'm seeing an excellent reduction in memory usage, and even some reduction in run time. (You told me it would cost me run time. I'm glad you are wrong.)

However, it can be made to be even faster. In this code, in `xml_node::attribute`:

```
		for (xml_attribute_struct* i = _root->first_attribute; i; i = i->next_attribute)
			if (i->name && impl::strequal(name_, i->name))
```

The test on `i->name` calls `compact_string<4,2>::operator char_t*`. If that passes, you then call `operator char_t*` again to do the `strequal`. That expansion to a `char*` is moderately expensive. With C++17 you could write that test as:

`    if (const auto* ptr=i->name; ptr && impl::strequal(name_, ptr))`

It would work fine for both Compact and non-compact modes. Alternately, to still work with C++14:

```
    {
        const auto* ptr=i->name;
        if (ptr && impl::strequal(name_, ptr)) ...
```

**Comment by zeux** [comment]
That's a good suggestion; feel free to submit a PR for this and other places. Note that pugixml should compile in C++98 mode (which is validated by CI), but as long as `auto` isn't used it shouldn't be a problem.

**Comment by zeux** [comment]
Other opportunities for the same optimization include xml_node::name(), xml_node::value(), xml_node::previous_sibling(), possibly others.
