### ISSUE TITLE
dereference of a null pointer

### ISSUE THREAD

**Issue by CarCode** [zeux/pugixml#47]
In function void optimize(xpath_allocator* alloc) I get these warnings:
src/pugixml.cpp:9904:5: Access to field '_type' results in a dereference of a null pointer (loaded from field '_right')

src/pugixml.cpp:9939:39: Access to field '_type' results in a dereference of a null pointer (loaded from field '_right')

src/pugixml.cpp:9952:5: Access to field '_type' results in a dereference of a null pointer (loaded from field '_left')

src/pugixml.cpp:9953:6: Access to field '_type' results in a dereference of a null pointer (loaded from field '_right')
Any hint to avoid this please?

Gerhard

**Comment by zeux** [comment]
Please be more specific.

What version of pugixml are you using?
What compiler generates these warnings? (I'm assuming this is clang's static analysis, but what's the compiler version?)

**Comment by CarCode** [comment]
This patch works with Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0
No issues anymore. Thank you.
Gerhard
