### ISSUE TITLE
tests/test_xpath.cpp doesn't build on visual studio using the c++20 standard

### ISSUE THREAD

**Issue by bitrunner** [zeux/pugixml#481]
tests/test_xpath.cpp doesn't build on Visual Studio using the C++20 standard with the following error:

```
../subprojects/pugixml-1.12/tests/test_xpath.cpp(166): error C2039: 'random_shuffle': is not a member of 'std'
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\algorithm(40): note: see declaration of 'std'
../subprojects/pugixml-1.12/tests/test_xpath.cpp(166): error C3861: 'random_shuffle': identifier not found
../subprojects/pugixml-1.12/tests/test_xpath.cpp(195): error C2039: 'random_shuffle': is not a member of 'std'
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\algorithm(40): note: see declaration of 'std'
../subprojects/pugixml-1.12/tests/test_xpath.cpp(195): error C3861: 'random_shuffle': identifier not found
```

I assume this also happens using C++17, but I didn't test that.

The problem appears to be that the silly compiler doesn't define the standard __cplusplus macro correctly.  See https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170 for details on that.  Looks like you've got workarounds for this in pugixml.hpp that use _MSC_VER.  Maybe this also needs something like that?  There's also _MSVC_LANG on VS >= 2015 update 3 which has correct __cplusplus values without requiring /Zc:__cplusplus (which actually fixes __cplusplus values on VS >= 2017 version 15.7).  See https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170 for details on that.

[rant]I have no idea why M$ takes such pride in making everyone that tries to make something cross platform suffer so badly by ignoring standards.[/rant]

**Comment by eli-schwartz** [comment]
@bitrunner, I... genuinely thought we fixed this in Meson long ago, see https://github.com/mesonbuild/meson/pull/10323
