### ISSUE TITLE
bug& paser elements

### ISSUE THREAD

**Issue by 617475jordan** [zeux/pugixml#484]
<?xml version="1.0" encoding="UTF-8"?>
<OpenSCENARIO
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="OpenSCENARIO.xsd">
  <FileHeader revMajor="1" revMinor="0" date="2020-02-21T10:00:00" description="Traffic Jam example" author="ASAM e.V."/>

</OpenSCENARIO>
when the code parsers fileheader , the tools says"ERROR :Exception .. Invalid range in bracket expression"

**Comment by zeux** [comment]
This error message doesn't come from pugixml.
