### ISSUE TITLE
parse and write "&gt;" in attribute

### ISSUE THREAD

**Issue by LukaMod** [zeux/pugixml#485]
Hello, I load a xml file and write to output directly. the attribute value was changed.
input file:
```xml
<note>
<to>Tove</to>
<from>Jani</from>
<heading attr="Don't &lt;forget me&gt; this weekend!">Reminder</heading>
<body>Don't forget me this weekend!</body>
</note>
```

output:
```xml
<?xml version="1.0"?>
<note>
	<to>Tove</to>
	<from>Jani</from>
	<heading attr="Don't &lt;forget me> this weekend!">Reminder</heading>
	<body>Don't forget me this weekend!</body>
</note>
```

**Comment by zeux** [comment]
Unescaped `>` is allowed in attribute values (unlike unescaped `<`) by the XML standard. pugixml tries to produce the minimal encoded output, so it doesn't escape characters that don't need to be escaped.
