### ISSUE TITLE
Can i replace \n line ending with \r\n ?

### ISSUE THREAD

**Issue by LowLevelMahn** [zeux/pugixml#486]
i've replaced an old xml writer with superior pugixml - the only thing that is currently a problem is that the generated xml files lines endings are \n - but i need \r\n (i know its a silly difference) but depending tools based on this

is there a feature to change the line ending?

**Comment by tuananh** [comment]
check this option from the doc. looks like what you need

> format_save_file_text changes the file mode when using save_file function. By default, file is opened in binary mode, which means that the output file will contain platform-independent newline \n (ASCII 10). If this flag is on, file is opened in text mode, which on some systems changes the newline format (i.e. on Windows you can use this flag to output XML documents with \r\n (ASCII 13 10) newlines. This flag is off by default.

**Comment by LowLevelMahn** [comment]
works - thanks
