### ISSUE TITLE
Use stringstream to get xml content to string is simpler

### ISSUE THREAD

**Issue by 474914041** [zeux/pugixml#489]
I want save xml content to string , use stringstream is simpler.
```
pugi::xml_document doc;
doc.load_string("<root>hello,world</root>");

std::stringstream ss;
doc.save(ss, "", pugi::format_raw);  
std::string result = os.str();
```

**Comment by zeux** [comment]
Not sure what this is asking for. If you want a simpler way to print the document into a std::string you can wrap the three required lines into a function.
