### ISSUE TITLE
nuget package

### ISSUE THREAD

**Issue by kreuzerkrieg** [zeux/pugixml#49]
may we have native nugget package for pugi? it is very convenient way to get your thirdparties via nugget repository

**Comment by zeux** [comment]
I looked at creating native NuGet packages and it feels painful. I don't really have time to look into this more closely right now; I'd happily accept package specs and/or build scripts (preferably in PowerShell so I can put them on AppVeyor).

**Comment by igagis** [comment]
I made and uploaded a NuGet package, it is named libpugixml on nuget.org
Pull request: https://github.com/zeux/pugixml/pull/59

**Comment by kreuzerkrieg** [comment]
u r da man!
@zeux , will you adopt and maintain it?

**Comment by igagis** [comment]
@zeux, if you tell me your username on nuget.org I'll add you to the owners of the package, so you'll be able to upload newer versions with same name

**Comment by zeux** [comment]
My username on nuget.org is zeuxcg.

Is "lib" prefix a convention that NuGet packages use? Curious as to why you did not name it pugixml.
I'm happy to upload new versions, the script looks pretty simple!

**Comment by igagis** [comment]
I added you as package owner on nuget.org.

There is no any such naming convention afaik. I added "lib" prefix without reason, just a habit from linux world. You can change name in nuget.autopkg to pugixml and upload to nuget.org with that name. I will remove the libpugixml then to avoid littering the namespace.

Scripts are simple, but in order to run those you have to set up your environment as described here:
http://coapp.org/tutorials/building-a-package.html

**Comment by igagis** [comment]
Ok, I updated the pull request. Now the name is pugixml. Will upload new package to nuget.org in the evening.

**Comment by igagis** [comment]
Uploaded new package to nuget.org, named pugixml

**Comment by zeux** [comment]
I've updated the packaging scripts/description/etc. and uploaded a new version (1.7.0-alpha).

Note that the "1.6.0.1" version that's on NuGet is *not* 1.6 and rather the version built from master recently. I can't remove it from the list so I unlisted it; when 1.7 gets released I'll upload the correct build.

**Comment by zeux** [comment]
The only issue that still remains is debug info - I uploaded pugixml.symbols package built from new nuspec but it's not being picked up in VS - not really sure how all that is supposed to work. I sort of expected the .pdb files to be put in the main package...

**Comment by igagis** [comment]
I'm not VS expert, but my understanding is that you don't need debug symbols for static lib as the symbols are already there in .lib. The .pdb is only needed for .dll, in that case usually there are 3 nuget packages built: one with headers and .lib called pugixml,for example; the other is pugixml.redist which contains .dll; and the third is pugixml.symbols with .pdb.
Since you make a static lib you don't need pugixml.symbols package, only pugixml.

**Comment by zeux** [comment]
That's incorrect. Unlike GCC, MSVC by default stores debug information for object files in .PDB. When you link the final executable several .PDB files get linked together.

There is an old flag, /Z7, that switches debug information storage to .obj (and .lib, of course) files. I'll check if it still works - if it does that's the best approach probably.

**Comment by igagis** [comment]
Also, regarding package version, the convention is that first three numbers are version of the software and the last forth one is the version of the package. In case you make changes to package meta info, like its description etc. without changing the library itself you can increase that forth number to upload new package. So, current versioning 1.7.0-alpha is kind of out of that convention. But ok for now, take this into account when releasing 1.7.0.1

**Comment by zeux** [comment]
pugixml versions are generally in the form major.minor, without .patch. I looked on other packages and did not really see 4 numbers in the version so I thought I'd use major.minor.package.

**Comment by igagis** [comment]
Ok, you probably know VS better than me :) :+1: 
Regarding version examples, here are some:
http://www.nuget.org/packages/libpng/
http://www.nuget.org/packages/zlib/
http://www.nuget.org/packages/freetype2/

you can use always 0 for .patch, I see no problem with that..

**Comment by zeux** [comment]
Yeah, all these packages have the non-NuGet version using major.minor.patch. Actually, I think most packages I see here https://www.nuget.org/packages use major.minor.patch - e.g. the 3rd number is not the package version. I was thinking of just uploading 1.7 as 1.7, honestly, to keep the versions uniform across all distribution channels (e.g. GitHub releases and various Linux packages)...

In most Linux distributions pugixml is distributed with package version is cleanly separated from the library version - e.g. pugixml 1.6-3. Not sure if NuGet allows something like this or not...

**Comment by igagis** [comment]
Since you were able to upload 1.7-alpha, I guess NuGet allows whatever you write in the version field :)

I have just googled and looks like NuGet uses this versioning standard:
http://semver.org/spec/v1.0.0.html

I haven't read it though...

**Comment by zeux** [comment]
I uploaded https://www.nuget.org/packages/pugixml/1.7.0. I'll look into building the nupkg files on AppVeyor but even if this does not work I'll build the packages for future releases.

**Comment by igagis** [comment]
Great!
