### ISSUE TITLE
Add support non-zero-terminated strings (pointer+size, i.e. std::string_view)

### ISSUE THREAD

**Issue by Hedede** [zeux/pugixml#495]
I use `std::string_view` extensively in my code, because it allows to make substrings very cheaply (requires only adjusting a couple of pointers instead of copying the string), but pugixml accepts only `const char*` arguments, which forces me to make local copies of strings.

It would nice to have either a `std::string_view` overload, or `const char*, size_t` overload.

**Comment by rettinghaus** [comment]
See #73
