### ISSUE TITLE
Will there be support for c#?

### ISSUE THREAD

**Issue by Tomatin** [zeux/pugixml#502]
Is there any chance of future support for c# as native assembly ?

Thanks!

**Comment by zeux** [comment]
pugixml is a C++ library and will remain a C++ library; support for any other languages is outside of the scope of this library. There are various open source externally maintained bindings for other languages, although I'm not aware of any .NET bindings off the top of my head. Building pugixml as C++/CLR is supported so it might be pretty easy to expose a CLR-friendly interface on top, but again this falls outside of the scope of this project.
