### ISSUE TITLE
In the acknowledgement (license) replace "is based on" with "uses"

### ISSUE THREAD

**Issue by ErikDeKoster** [zeux/pugixml#504]
I am reviewing whether I will be using pugixml and found the following in the license section of the manual:

This software is based on pugixml library (https://pugixml.org).
pugixml is Copyright (C) 2006-2022 Arseny Kapoulkine.

I suggest to replace "in based on" with "uses". I think that is based on can be true but is usually to strong.

**Comment by zeux** [comment]
I believe "based on" is the standard legal language for licenses; that said, feel free to replace it with "uses".

**Comment by ErikDeKoster** [comment]
Thanks for the answer!
