### ISSUE TITLE
More intuitive interface for checking if an attribute exists would be nice

### ISSUE THREAD

**Issue by olowo726** [zeux/pugixml#532]
My understanding, please correct me if I'm wrong, is that the correct what to check if an attribute exists is to see if the value is the zero-length string. This yields code such as

```
if (strcmp(requiresSecurityAccessAttr.value(), "read") == 0)
{
...
}
```

which is a bit nonintuitive to read.

**Comment by zeux** [comment]
Please use Discussions to ask questions. You can check if the attribute exists by simply treating it as a boolean value, eg `if (requiresSecurityAccessAttr)`, see https://pugixml.org/docs/manual.html#dom.cpp.

**Comment by olowo726** [comment]
I tried that but it didn't seem to work so I thought it applied only to
elements but I guess I made some kind of mistake.

Den fre 11 nov. 2022 kl 21:39 skrev Arseny Kapoulkine <
***@***.***>:
