### ISSUE TITLE
Be explicit about `children` parameter lifetime

### ISSUE THREAD

**Issue by OleksandrKvl** [zeux/pugixml#538]
Today I spent some time fixing this bug in our code base:

```cpp
const std::string str;
for(auto msg : root.children(std::string(str + "abc").c_str())){ /*...*/ }
```

It's not the best code, I know. However, it's not wrong in general sense, temporary `std::string` still exists during `children()` call. The problem is that `children` returns another object which still relies on that pointer and it's not stated anywhere that it should stay valid not only during `children()` call but during the lifetime of its result. I think it's a good idea to say this explicitly in comment (and maybe for other similar functions as well, don't know if you have them).

**Comment by zeux** [comment]
This definitely warrants a comment.
