### ISSUE TITLE
v1.13 is linking to the dynamic MSVC runtime (dll) even if PUGIXML_STATIC_CRT is set to ON.

### ISSUE THREAD

**Issue by Adnn** [zeux/pugixml#544]
We are building `pugixml` for Windows, linking against the static MSVC runtime. When using v1.9, we were simply setting `STATIC_CRT` to `ON`, and everything was working as expected.

With newer versions of `pugixml`, the CMake variable has been namespaced to `PUGIXML_STATIC_CRT`. Sadly, setting this variable to `ON` does not seem to link against the static RT.

Here is a minimal procedure to illustrate the issue:

* Clone and build pugixml 1.3 and request static runtime:
 
      git clone https://github.com/zeux/pugixml.git --branch v1.13 --depth 1
      cd pugixml
      mkdir build && cd build
      cmake -D PUGIXML_STATIC_CRT=ON ..
      cmake --build . --config Release

* Analyse the result:

      dumpbin /directives Release\pugixml.lib

We get the following output:

>    Linker Directives
>
>    /FAILIFMISMATCH:_MSC_VER=1900
>    /FAILIFMISMATCH:_ITERATOR_DEBUG_LEVEL=0
>    /FAILIFMISMATCH:RuntimeLibrary=MD_DynamicRelease
>    /DEFAULTLIB:msvcprt
>    /FAILIFMISMATCH:_CRT_STDIO_ISO_WIDE_SPECIFIERS=0
>    /DEFAULTLIB:MSVCRT
>    /DEFAULTLIB:OLDNAMES

This indicates that it is linked against `MSVCRT`, which is the [DLL version of the MSVC runtime](https://learn.microsoft.com/en-us/cpp/build/reference/md-mt-ld-use-run-time-library?view=msvc-170).

Are there other requirements to link to the static runtime, or is there an issue with the build procedure?

**Comment by Adnn** [comment]
Thank you for your response @zeux.
This was tested against CMake versions 3.16 and 3.25, with the same result.

Do you mean that this fragment could prevent the correct value to be set on `CMAKE_MSVC_RUNTIME_LIBRARY`?

To test this I added a debug statement locally at line 64: `message("My RUNTIME: ${CMAKE_MSVC_RUNTIME_LIBRARY}")``
And as far as I can tel, the variable was assigned the correct generator expression

> My RUNTIME: MultiThreaded$<$<CONFIG:Debug>:Debug>$<$<NOT:$<BOOL:ON>>:DLL>

**Comment by bruxisma** [comment]
I *thought* this was a simple case of the following line from the [MSVC_RUNTIME_LIBRARY](https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html) documentation where it says

> Note that with [Visual Studio Generators](https://cmake.org/cmake/help/latest/manual/cmake-generators.7.html#visual-studio-generators) the native build system may choose to add its own default runtime library selection flag.

However I'm able to replicate the EXACT same output as the OP with ninja + clang (with gnu command line, but MSVC ABI), ninja + clang-cl, and ninja + msvc.

This doesn't match up with the documentation at all, and even when I explicitly set the property to `MultiThreaded` or `MultiThreadedDebug`, CMake is ignoring it completely. If I block out the `VERSION_LESS` guard for post 3.15 CMake versions, the flags do show up, but we also get a compiler warning as a result.

I'll look into this further.

**Comment by Adnn** [comment]
Hi Isabella!
What a not-so-strange coïncidence to _meet_ you in a CMake related issue ; )

Related to the issue, we use `MSVC_RUNTIME_LIBRARY` in our internal libraries and apps, and there it does behave as expected (i.e. allowing to control which runtime gets linked into the code).

**Comment by zeux** [comment]
I took some time to debug this and it looks like the issue happens because the CMP0091 policy, which is necessary for runtime library variables to work, must be defined before project is. CMake being CMake, defining it after silently does the wrong thing.
