### ISSUE TITLE
xml_parse_result causing stack corruption in MFCx64 project

### ISSUE THREAD

**Issue by Forrest99** [zeux/pugixml#545]
I have an MFCx64 c++ program where `InitInstace()` is calling a ReadXML function that uses pugixml (latest version 1.13). Pugixml was compiled by including the pugixml.cpp file into the project. The creation of a `pugi::xml_parse_result` object is then causing a stack corruption when exiting the ReadXML function (so it might be destruction of the object that is causing trouble).

Minimum code causing the error: 

```
int CMyApp::ReadXML()
{
   pugi::xml_parse_result result1;
   return 0;  //program will throw exception when leaving the function
}

BOOL CMyApp::InitInstance()
{
   int test = ReadXML();

   //rest of InitInstance() here...
}
```
When the code leaves the ReadXML() function I get this exception: `Run-Time Check Failure #2 - Stack around the variable 'result1' was corrupted.` Stack corruption happens in both release and debug (but a few more code lines might be needed to avoid the result1 object to be optimized away in release).

What in this very minimalistic code could be causing a stack corruption???

It should be noted that, of course, this was originally part of a much bigger code base. Initially the problematic code line was `status = pDoc->load_file(file).status;`, or  `status = myDoc.load_file(file).status;` - but that was much harder to debug since the stack corruption was silent (no exceptions, just stack corruption including a messed up this pointer in InitInstance). I have now reason to suspect that it was the creation/deletion of some intermediate xml_parse_result object returned by load_file() that was causing the stack corruption.

More details about the compiler settings causing this error: 
```
Studio: VS2019
Platform: x64
Build: Both Debug and Release 
Toolset: Visual Studio 2019 (v142)
MFC in a static library
Runtime library: /MT or /MTd
Struct alignment: Default
```

**Comment by zeux** [comment]
I'm fairly confident that this is something specific to your setup as pugixml does nothing unusual. It's possible perhaps that the way you're configuring the project, the .obj files for pugixml aren't rebuilt with correct settings. One other possibility is that you're including pugixml.cpp into the project, *and* also linking to some prebuilt library that contains pugixml.obj redundantly. Of course absent an actual example there's not much else that's possible to debug here...

**Comment by Forrest99** [comment]
Thank you for your reply zeux. Sorry, but I forgot to remove this issue when I found out what the root cause was. There was a bad #pragma pack (2) directive on the loose at one place in my codebase that caused the memory corruption. It just happened to show up first in the pugixml part, which I call early in my code.
