### ISSUE TITLE
Comments split Text into multiple Nodes

### ISSUE THREAD

**Issue by jwindgassen** [zeux/pugixml#546]
If you parse the following XML Node:
```xml
<node>
    Lorem ipsum dolor sit amet,
    consetetur sadipscing elitr, <!-- Some Comment -->
    sed diam nonumy eirmod tempor invidunt <!-- ut labore et dolore magna aliquyam erat-->,
    sed diam voluptua.
</node>
```
you will receive a node with 3 children, that contain `Lorem ipsum dolor sit amet,\nconsetetur sadipscing elitr,`, `sed diam nonumy eirmod tempor invidunt` and `,\nsed diam voluptua.`, respectively.

If you enable `parse_comments`, the root will correctly contain 5 nodes, where the 2 comments are between the 3 text nodes.
But if you disable comments, however, the text will still be split into the 3 pieces, whereas one would probably expect them to be parsed into one single node.

I don't know if that is intended behavior, but IMHO it would be better to be parsed into a single node.

~Jonathan

**Comment by zeux** [comment]
This is currently by design. Similar behavior occurs when CDATA or PI nodes are used.

**Comment by vineethkuttan** [comment]
Hi @zeux . I am new here.

> This is currently by design. Similar behavior occurs when CDATA or PI nodes are used.

1 ) I have checked this enhancement and thinking that
before pushing the node_pcdata  , we can check whether the current node has any pcdata node. If so we can concatenate data with that node.
I am stuck with the confusion , what will be the better way.
i)adding the another pointer in the struct xml_node_struct , which will point the current node's pcdata if its is present. (OR)
ii)traversing all the children of the node and check for the pcdata node is present.
Please suggest what will be the better way.

2 )And doing this will change the document structure as you said.
i)So do I need to  add any flag like merge_pcdata or something.
ii)If no flag is needed, what will be the behavior if parse_comments, parse_pi, parse_cdata flag is set? Concatenating even if these flags set to true?

**Comment by zeux** [comment]
There's already a way to check if the last child is PCDATA, eg see how last_root_child is computed in xml_parser::parse. And yeah this would need a flag like parse_merge_pcdata.
