### ISSUE TITLE
Static analyzer: Null pointer dereference

### ISSUE THREAD

**Issue by AnaLGiN83** [zeux/pugixml#555]
Hello!
Svace static analyzer warning seems possible for me, so please confirm or disproof nullptr dereference possibility.

Static analyzer report:
```
After having been compared to a NULL value at pugixml.cpp:2390,
pointer 'dest' is passed as 1st parameter in call to function
'pugi::impl::(anonymous namespace)::xml_allocator::deallocate_string' at pugixml.cpp:2413,
where it is dereferenced at pugixml.cpp:686.
```

https://github.com/zeux/pugixml/blob/c2c61a590508922964a425c603c7016329b14655/src/pugixml.cpp#L2413

**Comment by zeux** [comment]
`dest` can never be null in this branch because `source_length == 0` implicitly checks for that condition. Unsure if your static analyzer processes assertions, adding `assert(dest || source_length == 0);` to the top of the function may help silence this.

**Comment by zeux** [comment]
(probably the `dest` check in the preceding branch can be removed for the same reason, I need to look at the history to understand why it is even there)

**Comment by AnaLGiN83** [comment]
Thanks for explanation!
