### ISSUE TITLE
[BUG] Make stopped with error.  

### ISSUE THREAD

**Issue by jiangqucheng** [zeux/pugixml#556]
Some environments have `$(CXX)` default with lots of preset switches, i.e. `$(CXX) = [GCC] -<preset params> -<preset params> ...`, which is an obstacle to build from makefile.

**Comment by jiangqucheng** [comment]
add a firstword wrapper in CXX
![image](https://user-images.githubusercontent.com/12996850/225520352-f53e2395-6534-4ff1-813a-86fd5bff41b3.png)

**Comment by zeux** [comment]
Yup this makes sense, feel free to submit a PR to fix this
