### ISSUE TITLE
Is reading Chinese garbled?

### ISSUE THREAD

**Issue by BaiFeng666** [zeux/pugixml#564]
![image](https://user-images.githubusercontent.com/69395668/236794293-db828555-b4f4-49a4-b2db-d6a498b8a24c.png)

**Comment by nonwill** [comment]
pugi::xml uses utf8 encoding inside and your CMD console defaults to GBK encoding.
![handict_web_file111](https://user-images.githubusercontent.com/46510529/236809067-8e6efea8-bda3-4895-a2a0-90609901bfc3.gif)
