### ISSUE TITLE
xpath_variable_set Boolean invalid?

### ISSUE THREAD

**Issue by CreatingBug** [zeux/pugixml#565]
I set a Boolean value for `xpath_variable_set `, but it didn't work.

'condition="false"' is also among them.

```
int main()
{
	const char* xml = R"(
        <?xml version="1.0"?>
        <root>
            <node condition="true" />
            <node condition="false" />
            <node condition="true" />
        </root>
    )";
	xml_document doc;
	xml_parse_result result = doc.load_string(xml);
	if (result)
	{
		xpath_variable_set vars;
		vars.set("value", true);
		xpath_node_set nodes = doc.select_nodes("//node[@condition=$value]", &vars);
		for (auto node : nodes)
		{
			cout << "condition: " << node.node().attribute("condition").as_string() << endl;
		}
	}
	return 0;
}
```

**Comment by zeux** [comment]
XPath booleans don't work like you're expecting them to, they compare as-if both sides have boolean() function applied, which treats only empty strings as false, see https://www.w3.org/TR/1999/REC-xpath-19991116/#function-boolean

You need to set the variable to a string "true" or "false" to have this work.

**Comment by CreatingBug** [comment]
> XPath 布尔值不像你期望的那样工作，它们比较好像双方都应用了布尔（）函数，该函数仅将空字符串视为假，请参阅 https://www.w3.org/TR/1999/REC-xpath-19991116/#function-boolean
> 
> 您需要将变量设置为字符串“true”或“false”才能正常工作。

thank you!
