### ISSUE TITLE
Assertion fails during number-to-string conversion if wrong C locale is set (non-MSVC)

### ISSUE THREAD

**Issue by crawlserv** [zeux/pugixml#574]
I was debugging a strange failed assertion in the library that only occurred when I called a seemingly unrelated function by another library. Then I realized that pugixml uses `sprintf` for number-to-string conversion and the `assert` checks the decimal point without taking into account that the current C locale could use a different character than `'.'`.

Thus, if the C locale is set to German, for example,

https://github.com/zeux/pugixml/blob/187cf6b5a53d606c0114e917ea02ba06bfdbf21c/src/pugixml.cpp#L8461

will fail due to `mantissa[1]` being `','`.

**Workaround:** Calling `setlocale(LC_ALL, "C");` before calling functions such as `pugi::xpath_query::evaluate_string()` avoids this problem but is NOT thread-safe.

**Comment by zeux** [comment]
Ah, well, this is unfortunate :-/

The assertion can certainly ignore commas, which is probably "fine" in practice; a better fix would be to use ecvt_r when available but that appears to be deprecated so may not always be "safe" to use from the compile time warning perspective.

XPath number parsing also uses strtod which will silently truncate characters after decimal point on German locales, and that is more difficult to fix, probably requiring C++17. Maybe that can be left for another day.
