### ISSUE TITLE
Support std::filesystem::path

### ISSUE THREAD

**Issue by TheFGFSEagle** [zeux/pugixml#575]
Could you add overloads of xml_document::load_file that accept std::string and std::filesystem::path as types for the path argument ?

**Comment by zeux** [comment]
Using `.c_str()` on either std::string or std::filesystem::path should be sufficient - you can pass the resulting pointer to `load_file` or `save_file`.

**Comment by TheFGFSEagle** [comment]
Ah ok, that works - thanks ! :)
