### ISSUE TITLE
parse_embed_pcdata and parse_merge_pcdata don't play together

### ISSUE THREAD

**Issue by schulzer** [zeux/pugixml#600]
`pugi::parse_embed_pcdata | pugi::parse_merge_pcdata` can't be used together. The following document
```xml
<node>curse<!--trickery-->word</node>
```
would yield
```cpp
doc.child("node").child_value()
    -> "curse"
doc.child("node").first_child().type() 
    -> node_pcdata

for (pugi::xml_node current : doc.child("node").children())
    result += current.value()
    -> "word"
```
if only `pugi::parse_merge_pcdata` would be used the same code would yield
```cpp
doc.child("node").child_value()
    -> "curseword"
doc.child("node").first_child().type() 
    -> node_pcdata

for (pugi::xml_node current : doc.child("node").children())
    result += current.value()
    -> "curseword"
```

other flags I had set:
- `pugi::parse_default`
- `pugi::parse_trim_pcdata`
- `pugi::parse_ws_pcdata`
- `pugi::parse_wnorm_attribute`

**Comment by zeux** [comment]
Yes, this was an intentional limitation, as it simplifies the logic during the parsing flow. This can probably be fixed if you need to use this combination.

**Comment by schulzer** [comment]
I do not really need it, I thought it could save memory never the less (even in non constraint environments), but if it is not _fixed_ then the documentation should be updated to clarify that those options may not be used in conjunction.
