### ISSUE TITLE
Unexpected #endif in line 13201 with precompilation in a pch.h file

### ISSUE THREAD

**Issue by anschulz72** [zeux/pugixml#601]
I want to use the pugixml in a wui3 application to read data from the XML file. When pre-compiling, I get an error that an unexpected #endif appears. at first glance, everything looks okay to me.

How can I use pugixml in wui 3 apps and what needs to be adapted.

**Comment by zeux** [comment]
I'm assuming you just added pugixml.cpp to your project that uses a PCH file. In that case you either need to disable PCH for pugixml.cpp specifically, or maybe edit it to add your pch include before line 14 (before first preprocessor directive). Alternatively you could compile pugixml as a separate static library that doesn't use PCH.

**Comment by anschulz72** [comment]
Thank you, your comment was helpful in fixing the problem.
