### ISSUE TITLE
Error in handling loading errors example

### ISSUE THREAD

**Issue by OleksandrKvl** [zeux/pugixml#607]
Does it make any sense to output attribute's value in presence of errors?

https://github.com/zeux/pugixml/blob/96aebcb8ae2062ad020186e32fd301db7c3a0c88/docs/samples/load_error_handling.cpp#L17

**Comment by zeux** [comment]
Yes, this example explicitly demonstrates that when parsing errors, you still get an incomplete tree that you can process if you’d like.
