### ISSUE TITLE
Serilisation 

### ISSUE THREAD

**Issue by naushadck** [zeux/pugixml#612]
This might be a dumb question - I'm  serializing using pugi::xml_document.
But i could not find any proper way to achieve the same. 

Any input is highly appreciable.

**Comment by zeux** [comment]
Not sure what this is asking about but I'm very sure that this is not a bug and should not be an issue report.

**Comment by naushadck** [comment]
How to serialise an object in  pugi::xml...

**Comment by naushadck** [comment]
How to serialise/deserialise an object/class using pugi::xml...

**Comment by brandl-muc** [comment]
pugixml is an XML parser, not a serialization framework. You need to write that yourself or use a different library like Boost.Serialization.
