### ISSUE TITLE
Warnings (C5245) when having PUGIXML_NO_STL and PUGIXML_API defined

### ISSUE THREAD

**Issue by BobbyAnguelov** [zeux/pugixml#619]
Hi,

When compiling pugixml and having the PUGIXML_API/PUGIXML_CLASS definitions set as well as PUGIXML_NO_STL, I get a bunch of C5245 warnings:

```
1>pugixml.cpp(262,22): warning C5245: 'pugi::impl::`anonymous-namespace'::strlength_wide': unreferenced function with internal linkage has been removed
1>pugixml.cpp(2311,22): warning C5245: 'pugi::impl::`anonymous-namespace'::as_utf8_begin': unreferenced function with internal linkage has been removed
1>pugixml.cpp(2317,20): warning C5245: 'pugi::impl::`anonymous-namespace'::as_utf8_end': unreferenced function with internal linkage has been removed
```

I've added ```#   pragma warning(disable: 5245) // unreferenced function with internal linkage has been removed``` to ln54 in the cpp to resolve this. Might be good to either ifdef the functions for ```#define PUGIXML_NO_STL``` or add the warning disable pragma.

**Comment by zeux** [comment]
I don't get this in a stock shared library build (which defines _API/_CLASS as dllexport) when enabling NO_STL, and using /W4. MSDN lists this warning as off by default (here https://learn.microsoft.com/en-us/cpp/preprocessor/compiler-warnings-that-are-off-by-default?view=msvc-170) - I'm wondering if you are enabling this warning explicitly?

**Comment by zeux** [comment]
fwiw all three functions are not ifdef'd behind NO_STL because they can be used for the implementation of `load_file(const wchar_t*)` on other platforms even if STL APIs are disabled, and that define chain is  rather long and gnarly. So disabling the warning with a pragma is probably the most reasonable solution.

**Comment by BobbyAnguelov** [comment]
Ah yeh, I'm running with /Wall so that warning is enabled for me.

**Comment by zeux** [comment]
Could you post a full set of warning flags you're using? I've generally considered Wall impractical in MSVC in the past, as when enabled it generates decidedly too many warnings (on pugixml I get an assortment of "inline function can't be inlined", "padding added", etc etc etc), but maybe you're using a significantly reduced set, and I want to make sure I can actually reproduce your configuration exactly before considering a fix.

**Comment by BobbyAnguelov** [comment]
Yeh, I have a bunch of the really annoying ones disabled, here's the exact setup:

```xml
<WarningLevel>EnableAllWarnings</WarningLevel>
<DisableSpecificWarnings>4189;4946;4191;5220;4266;4623;4711;4388;4355;5031;4774;4582;4365;5246;4061;5219;4514;4505;4251;4100;4127;4201;4577;4464;4668;4710;4820;5052;4619;4625;4626;5026;5027;5045;26495;5262;5264;5267;</DisableSpecificWarnings>
```

**Comment by zeux** [comment]
Ok great, thanks. It also occurred to me that this might be a problem with mingw, and indeed I get these with "-Wall -Wextra -DPUGIXML_NO_STL" - on MinGW I would expect -Wall to be a production ready configuration, so this needs tweaks.

![image](https://github.com/zeux/pugixml/assets/1106629/80e17c6f-22a9-4aa3-a39f-cab4fc1bb6c6)
