### ISSUE TITLE
Simplified closing tag

### ISSUE THREAD

**Issue by 1vanK** [zeux/pugixml#625]
The lib can parse
```
<window title="Title">
	<controls>
		<button text="Text" />
	</>
</>
```

Is it possible to force the lib to save in this form?

**Comment by 1vanK** [comment]
Something like this:

```
PUGI_IMPL_FN void node_output_end(xml_buffered_writer& writer, xml_node_struct* node)
{
    const char_t* default_name = PUGIXML_TEXT(":anonymous");
    const char_t* name = node->name ? node->name + 0 : default_name;

    writer.write('<', '/');
#ifndef SIMPIFIED
    writer.write_string(name);
#endif
    writer.write('>');
}
```

**Comment by zeux** [comment]
> The lib can parse

This is not a valid XML. pugixml correctly rejects it. As described in https://pugixml.org/docs/manual.html#loading.errors, you still get access to the part of the tree that was successfully parsed (which would be up until the first "closing" tag).

Since this is not a valid XML and it can't be parsed it would not make sense to add a feature to write it out.

**Comment by 1vanK** [comment]
> Since this is not a valid XML and it can't be parsed it would not make sense to add a feature to write it out.

As far as I know, in XML tags are always paired (unlike in HTML), so the closing tag name is redundant.

RapidJson for example has parse flags for non-standard JSON formats:

```
enum ParseFlag {
    ...
    kParseCommentsFlag = 32,        //!< Allow one-line (//) and multi-line (/**/) comments.
    ...
    kParseTrailingCommasFlag = 128, //!< Allow trailing commas at the end of objects and arrays.
    ...
};
```

**Comment by zeux** [comment]
They are redundant in principle but omitting their name is not standard or commonly supported; in contrast, the RapidJSON flags you mentioned are part of json5.

**Comment by 1vanK** [comment]
Well we can call the modified xml "xml3000" xD
