### ISSUE TITLE
Add support for pre-defined "character entities"

### ISSUE THREAD

**Issue by mominul** [zeux/pugixml#68]
Hi, Please add support for pre-defined "character entities". Namely
```
    &amp;   &
    &lt;    <
    &gt;    >
    &quot;  "
    &apos;  '
```
Because I am parsing a xml like this one -
```
  ...
  <DeveloperComment>
    <![CDATA[The original layout was designed by &apos;The Safeworks&apos;, in 1996-1998.

  OmicronLab redesigned this layout a bit to enable UNICODE support.
  ]]> </DeveloperComment>
  ...
```

test.cpp -
```
...
cout << "Description " << key.child("DeveloperComment").text().as_string() << endl;
...
```
result:
```
Description The original layout was designed by &apos;The Safeworks&apos;, in 1996-1998.

OmicronLab redesigned this layout a bit to enable UNICODE support.
```

So the "character entities" are not getting processed.

Thanks!
Sorry for bad English!

**Comment by zeux** [comment]
Character entities should not get processed in a CDATA section:

> Within a CDATA section, only the CDEnd string is recognized as markup, so that left angle brackets and ampersands may occur in their literal form; they need not (and cannot) be escaped using " &lt; " and " &amp; ". CDATA sections cannot nest.

http://www.w3.org/TR/REC-xml/

**Comment by mominul** [comment]
Thanks for your clarification! Might be it was the problem of the program. The program used NativeXML for parsing and writing the XML. So the parser might not followed the standards.

Thanks!

**Comment by zeux** [comment]
If you really need to work with CDATA sections with char escapes, you can write a function to unescape it:

```
std::string parseEscapes(const char* value)
{
    pugi::xml_document doc;
    if (!doc.load_string(value, pugi::parse_fragment | pugi::parse_escapes)) return value;

    return doc.text().as_string();
}
```

**Comment by mominul** [comment]
Thanks! It is needed by me!

Many many Thanks!!!
