### ISSUE TITLE
xml_node is distroyed after loading

### ISSUE THREAD

**Issue by changshen** [zeux/pugixml#71]
```c++
class myxmltool
{
public:
	string filename;
	xml_node root;
	myxmltool(string fname)
	{
		xml_document doc;
		doc.load_file(fname.c_str());
		root = xml_node(doc.root());  //root is created and has contents
	}

};

void main()
{
	myxmltool tool = myxmltool("c:\\myxmlfile.xml");
	xml_node rootnode = tool.root;  //root was not there.  it was distroyed already

}
```

**Comment by jima80525** [comment]
Isn't that because the doc has already been destructed?  If you make the
doc a member of the class so it has not been freed, it will work.
Change the class to:
class myxmltool
{
    public:
        string filename;
        xml_node root;
        xml_document doc;

        myxmltool(string fname)
        {
            doc.load_file(fname.c_str());
            root = xml_node(doc.root()); //root is created and has contents
        }

};


jima

**Comment by zeux** [comment]
xml_document object controls the lifetime of the tree; xml_node objects are just handles to nodes of that tree. Destroying the xml_document object leads to the entire tree being destroyed; it's invalid to use the nodes from the tree after that. This is described in more detail in this section of the manual: http://pugixml.org/docs/manual.html#dom.cpp.

**Comment by changshen** [comment]
Thanks zeux and jima
I thought of this and tried to have xml_document as a member of extended class.  But compiler complained : 
Error	2	error C2248: 'pugi::xml_document::xml_document' : cannot access private member declared in class 'pugi::xml_document'	
even with empty constructor 
 myxmltool(string fname){}
