### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by changshen** [zeux/pugixml#72]
Hi all
I got this error and cannot understand.

Error	2	error C2248: 'pugi::xml_document::xml_document' : cannot access private member declared in class 'pugi::xml_document'

        class mxmltool 
        {
            public: 
	        xml_node root;
	        xml_document doc; 
	        mxmltool(string fname) 
	        {
		        doc.load_file(fname.c_str()); 
		        root = xml_node(doc.root()); 
	        }  
        }; 

        int main(int argc, char* argv[])
        {
	        mxmltool tool = mxmltool("c:\\myxmlfile.xml");
	        xml_node rootnode = xml_node(tool.root);  	
	        return 0;
        }

**Comment by zeux** [comment]
xml_document is not copyable.

You can use this syntax to create your object (that does not require copying):

   mxmltool tool("c:\\myxmlfile.xml");

Or keep a std::unique_ptr/std::shared_ptr to xml_document instead of embedding by value.

**Comment by changshen** [comment]
Thanks
This works.  The following also works
class mxmltool 
{
public: 
	pugi::xml_node root;
	string filename; 
	xml_document *doc = NULL; 
	mxmltool(string fname) 
	{
		doc = new xml_document();
		doc->load_file(fname.c_str()); 
		root = xml_node(doc->root()); 
	} 
}; 


int _tmain(int argc, _TCHAR* argv[])
{
	mxmltool tool = mxmltool("c:\\myxmlfile.xml");
	xml_node rootnode = xml_node(tool.root);  //rootnode was empty	
	return 0;
}

**Comment by zeux** [comment]
Caution: your code example has a memory leak (xml_document is never destroyed) - which is why I suggested std::shared_ptr as one possible solution.
