### ISSUE TITLE
wish to add another xml_node::traverse function meber

### ISSUE THREAD

**Issue by baixuefeng** [zeux/pugixml#77]
at present, the xml_node::traverse function:
...
if (!walker.for_each(arg_for_each))
    return false;
...

But, sometimes, I want to use it like this:
...
if (walker.for_each(arg_for_each) && cur.first_child())
{
    // traverse it's child tree
}
else
...

**Comment by zeux** [comment]
I don't understand the use case. Why can't you check this condition inside your for_each implementation?

**Comment by baixuefeng** [comment]
case 1: when function "for_each" return false , the all traverse ended.
case 2: when function "for_each" return false, it mean that it only will not traverse it's child tree, but will continue to traverse it's sibling.

**Comment by zeux** [comment]
Ah, right. Yeah, this makes sense. Unfortunately, I can't easily change the existing interface because of binary compatibility issues. The interface has some other problems as well (e.g. https://code.google.com/p/pugixml/issues/detail?id=219)

**Comment by baixuefeng** [comment]
Haha, I think so too.

**Comment by zeux** [comment]
Closing in favor of #103, which has several different options and thoughts on the matter.
