### ISSUE TITLE
Missing operator=(unsigned long) and (long) causes compile error on some systems.

### ISSUE THREAD

**Issue by deathbaba** [zeux/pugixml#78]
For example:
```
error: use of overloaded operator '=' is ambiguous (with operand types 'pugi::xml_attribute' and 'const unsigned long')
    node.append_attribute(attribute) = v;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^ ~
```

**Comment by deathbaba** [comment]
Possible solution is here: https://github.com/deathbaba/omim/commit/6f50afe26e56fd3c36c23ba2b0028287cd5809eb

**Comment by zeux** [comment]
I'm not 100% sure if this is a bug or a feature.

long type has an unpredictable size on various platforms (it's 8 bytes on 64-bit Linux/Mac but 4 bytes on 64-bit Windows and all 32-bit platforms). Is there a reason why the calling code uses long instead of e.g. long long?

**Comment by deathbaba** [comment]
The calling code uses uint64_t. It works on many platforms, but fails on Linux.

Pugixml should use intXX_t and uintXX_t to avoid compilation issues.

**Comment by zeux** [comment]
Ugh, I see. The inconsistent mapping of uint64_t to basic types is annoying.

I'm not sure if I can use uin64_t - in general pugixml avoids using these types in the interface because they are not universally available. Maybe it is fine if PUGIXML_HAS_LONG_LONG is defined. Alternative approach is to add overloads for long/unsigned long, similar to your patch.

**Comment by deathbaba** [comment]
As far as I know, C++11 has all these types defined: http://en.cppreference.com/w/cpp/types/integer <http://en.cppreference.com/w/cpp/types/integer>

**Comment by zeux** [comment]
I decided to go ahead with long/unsigned long support for setters. That makes various setters have a signature along the lines of std::to_string. It could lead to inconsistent behavior between platforms if the calling code uses long type explicitly, but that is the problem of the calling code regardless of the type support in pugixml.
