### ISSUE TITLE
string_to_integer(const char_t* value, U minneg, U maxpos) clips values, does not throw to indicate out-of-bounds error.

### ISSUE THREAD

**Issue by hallsoftware** [zeux/pugixml#86]
When parsing XML files, string_to_integer(...) clips invalid values to max or min values and does not indicate that invalid values are found.  I would prefer that this function throws some out-of-bounds exception.

**Comment by zeux** [comment]
This is consistent with the previous behavior (when using strtoll etc.). Of course indicating an error is better.

While throwing an exception is not a good idea (pugixml does not use exceptions for the most part, xpath_exception being the only unfortunate... uh... exception), especially at this stage where it would throw for callers that do not anticipate it, there are potential alternatives.

Improvements to handling issues like this are tracked in #15.
