### ISSUE TITLE
Extra space in empty node

### ISSUE THREAD

**Issue by JayXon** [zeux/pugixml#87]
`<node/>` will become `<node />` even if format_raw is set.
Is this intended?

**Comment by zeux** [comment]
This is intended.

pugixml does not keep internal whitespace inside nodes for performance/memory reasons. So format_raw emits XML with a fixed markup which for I guess style/historical reasons ended up having a space before /.

**Comment by JayXon** [comment]
Thanks for the response.
IMHO people would care more about XML size than style if they are using format_raw since it's usually used in serialization and it's not intended to be read by humans.

**Comment by zeux** [comment]
Right, so there is no way to preserve the formatting in general - but it is of course possible to change format_raw output to always remove the space.

It does make sense, I guess - this may be literally the only character that's printed in format_raw mode that is not *required* to be there for XML to round-trip... I'll look into this a bit more.

**Comment by zeux** [comment]
Changing this breaks 110 unit tests :) which is not surprising and easy to fix.
I have no way of knowing whether any users depend on the existing behavior. Most likely the answer is "no", and there have been some minor formatting changes in the past like that.

Libraries that always add a space:
* .NET (XmlWriter)
* TinyXML
* Python xml.etree.ElementTree

Libraries that don't add a space:
* libxml2
* rapidxml
* TinyXML2
* Python xml.dom.minidom
