### ISSUE TITLE
update for EL7 ?

### ISSUE THREAD

**Issue by tmdag** [zeux/pugixml#98]
Hi!
I've found few applications that are using your library, unfortunately their implementation requires latest version (at least 1.2 and above) and your latest version for EL7 is 1.0.6. Are you planning to update Centos7/EL7 soon ?

Cheers!

**Comment by zeux** [comment]
I do not maintain pugixml packages for Linux distributions.

My understanding is that the maintainer for pugixml for CentOS is @hobbes1069 - he would probably be the person to ask about version update (I have no idea how this works).

FWIW, 1.7 is source-compatible all the way back to 1.0. I believe there was an ABI change in 1.2 so the .so name will have to change (I *think* 1.7 is ABI-compatible with 1.2 but it does not matter that much if the current version in CentOS is 1.0).
