### ISSUE TITLE
CMake Configuration failed for Visual Studio 9 2008

### ISSUE THREAD

**Issue by yuvarajvelumani** [zeux/pugixml#99]
I tried to Configure the pugixml source code for Visual studio 2008, but it gave me error like 

CMake Error at CMakeLists.txt:30 (target_compile_features):
  target_compile_features no known features for CXX compiler
  "MSVC"
  version 15.0.30729.1.
Configuring incomplete, errors occurred!

I am using CMake Version 3.5.2. Should I need to try with lower version of CMake like less than 3.1

**Comment by zeux** [comment]
You should be able to just comment out this line in CMakeLists.txt:

	target_compile_features(pugixml PUBLIC cxx_long_long_type)

It's an issue with the CMakeLists.txt though - I'll look into this.

**Comment by zeux** [comment]
I pushed a fix for CMakeLists.txt that should resolve this issue - can you confirm that this is the case?
